### ISSUE TITLE
How to serve multiple simultaneous request in Ollama?

### ISSUE THREAD

**Issue by austin-starks** [ollama/ollama#1400] opened 2023-12-06 15:27 UTC
Hello!

I want to deploy Ollama in the cloud server. The cloud server I'm renting is big enough to handle multiple requests at the same time with the models I'm using. However, Ollama queues the request. What specific changes do I need to make for this to be possible? And, is there any way for this to be an additional configuration option added to the Ollama repo?

**Comment by technovangelist** [comment] 2023-12-06 20:08
For now Ollama is designed to provide a great experience on your local machine for a single user. It is designed to queue the request and then it will get to the next request after the current one is complete. We intend to look at making a better server experience in the future.

**Comment by phalexo** [comment] 2023-12-07 18:34
If you wanted to do the work, you could probably set up a process pool, which would take work off its own queue and then managing multiple ollama(s) running against different GPUs. It is messy of course.

**Comment by ciliamadani** [comment] 2023-12-19 20:53
Hello @austin-starks, what alternatives are you considering if I may know, I'm in the same situation and would like to know the available options.
Thank you in advance.

**Comment by ParisNeo** [comment] 2024-01-09 08:30
Maybe you can create multiple instances of the server with different port numbers

**Comment by ParisNeo** [comment] 2024-01-09 09:44
> For now Ollama is designed to provide a great experience on your local machine for a single user. It is designed to queue the request and then it will get to the next request after the current one is complete. We intend to look at making a better server experience in the future. 

It is fine to have a single generation with a queue. But can you add an endpoint to ask fir que status?

I want to launch multiple instances of the server to solve this multi users problem. But i need to put a disparcher in front of them. I need to be able to know the state of each queue to dispatch the connections.

**Comment by m0wer** [comment] 2024-01-17 12:49
Sounds like something https://github.com/vllm-project/vllm has sorted out (queuing + configurable number of workers).

**Comment by ParisNeo** [comment] 2024-01-18 08:25
except vllm doesn't know how to run GGUF models and is  very hungry in terms of memory consumption.

**Comment by m0wer** [comment] 2024-01-18 09:04
> except vllm doesn't know how to run GGUF models and is very hungry in terms of memory consumption.

Agreed. Would be great to have parallelism in Ollama instead.

**Comment by easp** [comment] 2024-01-18 17:04
Depending on what level of concurrency you are after, quantization can be counterproductive. Using quantized models requires more compute, which ends up becoming the bottleneck at higher levels of concurrency.

**Comment by pdevine** [comment] 2024-01-26 23:54
Going to close this as a dupe of #358

**Closed by pdevine** 2024-01-26 23:54 UTC
