### ISSUE TITLE
ollama on Proxmox??

### ISSUE THREAD

**Issue by Paulie420** [ollama/ollama#1495] opened 2023-12-13 04:08 UTC
So I know this is user error, but... I can install and use ollama on my Framework laptop (without GPU) easily. Install w/ curl command and get going right away - but on a ProxMox VM w/ MORE RAM than my Framework, I get an Error ollama failed at the run command.

Am I missing something simple that I can 'fix'? I feel like my server has more CPU than my laptop - and wondering if others are running ollama on Proxmox w/o GPU?

**Comment by rgaidot** [comment] 2023-12-13 09:42
You've deploy ollama on CT or VM? On which OS? How many resources have you allocated?

_FYI, I've deploy on CT on Debian with 16GB RAM and I haven't GPU activated (gpu passthrough)_

-  Ryzen 7 5800H 
- 64GB RAM DDR4
- 500GB M.2 NVME SSD
- SSD Crucial MX500 1To

**Comment by Cybervet** [comment] 2023-12-13 16:17
I managed to run Ollama in proxmox fine in a old workstation withou AVX capable cpu. It runs in a CT (without GPU) slow, but on a VM with GPU passthrough runs fine. Just to mention that on the VM I compile the code not just d/l it.

**Comment by Paulie420** [comment] 2023-12-17 00:32
I ran on a VM w/ 4 cores and 16GB of RAM - but it IS a Debian server... I was thinking maybe I need graphics packages installed??? LOL - works just fine on my GUI/Plasma laptop. 

Am I forgetting something simple???

**Comment by FlPie** [comment] 2023-12-20 15:14
I encountered a similar issue with a Proxmox VM. I believe the cause is related to AVX, SSE4, or other advanced instruction sets.

You may be able to resolve it by changing the type of processors assigned to the VM in Proxmox.

For me, setting the CPU type to "host" in Proxmox has worked as a solution.

Additional information can be found at the Proxmox forum:
https://forum.proxmox.com/threads/avx2-and-avx-flags-on-vm.87808/

**Comment by abayomi185** [comment] 2023-12-29 04:38
I recently set up GPU passthrough (Nvidia) to an LXC container running Ollama. If it helps anyone, here's how I did it:
https://yomis.blog/nvidia-gpu-in-proxmox-lxc/

**Comment by dhiltgen** [comment] 2024-01-27 01:39
We've recently added CPU variants so that Ollama can run on CPUs without AVX support.  This should cover proxmox, although you should expect a pretty massive performance hit.  I would recommend enabling host CPU in the advanced settings, but regardless, it will work without AVX now.

https://forum.proxmox.com/threads/avx2-and-avx-flags-on-vm.87808/

**Closed by dhiltgen** 2024-01-27 01:39 UTC

**Comment by DocMAX** [comment] 2024-02-24 21:50
I tried with AMD iGPU 5800U and RX5700. Can't get it to work.
Passing /dev/dri and /dev/kfd to a LXC container. Ollama detects ROCm but stuck.

**Comment by tristan-k** [comment] 2024-09-20 12:36
I recently tried to run [IPEX-LLM](https://github.com/intel-analytics/ipex-llm) on a Proxmox 8 host inside a Ubuntu 24.04 LXC but for some unkown reason ollama just gives empty answers.

```
./ollama serve
2024/09/20 14:34:34 routes.go:1125: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/root/.ollama/models OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://*] OLLAMA_RUNNERS_DIR: OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-09-20T14:34:34.932+02:00 level=INFO source=images.go:753 msg="total blobs: 5"
time=2024-09-20T14:34:34.932+02:00 level=INFO source=images.go:760 msg="total unused blobs removed: 0"
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] POST   /api/pull                 --> github.com/ollama/ollama/server.(*Server).PullModelHandler-fm (5 handlers)
[GIN-debug] POST   /api/generate             --> github.com/ollama/ollama/server.(*Server).GenerateHandler-fm (5 handlers)
[GIN-debug] POST   /api/chat                 --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (5 handlers)
[GIN-debug] POST   /api/embed                --> github.com/ollama/ollama/server.(*Server).EmbedHandler-fm (5 handlers)
[GIN-debug] POST   /api/embeddings           --> github.com/ollama/ollama/server.(*Server).EmbeddingsHandler-fm (5 handlers)
[GIN-debug] POST   /api/create               --> github.com/ollama/ollama/server.(*Server).CreateModelHandler-fm (5 handlers)
[GIN-debug] POST   /api/push                 --> github.com/ollama/ollama/server.(*Server).PushModelHandler-fm (5 handlers)
[GIN-debug] POST   /api/copy                 --> github.com/ollama/ollama/server.(*Server).CopyModelHandler-fm (5 handlers)
[GIN-debug] DELETE /api/delete               --> github.com/ollama/ollama/server.(*Server).DeleteModelHandler-fm (5 handlers)
[GIN-debug] POST   /api/show                 --> github.com/ollama/ollama/server.(*Server).ShowModelHandler-fm (5 handlers)
[GIN-debug] POST   /api/blobs/:digest        --> github.com/ollama/ollama/server.(*Server).CreateBlobHandler-fm (5 handlers)
[GIN-debug] HEAD   /api/blobs/:digest        --> github.com/ollama/ollama/server.(*Server).HeadBlobHandler-fm (5 handlers)
[GIN-debug] GET    /api/ps                   --> github.com/ollama/ollama/server.(*Server).ProcessHandler-fm (5 handlers)
[GIN-debug] POST   /v1/chat/completions      --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (6 handlers)
[GIN-debug] POST   /v1/completions           --> github.com/ollama/ollama/server.(*Server).GenerateHandler-fm (6 handlers)
[GIN-debug] POST   /v1/embeddings            --> github.com/ollama/ollama/server.(*Server).EmbedHandler-fm (6 handlers)
[GIN-debug] GET    /v1/models                --> github.com/ollama/ollama/server.(*Server).ListModelsHandler-fm (6 handlers)
[GIN-debug] GET    /v1/models/:model         --> github.com/ollama/ollama/server.(*Server).ShowModelHandler-fm (6 handlers)
[GIN-debug] GET    /                         --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func1 (5 handlers)
[GIN-debug] GET    /api/tags                 --> github.com/ollama/ollama/server.(*Server).ListModelsHandler-fm (5 handlers)
[GIN-debug] GET    /api/version              --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func2 (5 handlers)
[GIN-debug] HEAD   /                         --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func1 (5 handlers)
[GIN-debug] HEAD   /api/tags                 --> github.com/ollama/ollama/server.(*Server).ListModelsHandler-fm (5 handlers)
[GIN-debug] HEAD   /api/version              --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func2 (5 handlers)
time=2024-09-20T14:34:34.933+02:00 level=INFO source=routes.go:1172 msg="Listening on 127.0.0.1:11434 (version 0.3.6-ipexllm-20240920)"
time=2024-09-20T14:34:34.933+02:00 level=INFO source=payload.go:30 msg="extracting embedded files" dir=/tmp/ollama499157638/runners
time=2024-09-20T14:34:35.027+02:00 level=INFO source=payload.go:44 msg="Dynamic LLM libraries [cpu cpu_avx cpu_avx2]"
[GIN] 2024/09/20 - 14:35:01 | 200 |     342.519µs |       127.0.0.1 | HEAD     "/"
[GIN] 2024/09/20 - 14:35:01 | 200 |    32.81047ms |       127.0.0.1 | POST     "/api/show"
time=2024-09-20T14:35:02.011+02:00 level=INFO source=gpu.go:168 msg="looking for compatible GPUs"
time=2024-09-20T14:35:02.012+02:00 level=WARN source=gpu.go:560 msg="unable to locate gpu dependency libraries"
time=2024-09-20T14:35:02.012+02:00 level=WARN source=gpu.go:560 msg="unable to locate gpu dependency libraries"
time=2024-09-20T14:35:02.013+02:00 level=WARN source=gpu.go:560 msg="unable to locate gpu dependency libraries"
time=2024-09-20T14:35:02.014+02:00 level=INFO source=gpu.go:280 msg="no compatible GPUs were discovered"
time=2024-09-20T14:35:02.048+02:00 level=INFO source=memory.go:309 msg="offload to cpu" layers.requested=-1 layers.model=43 layers.offload=0 layers.split="" memory.available="[31.6 GiB]" memory.required.full="8.4 GiB" memory.required.partial="0 B" memory.required.kv="2.6 GiB" memory.required.allocations="[8.4 GiB]" memory.weights.total="7.0 GiB" memory.weights.repeating="6.3 GiB" memory.weights.nonrepeating="717.8 MiB" memory.graph.full="507.0 MiB" memory.graph.partial="1.2 GiB"
time=2024-09-20T14:35:02.053+02:00 level=INFO source=server.go:395 msg="starting llama server" cmd="/tmp/ollama499157638/runners/cpu_avx2/ollama_llama_server --model /root/.ollama/models/blobs/sha256-ff1d1fc78170d787ee1201778e2dd65ea211654ca5fb7d69b5a2e7b123a50373 --ctx-size 8192 --batch-size 512 --embedding --log-disable --n-gpu-layers 999 --no-mmap --parallel 4 --port 36611"
time=2024-09-20T14:35:02.053+02:00 level=INFO source=sched.go:450 msg="loaded runners" count=1
time=2024-09-20T14:35:02.053+02:00 level=INFO source=server.go:595 msg="waiting for llama runner to start responding"
time=2024-09-20T14:35:02.053+02:00 level=INFO source=server.go:629 msg="waiting for server to become available" status="llm server error"
INFO [main] build info | build=1 commit="1810c22" tid="131835344998976" timestamp=1726835702
INFO [main] system info | n_threads=14 n_threads_batch=-1 system_info="AVX = 0 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 0 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | " tid="131835344998976" timestamp=1726835702 total_threads=12
INFO [main] HTTP server listening | hostname="127.0.0.1" n_threads_http="11" port="36611" tid="131835344998976" timestamp=1726835702
llama_model_loader: loaded meta data with 29 key-value pairs and 464 tensors from /root/.ollama/models/blobs/sha256-ff1d1fc78170d787ee1201778e2dd65ea211654ca5fb7d69b5a2e7b123a50373 (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = gemma2
llama_model_loader: - kv   1:                               general.name str              = gemma-2-9b-it
llama_model_loader: - kv   2:                      gemma2.context_length u32              = 8192
llama_model_loader: - kv   3:                    gemma2.embedding_length u32              = 3584
llama_model_loader: - kv   4:                         gemma2.block_count u32              = 42
llama_model_loader: - kv   5:                 gemma2.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                gemma2.attention.head_count u32              = 16
llama_model_loader: - kv   7:             gemma2.attention.head_count_kv u32              = 8
llama_model_loader: - kv   8:    gemma2.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv   9:                gemma2.attention.key_length u32              = 256
llama_model_loader: - kv  10:              gemma2.attention.value_length u32              = 256
llama_model_loader: - kv  11:                          general.file_type u32              = 2
llama_model_loader: - kv  12:              gemma2.attn_logit_softcapping f32              = 50.000000
llama_model_loader: - kv  13:             gemma2.final_logit_softcapping f32              = 30.000000
llama_model_loader: - kv  14:            gemma2.attention.sliding_window u32              = 4096
llama_model_loader: - kv  15:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  16:                         tokenizer.ggml.pre str              = default
llama_model_loader: - kv  17:                      tokenizer.ggml.tokens arr[str,256000]  = ["<pad>", "<eos>", "<bos>", "<unk>", ...
llama_model_loader: - kv  18:                      tokenizer.ggml.scores arr[f32,256000]  = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  19:                  tokenizer.ggml.token_type arr[i32,256000]  = [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...
llama_model_loader: - kv  20:                tokenizer.ggml.bos_token_id u32              = 2
llama_model_loader: - kv  21:                tokenizer.ggml.eos_token_id u32              = 1
llama_model_loader: - kv  22:            tokenizer.ggml.unknown_token_id u32              = 3
llama_model_loader: - kv  23:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  24:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  25:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  26:                    tokenizer.chat_template str              = {{ bos_token }}{% if messages[0]['rol...
llama_model_loader: - kv  27:            tokenizer.ggml.add_space_prefix bool             = false
llama_model_loader: - kv  28:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:  169 tensors
llama_model_loader: - type q4_0:  294 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_vocab: special tokens cache size = 108
time=2024-09-20T14:35:02.305+02:00 level=INFO source=server.go:629 msg="waiting for server to become available" status="llm server loading model"
llm_load_vocab: token to piece cache size = 1.6014 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = gemma2
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 256000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: vocab_only       = 0
llm_load_print_meta: n_ctx_train      = 8192
llm_load_print_meta: n_embd           = 3584
llm_load_print_meta: n_layer          = 42
llm_load_print_meta: n_head           = 16
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_rot            = 256
llm_load_print_meta: n_swa            = 4096
llm_load_print_meta: n_embd_head_k    = 256
llm_load_print_meta: n_embd_head_v    = 256
llm_load_print_meta: n_gqa            = 2
llm_load_print_meta: n_embd_k_gqa     = 2048
llm_load_print_meta: n_embd_v_gqa     = 2048
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-06
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 2
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_ctx_orig_yarn  = 8192
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: ssm_dt_b_c_rms   = 0
llm_load_print_meta: model type       = 9B
llm_load_print_meta: model ftype      = Q4_0
llm_load_print_meta: model params     = 9.24 B
llm_load_print_meta: model size       = 5.06 GiB (4.71 BPW)
llm_load_print_meta: general.name     = gemma-2-9b-it
llm_load_print_meta: BOS token        = 2 '<bos>'
llm_load_print_meta: EOS token        = 1 '<eos>'
llm_load_print_meta: UNK token        = 3 '<unk>'
llm_load_print_meta: PAD token        = 0 '<pad>'
llm_load_print_meta: LF token         = 227 '<0x0A>'
llm_load_print_meta: EOT token        = 107 '<end_of_turn>'
llm_load_print_meta: max token length = 93
ggml_sycl_init: GGML_SYCL_FORCE_MMQ:   no
ggml_sycl_init: SYCL_USE_XMX: yes
ggml_sycl_init: found 1 SYCL devices:
get_memory_info: [warning] ext_intel_free_memory is not supported (export/set ZES_ENABLE_SYSMAN=1 to support), use total memory as free memory
llm_load_tensors: ggml ctx size =    0.41 MiB
llm_load_tensors: offloading 42 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 43/43 layers to GPU
llm_load_tensors:      SYCL0 buffer size =  5185.21 MiB
llm_load_tensors:  SYCL_Host buffer size =   717.77 MiB
llama_new_context_with_model: n_ctx      = 8192
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
[SYCL] call ggml_check_sycl
ggml_check_sycl: GGML_SYCL_DEBUG: 0
ggml_check_sycl: GGML_SYCL_F16: no
found 1 SYCL devices:
|  |                   |                                       |       |Max    |        |Max  |Global |                     |
|  |                   |                                       |       |compute|Max work|sub  |mem    |                     |
|ID|        Device Type|                                   Name|Version|units  |group   |group|size   |       Driver version|
|--|-------------------|---------------------------------------|-------|-------|--------|-----|-------|---------------------|
| 0| [level_zero:gpu:0]|                     Intel Arc Graphics|    1.3|    112|    1024|   32| 62228M|            1.3.29735|
llama_kv_cache_init:      SYCL0 KV buffer size =  2688.00 MiB
llama_new_context_with_model: KV self size  = 2688.00 MiB, K (f16): 1344.00 MiB, V (f16): 1344.00 MiB
llama_new_context_with_model:  SYCL_Host  output buffer size =     3.96 MiB
[1726835715] warming up the model with an empty run
llama_new_context_with_model:      SYCL0 compute buffer size =   507.00 MiB
llama_new_context_with_model:  SYCL_Host compute buffer size =    39.01 MiB
llama_new_context_with_model: graph nodes  = 1732
llama_new_context_with_model: graph splits = 2
INFO [main] model loaded | tid="131835344998976" timestamp=1726835716
time=2024-09-20T14:35:17.119+02:00 level=INFO source=server.go:634 msg="llama runner started in 15.07 seconds"
[GIN] 2024/09/20 - 14:35:17 | 200 | 15.126045979s |       127.0.0.1 | POST     "/api/chat"
INFO [print_timings] prompt eval time     =    1379.57 ms /    15 tokens (   91.97 ms per token,    10.87 tokens per second) | n_prompt_tokens_processed=15 n_tokens_second=10.872984692287284 slot_id=0 t_prompt_processing=1379.566 t_token=91.97106666666667 task_id=3 tid="131835344998976" timestamp=1726835724
INFO [print_timings] generation eval time =       0.01 ms /     1 runs   (    0.01 ms per token, 83333.33 tokens per second) | n_decoded=1 n_tokens_second=83333.33333333333 slot_id=0 t_token=0.012 t_token_generation=0.012 task_id=3 tid="131835344998976" timestamp=1726835724
INFO [print_timings]           total time =    1379.58 ms | slot_id=0 t_prompt_processing=1379.566 t_token_generation=0.012 t_total=1379.578 task_id=3 tid="131835344998976" timestamp=1726835724
[GIN] 2024/09/20 - 14:35:24 | 200 |  1.438643598s |       127.0.0.1 | POST     "/api/chat"
INFO [print_timings] prompt eval time     =    1395.62 ms /    15 tokens (   93.04 ms per token,    10.75 tokens per second) | n_prompt_tokens_processed=15 n_tokens_second=10.747895920242014 slot_id=0 t_prompt_processing=1395.622 t_token=93.04146666666666 task_id=11 tid="131835344998976" timestamp=1726835736
INFO [print_timings] generation eval time =       0.01 ms /     1 runs   (    0.01 ms per token, 111111.11 tokens per second) | n_decoded=1 n_tokens_second=111111.1111111111 slot_id=0 t_token=0.009000000000000001 t_token_generation=0.009000000000000001 task_id=11 tid="131835344998976" timestamp=1726835736
INFO [print_timings]           total time =    1395.63 ms | slot_id=0 t_prompt_processing=1395.622 t_token_generation=0.009000000000000001 t_total=1395.631 task_id=11 tid="131835344998976" timestamp=1726835736
[GIN] 2024/09/20 - 14:35:36 | 200 |  1.540893033s |       127.0.0.1 | POST     "/api/chat"
```

```
./ollama run gemma2:9b
>>> Why is the sky blue?


>>> Why is the sky blue?
```

**Comment by dhiltgen** [comment] 2024-09-24 18:15
@tristan-k Intel GPU support isn't officially part of Ollama yet - we're tracking that via #1590 

Something seems to be going wrong with the Intel GPU support, so you should probably follow up with the maintainers of [IPEX-LLM](https://github.com/intel-analytics/ipex-llm)

**Comment by havardthom** [comment] 2024-10-28 16:44
For anyone interested, I've added an Ollama LXC script to tteck's Proxmox Helper-Scripts. The script installs intel-basekit and builds Ollama from source and supports Intel iGPU passthrough (though it has a very long install time). It can be run like any other proxmox helper script: bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/ollama.sh)"

A script for Open WebUI LXC with optional Ollama install is also available: https://tteck.github.io/Proxmox/#open-webui-lxc

**Comment by tristan-k** [comment] 2024-10-29 20:37
@havardthom I just installed your Ollama LXC on my Metero Lake Intel Core Ultra 5 125H but despite your efforts to install oneapi runtime Ollama still uses the CPU (AVX2).

Note: The systemd service also runs on CPU. For the debug output I run Ollama manually from the install directory in the LXC at `/opt/ollama/` and exported the enviroment variables.

```
export OLLAMA_INTEL_GPU=true 
export OLLAMA_HOST=0.0.0.0 
export OLLAMA_NUM_GPU=999 
export SYCL_CACHE_PERSISTENT=1
export ZES_ENABLE_SYSMAN=1

$ cd /opt/ollama/
$ ./ollama serve
2024/10/29 21:23:55 routes.go:1189: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://0.0.0.0:11434 OLLAMA_INTEL_GPU:true OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/root/.ollama/models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://*] OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES: http_proxy: https_proxy: no_proxy:]"
time=2024-10-29T21:23:55.909+01:00 level=INFO source=images.go:754 msg="total blobs: 5"
time=2024-10-29T21:23:55.909+01:00 level=INFO source=images.go:761 msg="total unused blobs removed: 0"
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] POST   /api/pull                 --> github.com/ollama/ollama/server.(*Server).PullHandler-fm (5 handlers)
[GIN-debug] POST   /api/generate             --> github.com/ollama/ollama/server.(*Server).GenerateHandler-fm (5 handlers)
[GIN-debug] POST   /api/chat                 --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (5 handlers)
[GIN-debug] POST   /api/embed                --> github.com/ollama/ollama/server.(*Server).EmbedHandler-fm (5 handlers)
[GIN-debug] POST   /api/embeddings           --> github.com/ollama/ollama/server.(*Server).EmbeddingsHandler-fm (5 handlers)
[GIN-debug] POST   /api/create               --> github.com/ollama/ollama/server.(*Server).CreateHandler-fm (5 handlers)
[GIN-debug] POST   /api/push                 --> github.com/ollama/ollama/server.(*Server).PushHandler-fm (5 handlers)
[GIN-debug] POST   /api/copy                 --> github.com/ollama/ollama/server.(*Server).CopyHandler-fm (5 handlers)
[GIN-debug] DELETE /api/delete               --> github.com/ollama/ollama/server.(*Server).DeleteHandler-fm (5 handlers)
[GIN-debug] POST   /api/show                 --> github.com/ollama/ollama/server.(*Server).ShowHandler-fm (5 handlers)
[GIN-debug] POST   /api/blobs/:digest        --> github.com/ollama/ollama/server.(*Server).CreateBlobHandler-fm (5 handlers)
[GIN-debug] HEAD   /api/blobs/:digest        --> github.com/ollama/ollama/server.(*Server).HeadBlobHandler-fm (5 hand
[GIN-debug] DELETE /api/delete               --> github.com/ollama/ollama/server.(*Server).DeleteHandler-fm (5 handle
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_dt_b_c_rms   = 0
llm_load_print_meta: model type       = 2B
llm_load_print_meta: model ftype      = Q4_0
llm_load_print_meta: model size       = 1.51 GiB (4.97 BPW) 
llm_load_print_meta: general.name     = Gemma 2.0 2b It Transformers
llm_load_print_meta: BOS token        = 2 '<bos>'
llm_load_print_meta: EOS token        = 1 '<eos>'
llm_load_print_meta: UNK token        = 3 '<unk>'
llm_load_print_meta: PAD token        = 0 '<pad>'
llm_load_print_meta: LF token         = 227 '<0x0A>'
llm_load_print_meta: EOT token        = 107 '<end_of_turn>'
llm_load_print_meta: EOG token        = 1 '<eos>'
llm_load_print_meta: EOG token        = 107 '<end_of_turn>'
llm_load_print_meta: max token length = 48
llm_load_tensors: ggml ctx size =    0.13 MiB
llm_load_tensors:        CPU buffer size =  2009.68 MiB
time=2024-10-29T21:25:31.759+01:00 level=INFO source=server.go:601 msg="waiting for server to become available" status="llm server loading model"
llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:        CPU KV buffer size =   208.00 MiB
llama_new_context_with_model: KV self size  =  208.00 MiB, K (f16):  104.00 MiB, V (f16):  104.00 MiB
llama_new_context_with_model:        CPU  output buffer size =     0.99 MiB
llama_new_context_with_model:        CPU compute buffer size =   509.00 MiB
llama_new_context_with_model: graph nodes  = 1050
llama_new_context_with_model: graph splits = 1
INFO [main] model loaded | tid="133087149890496" timestamp=1730233533
time=2024-10-29T21:25:33.765+01:00 level=INFO source=server.go:606 msg="llama runner started in 2.26 seconds"
[GIN] 2024/10/29 - 21:25:33 | 200 |  2.389025476s |       127.0.0.1 | POST     "/api/generate"
[GIN] 2024/10/29 - 21:26:57 | 200 | 38.965294962s |       127.0.0.1 | POST     "/api/chat"
```

```
$ cat  /etc/pve/lxc/104.conf
# Ollama LXC
arch: amd64
cores: 4
dev0: /dev/dri/card1,gid=44
dev1: /dev/dri/renderD128,gid=104
features: keyctl=1,nesting=1
hostname: ollama
memory: 4096
net0: name=eth0,bridge=vmbr0,hwaddr=REDACTED,ip=dhcp,type=veth
onboot: 1
ostype: ubuntu
rootfs: local-lvm:vm-104-disk-1,size=24G
swap: 512
tags: proxmox-helper-scripts
unprivileged: 1
```

**Comment by tristan-k** [comment] 2024-10-29 20:55
```
$ source /opt/intel/oneapi/setvars.shsh

:: initializing oneAPI environment ...
   bash: BASH_VERSION = 5.1.16(1)-release
   args: Using "$@" for setvars.sh arguments:
:: advisor -- latest
:: ccl -- latest
:: compiler -- latest
:: dal -- latest
:: debugger -- latest
:: dev-utilities -- latest
:: dnnl -- latest
:: dpcpp-ct -- latest
:: dpl -- latest
:: ipp -- latest
:: ippcp -- latest
:: mkl -- latest
:: mpi -- latest
:: tbb -- latest
:: umf -- latest
:: vtune -- latest
:: oneAPI environment initialized ::
```

```
$ sycl-ls
[opencl:acc:0] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device OpenCL 1.2  [2024.17.5.0.08_160000.xmain-hotfix]
[opencl:cpu:1] Intel(R) OpenCL, Intel(R) Core(TM) Ultra 5 125H OpenCL 3.0 (Build 0) [2024.17.5.0.08_160000.xmain-hotfix]
[opencl:gpu:2] Intel(R) OpenCL Graphics, Intel(R) Arc(TM) Graphics OpenCL 3.0 NEO  [24.35.30872]
[ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Arc(TM) Graphics 1.3 [1.3.29735]
```

I already tried if the issue was related to `unprivileged: 1` but changing to `unprivileged: 0` doesnt make a difference.

**Comment by havardthom** [comment] 2024-10-29 21:00
Looking again at the first logs you posted it looks like the GPU is being used: 
```
time=2024-10-29T21:48:08.311+01:00 level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[cpu cpu_avx cpu_avx2 oneapi]"
time=2024-10-29T21:48:08.311+01:00 level=INFO source=gpu.go:221 msg="looking for compatible GPUs"
time=2024-10-29T21:48:08.369+01:00 level=INFO source=types.go:123 msg="inference compute" id=0 library=oneapi variant="" compute="" driver=0.0 name="Intel(R) Arc(TM) Graphics" total="0 B" available="0 B"
```

**Comment by tristan-k** [comment] 2024-10-29 21:01
I thought so as well but `intel_gpu_top` on the proxmox host doesnt show any load and `htop` clearly shows a load on the CPU cores at `/tmp/ollama264177643/runners/cpu_avx2/ollama_llama_server`.

**Comment by havardthom** [comment] 2024-10-29 21:14
Same situation for me, I guess iGPU just isn't supported in Ollama yet then :/ tracking https://github.com/ollama/ollama/issues/3113

**Comment by tristan-k** [comment] 2024-10-29 21:19
Maybe have a lookt at [this](https://github.com/celesrenata/nixos-k3s-configs/blob/main/kubevirt/ipex-1x/bootstrap-ipex-fleet.sh). @celesrenata seems to be using Ubuntu 24.04.

**Comment by havardthom** [comment] 2024-10-29 22:09
GPU is used if I build and run llama backend directly (https://github.com/ggerganov/llama.cpp/blob/master/docs/backend/SYCL.md#iii-run-the-inference), so the limitation seems to be with Ollama

![image](https://github.com/user-attachments/assets/703398eb-aeb0-4963-b983-33a6675e6c4e)

**Comment by tristan-k** [comment] 2025-02-15 17:34
@havardthom [This](https://github.com/mattcurf/ollama-intel-gpu) docker container seems to run really well on intel gpus. Maybe its possible to add it to the [ollama](https://github.com/community-scripts/ProxmoxVE/blob/main/ct/ollama.sh) community-script?
