### ISSUE TITLE
Get supported models with API

### ISSUE THREAD

**Issue by angelozerr** [ollama/ollama#6593] opened 2024-09-02 15:36 UTC
The API provides the capability to get the list of local models, but I have not found an API to get the supported models that we can see with HTML page at https://ollama.com/library?q=l&sort=featured

It would be nice if API could provide a list of supported models.

**Comment by pdevine** [comment] 2024-09-02 22:02
Closing as a dupe of #1070

**Closed by pdevine** 2024-09-02 22:02 UTC
Labels: feature request
