### ISSUE TITLE
Support AMD RX580 graphics card

### ISSUE THREAD

**Issue by Tamila-2017** [ollama/ollama#6803] opened 2024-09-14 15:28 UTC
Hello,

Does your project support AMD RX580 or RX480 graphics card?

**Comment by olumolu** [comment] 2024-09-14 18:13
Yes it does you need rcom driver.

**Comment by Tamila-2017** [comment] 2024-09-14 19:14
O yes, I understand that. But where can I get such a ROCm driver that 
confidently supports the old RX580?
Unfortunately, I am not aware of such an amazing driver.
If you know about this, please let me know!



aritra saha писал(а) 2024-09-14 18:14:

**Comment by a-germain** [comment] 2024-09-20 20:48
Dupe of #2453

**Closed** 2024-09-21 00:44 UTC
Labels: feature request, amd, gpu
