### ISSUE TITLE
API for models on `ollama.com`

### ISSUE THREAD

**Issue by danemadsen** [ollama/ollama#1070] opened 2023-11-10 04:23 UTC
Hi I was wondering if you could add a way to either search for, or get a list of models available to pull off ollama.ai.

Currently the https://ollama.ai/library endpoint serves model information as HTML, it would be better if it was served as JSON so it could be better integrated into software

**Comment by kris-hansen** [comment] 2024-02-22 18:43
I have a [PR](https://github.com/ollama/ollama/pull/1732) up for this which was intended as exploratory/for discussion. After sending up the PR, I read the discussion on Discord related to this topic (wrong order, I know). It seems like the primary concern with listing the libraries from the CLI is that when the number of remote models grows it will become hard to handle. I can see some approaches to address this:
- do nothing: similar to listing the files in a directory with a lot of files, let the user pipe to more or other CLI tools to deal with the volume of information
- add pagination: it's a bit weird to have pagination for a CLI but certainly implementable; could be optional with a default enabled or optional with a default disabled. 

I have been using this feature (--list-remote) on my fork and have found it quite useful when exploring/pulling new models, but obviously not a critical feature.

Ideally, having a JSON file server side with the same contents as `https://ollama.ai/library` would make this easier/more reliable - something like `https://ollama.ai/library.json` would be helpful. 

Happy to discuss, refactor, update or close the issue - LMK

**Comment by adriens** [comment] 2024-05-11 20:35
You can get that kind of resources, see [💰 Unleash ollama potential w. data and LLM capabilities ](https://dev.to/adriens/unleash-ollama-potential-w-data-and-llm-capabilities-3ghl)

You can get the fresh data in [🦙 ollama models library Kaggle dataset](https://www.kaggle.com/datasets/adriensales/ollama-models)

**Comment by PhilKes** [comment] 2024-05-29 14:32
:+1: 
Any progress on this @jmorganca ?
I think for most people a REST API would be the most benefitial, with pagination.
I guess since many models have a lot of tags, maybe you could separate that into another endpoint,
having a `GET ollama.com/api/models?filter=xyz&page=1&pageSize=10` and a `GET ollama.com/api/models/{modelName}/tags` (which returns the same infos as requesting the local `/api/tags`)

**Comment by angelozerr** [comment] 2024-09-17 12:46
We are interested too with this feature in our Quarkus Toolings https://marketplace.visualstudio.com/items?itemName=redhat.vscode-quarkus,https://github.com/redhat-developer/intellij-quarkus to show supported ollama model in completion.

Today we display only Ollama model which are installed:

![image](https://github.com/user-attachments/assets/ecf44319-11d1-41d5-ac73-7aeaab4c4e4e)

**Comment by adriens** [comment] 2024-09-19 21:51
@angelozerr , you may get some suitable code from the following Kaggle notebook : [🦙 ollama models duckdb database](https://www.kaggle.com/code/adriensales/ollama-models-duckdb-database)

Hope this helps :crossed_fingers:

**Comment by angelozerr** [comment] 2024-09-20 04:30
Thanks @adriens . I have seen quickly your link and you convert html code from the http ollama library to JSON.

I would prefer getting directly JSON.

**Comment by adriens** [comment] 2024-09-20 05:03
Sure sure

**Comment by angelozerr** [comment] 2024-09-20 07:01
> Sure sure

Anyway thatks for your suggestion. I would like just to avoid adding a new Java library like JSoup in our tooling just for ollama.

**Comment by webfarmer** [comment] 2024-10-02 10:08
[https://github.com/webfarmer/ollama-get-models](https://github.com/webfarmer/ollama-get-models)

**Comment by oppenheimer-** [comment] 2024-10-18 06:23
> just discovered this [repo](https://github.com/akazwz/ollama-models)
> 
> name, description and tags are available as JSON here: https://ollama-models.zwz.workers.dev/ API seems to be working and up to date per today; models are sorted by "featured"

https://github.com/ollama/ollama/issues/1473#issuecomment-2421521786

**Comment by jakobhuss** [comment] 2024-10-25 11:42
[ollama_models.py](https://gist.github.com/jakobhuss/54c27c28bb860fb7e1069bde85122ad2)

**Comment by dhiltgen** [comment] 2024-11-21 17:25
Lets track this under #286

**Closed by dhiltgen** 2024-11-21 17:25 UTC
Labels: feature request, ollama.com
