### ISSUE TITLE
ollama pull modelName Error

### ISSUE THREAD

**Issue by ZPLSSSTD** [ollama/ollama#3212] opened 2024-03-18 03:24 UTC
### What is the issue?

I once accidentally installed Ollama: 7b successfully.Afterwards, I executed the command olama pull llama2. But there was an error, and the error message is as follows
`
pulling manifest
Error: pull model manifest: Get "https://ollama.com/token?nonce=qKzQl7GvJl7HVA-mW_-3Ow&scope=repository%!A(MISSING)library%!F(MISSING)llama2%!A(MISSING)pull&service=ollama.com&ts=1710731810": read tcp 192.168.4.190:13291->34.120.132.20:443: wsarecv: An existing connection was forcibly closed by the remote host.
`

I searched for the issue, but the answer inside cannot solve my problem. I have tried restarting my computer or changing my WiFi, but it still doesn't work.

### What did you expect to see?

I hope to be able to install the model normally

### OS

Windows

### Architecture

amd64

### Ollama version

0.1.29

### GPU

Nvidia

### GPU info

Nvidia Geforce RTX 2060

### CPU

AMD

**Comment by BruceMacD** [comment] 2024-03-21 10:11
Hi @ZPLSSSTD, sorry you're hitting this issue. This looks similar to #2448, you may be having this issue due to a proxy or firewall.

**Comment by mxyng** [comment] 2024-03-28 20:52
duplicate of #3112

**Closed by mxyng** 2024-03-28 20:52 UTC
Labels: networking
