### ISSUE TITLE
Concurrency

### ISSUE THREAD

**Issue by samyfodil** [ollama/ollama#3170] opened 2024-03-15 18:17 UTC
### What are you trying to do?

Right now Ollama is limited to one request and one model. Even desktop GPUs can handle easily load more than one model. While you can still run multiple instances of ollama, fixing the issue at the core is better. 

### How should we solve this?

The Ext Server was built on the server example on llama.cpp, which can only load one model. While it is the case for the example server, it's not the case for llama.cpp. Instead of building on top of the example server, using the same code but adding to it the ability to load multiple models. Maybe while doing that getting rid of the json encoding/decoding between the ext server and the example server used on the backend.

### What is the impact of not solving this?

Huge impact on performance as requests are lined up especially if they use different models.
It's also hard to use Ollama in a cloud setup.

### Anything else?

I discovered the issue while building a [tau](https://github.com/taubyte/tau) plugin for exposing ollama through wasm here https://github.com/samyfodil/ollama (see `tau` folder)
![](https://github.com/ollama/ollama/assets/76626119/be0fee96-e9b6-4996-aba5-0c7b76ea0589)

**Comment by mxyng** [comment] 2024-03-18 08:18
Duplicate of #358

**Comment by pdevine** [comment] 2024-03-18 08:18
Thanks for the issue @samyfodil , this is definitely on the radar.

**Closed by mxyng** 2024-03-18 08:18 UTC
Labels: needs-triage
