### ISSUE TITLE
ollama doesn't use system RAM

### ISSUE THREAD

**Issue by DrGood01** [ollama/ollama#1727] opened 2023-12-27 08:43 UTC
I'm running Ollama on a ubuntu 22 linux laptop with 32 G of RAM and a NVIDIA gtx 1650.  Ollama loads the models exclusively in the graphic card RAM, and doesn't use any of the system RAM at all. Very frustrating, as it exists with "Error: llama runner exited, you may not have enough available memory to run this model" as soon as I try to chat...

**Comment by iplayfast** [comment] 2023-12-27 09:13
I ran into this as well, The way to get around it is to tell ollama you have no gpu. Then it will load into memory.
my mixtralcpu model is as follows.
```
FROM mixtral:latest
TEMPLATE """ [INST] {{ .System }} {{ .Prompt }} [/INST]"""
PARAMETER num_gpu 0
PARAMETER num_ctx 32768
PARAMETER stop "</s>"
PARAMETER stop "[INST]"
PARAMETER stop "[/INST]"


PARAMETER temperature .9
PARAMETER num_ctx 32768
system "You are an intellegent AI that is always helpful"
```

modify it for the model you are trying, and create a new model
llama create mixtralcpu

**Comment by PollastreGH** [comment] 2023-12-27 23:20
Can confirm that I'm running into this issue as-well, EndeavourOS Linux desktop with 64GB of RAM and an RTX-3080.

**Comment by DrGood01** [comment] 2023-12-30 09:57
iplayfast, thank you so much! I'm now running mixtralcpu on my laptop!

**Comment by easp** [comment] 2024-01-02 21:17
> But it also fills the swap space. Is there a way to tell it not to fill swap?

If you don't have enough RAM, your system will use swap. The solution is to either get more RAM and/or reduce the RAM demands of your computer by closing files, quitting apps, using smaller models.

**Comment by DrGood01** [comment] 2024-01-03 05:35
thanks easp. I've got 32G or RAM, and while working, my mixtralcpu uses only 7 or 8 G of it, while rapidly filling swap. Any idea?

**Comment by Slapbox** [comment] 2024-01-04 04:38
It seems like for me the ollama never uses system memory at all, which doesn't make any sense to me, but it is reading from the disk at 140MB/s nonstop while it generates though and take up to 15 minutes for a brief response, so maybe it really isn't using system memory.

No GPU involvement.

Specifically I'm on via WSL1 (which I know is not officially supported, but is the only option I have.)

I hope there might be a Windows version soon! LLMs are just too heavy to boot up in traditional VMs.

**Comment by gbrohammer** [comment] 2024-01-09 13:54
Same problem, Ubuntu 64GB RAM with RTX 3050 TI (4G VRAM) fails to load the LLAMA2 model

**Comment by bsu3338** [comment] 2024-01-19 23:46
I am having the same problem.  I am using the docker image.  Solution from @iplayfast did not work for me. I tried q5_k_m models of mixtral, mistral, and llama2.

**Comment by bsu3338** [comment] 2024-01-28 13:22
My problem was caused because the Hyper-V VM was running with Dynamic Memory. After removing that option, everything worked as designed.

**Comment by pdevine** [comment] 2024-03-11 22:25
This should be working better in that ollama should offload a portion to the GPU, and a portion to the CPU. Can you test again with ollama version 0.1.28?

There are also a change coming in 0.1.29 where you will be able to set the amount of VRAM that you want to use which should force it to use the system memory instead.

**Comment by alfi4000** [comment] 2024-03-17 07:50
Hi i have the issue that it only uses my graphics card gram not also the system ram I use a server that has 256gb ram and a Nvidia Tesla p40 with 24576Mib ram but when I load a 24.6gb llm just nothing happens! How can I solve that or does it then just uses ram and cpu if the load doesnt match the gpu? Because I just waited a minute and then I just closed the chat!

**Comment by Nantris** [comment] 2024-03-19 19:10
It works here on Windows now that WSL is no longer involved.

**Comment by mzpqnxow** [comment] 2024-04-11 13:05
> > But it also fills the swap space. Is there a way to tell it not to fill swap?
> 
> If you don't have enough RAM, your system will use swap. The solution is to either get more RAM and/or reduce the RAM demands of your computer by closing files, quitting apps, using smaller models.

Important note on this, specifically for most Linux distributions. Arguably the most important thing for Linux desktop users with more than 16GB RAM

Most popular Linux distributions (all Debian-based distros, at least) advise the kernel to use swap for an unreasonably large portion of memory allocations, **even when there’s still plenty of physical RAM available**

This is a really nasty default setting that in my opinion should be adjusted or determined dynamically or by asking the user at installation time. For most workloads, a system with 32GB RAM should never proactively swap

You can tell the kernel not to swap so aggressively by setting the swappiness value lower. It’s a scale of 1-100, Debian sets it to 40 or 60 by default. I reduce it to 1 (effectively, “hardly ever swap”)

    $ sudo sysctl -w vm.swappiness=1

as usual, [Arch docs](https://wiki.archlinux.org/title/Swap#Swappiness) are the best on the subject

**Comment by mzpqnxow** [comment] 2024-04-11 13:22
> thanks easp. I've got 32G or RAM, and while working, my mixtralcpu uses only 7 or 8 G of it, while rapidly filling swap. Any idea?

Check swappiness (see my previous comment, should have replied to your comment sorry)

**Comment by ConfoundedHermit** [comment] 2024-04-12 01:56
I have this same issue on Windows native v0.1.31 with any model. Loads models into GPU vRAM, but larger models obviously run like molasses when it caps the vRAM. System RAM is not touched by the model at all and there is 100+ GB free.

**Comment by dhiltgen** [comment] 2024-04-12 22:40
I've lost track of what this issue is tracking.  It sounds like the initial problem was we miscalculated the number of layers of the model to load on the GPU, and ran out of VRAM and crashed.  In general, Ollama is going to try to use the GPU and VRAM before system memory.  We've been improving our prediction algorithms to get closer to fully utilizing the GPU's VRAM, without exceeding it, so I'd definitely encourage you to try the latest release.

**Comment by Nantris** [comment] 2024-04-12 22:58
I am pretty confident that when I tested it was properly using system RAM, as I haven't nearly enough VRAM to store an entire model and yet response times were pretty reasonable (a few seconds, as opposed to previously a few minutes.)

Thanks for the great work.

**Comment by Louden7** [comment] 2024-04-14 18:17
I still think this is an issue with linux, or more specifically Ubuntu. 

Troubleshooting steps taken:
1. updated Ollama
2. Removed all other LLMs from the local server
3. Restarted service
4. Set the default swappiness to 5 (from 60) as suggested above in this thread.

I am running Ollama 0.1.31 locally on a Ubuntu 22.04.4 LTS with 16GB RAM and 12GB RTX 3080ti and old Ryzen 1800x. Any LLM smaller then 12GB runs flawlessly since its all on the GPU's memory. However when I tried testing with the 19GB codellama:34b It loads all ~10GB on the GPU but then nothing on the available 16GB of RAM resulting in extremely slow response times. 

Screenshots below:
1. TMUX split screen of htop (top half) and nvtop (bottom half). Note: Average GPU% was ~7%
<img width="1440" alt="htop-nvtop" src="https://github.com/ollama/ollama/assets/22922778/5c39d777-431b-4ac8-9e78-f2876f4b09a4">

2. OpenwebUI with details on prompt response. 
<img width="1316" alt="OpenwebUI" src="https://github.com/ollama/ollama/assets/22922778/c41d044c-5b4a-442f-9c3d-bd8800e53629">

**Comment by joshwkearney** [comment] 2024-04-24 23:08
I'll second this, I'm having the same problem running on Zorin 17.1 (based on Ubuntu). Hardware is a Ryzen 3800x, 1080ti 12GB, and 32GB of ram. If I run models much larger than 8b it can't all fit into vram but it doesn't use my system memory at all. I tried the troubleshooting above but no luck

**Comment by siakc** [comment] 2024-04-30 16:14
Is [this](https://github.com/ollama/ollama/issues/3837) related?

**Comment by Louden7** [comment] 2024-04-30 16:35
Yes both of these issues seem related. Trying to run a larger model that does not all fit on GPU VRAM _should_ store the remaining in system RAM but by the images I shared above does not.

Ideally (and I may be wrong) in this case it would fill up GPU VRAM, then system RAM and share the compute load on both GPU and CPU favoring GPU for performance.

**Comment by Nantris** [comment] 2024-04-30 20:18
Is it fair to think this only affects Linux at this point? I haven't re-tested Windows as it's kind of a pain and I haven't much use for it, but it worked for me last time I tried.

**Comment by easp** [comment] 2024-05-01 04:46
@Louden7 

> Ideally (and I may be wrong) in this case it would fill up GPU VRAM, then system RAM and share the compute load on both GPU and CPU favoring GPU for performance.

The portion in VRAM is computed on the GPU, the portion in system RAM is computed by the CPU. The bottleneck is memory bandwidth, not compute. Transferring data from system RAM to the GPU is slower than transferring it to the CPU.

@Louden7, model weights are memory mapped. They are accounted for in buffer/file cache, which is generally counted as available memory. Performance with 19GB of model weights is bad because the portion that doesn't fit in VRAM is processed by the CPU, which is much slower than the GPU. Your GPU utilization is low because it's spending most of its time waiting for the CPU.

**Comment by Louden7** [comment] 2024-05-02 20:06
@easp 
That makes sense. Thank you for the detailed explanation! 

I am still curious about htop not showing the correct system RAM utilization.

**Comment by siakc** [comment] 2024-05-03 12:42
If you like I can run some more commands for you to see what is going on.

**Comment by pdevine** [comment] 2024-05-16 23:11
I'm going to go ahead and close this. Models should work w/ hybrid CPU/GPU. If you want to see what portion is offloaded you can now use the new `ollama ps` command.

**Closed by pdevine** 2024-05-16 23:11 UTC
Labels: nvidia

**Comment by kwikiel** [comment] 2024-09-08 01:37
The issue seems to be that some people would expect Ollama to load models to RAM first, then keep them there as long as possible and when there is some requests -> load from RAM to VRAM 

I have 128 GB RAM and 72 GB VRAM ( 3x3090 ) so I can keep the models in RAM instead of loading them from disk for each time it's dropped from the GPU. 

This seems kind of non-standard use case and maybe this can be circumvented by using RAM-disk for storing models so it can be fixed without changing anything in the Ollama code.

**Comment by summersonnn** [comment] 2024-10-21 21:10
Hey. 
I have 12 GB VRAM and 64GB RAM.
When I run a 53 GB model, I observe that my VRAM is almost full but my RAM and swap do not change. So, where is the model loaded to?
qwen2.5:72b    424bad2cc13f    53 GB    78%/22% CPU/GPU

It feels like my model is partially loaded onto GPU and processed by CPU (otherwise why would I see spike in cpu usage?) My GPU usage seldomly exceeds 30% and probably around 10% in average. What's going on?

**Comment by easp** [comment] 2024-10-21 21:23
@summersonnn https://github.com/ollama/ollama/issues/1727#issuecomment-2087971975
