### ISSUE TITLE
Suno-AI Bark 

### ISSUE THREAD

**Issue by ncamacho97** [ollama/ollama#7413] opened 2024-10-30 02:29 UTC
I was hoping you guys can please add this model 

https://github.com/suno-ai/bark

Bark is a transformer-based text-to-audio model created by [Suno](https://suno.ai/). Bark can generate highly realistic, multilingual speech as well as other audio - including music, background noise and simple sound effects. The model can also produce nonverbal communications like laughing, sighing and crying. To support the research community, we are providing access to pretrained model checkpoints, which are ready for inference and available for commercial use.

**Comment by jmorganca** [comment] 2024-11-04 17:43
Hi @ncamacho97 thanks!

Duplicate of https://github.com/ollama/ollama/issues/1234

**Closed by jmorganca** 2024-11-04 17:43 UTC
Labels: feature request
