### ISSUE TITLE
Always output GGGGGGG when encountering problems that will not occur... .

### ISSUE THREAD

**Issue by enryteam** [ollama/ollama#5814] opened 2024-07-20 15:54 UTC
### What is the issue?

https://ollama.com/library/glm4

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.2.7

**Comment by rick-github** [comment] 2024-07-20 15:57
dupe https://github.com/ollama/ollama/issues/5668

**Comment by kindzhon** [comment] 2024-07-23 09:49
me too

**Comment by AdamWangT** [comment] 2024-07-25 06:50
me too too

**Comment by enryteam** [comment] 2024-07-26 05:38
只要出现“ GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG” 接着问任何问题 都是“ GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG”

**Comment by enryteam** [comment] 2024-08-19 10:10
+1

**Comment by jiaolongxue** [comment] 2024-08-21 13:57
+1

**Comment by pdevine** [comment] 2024-09-12 22:16
Make sure you're on the latest version of Ollama and you `ollama pull glm4` to get the latest version. I just tested it w/ both linux and mac and it's working correctly. I'll go ahead and close this, but we can reopen if people are still seeing problems.

**Closed by pdevine** 2024-09-12 22:16 UTC
Labels: bug

**Comment by GwynnePrints** [comment] 2026-05-01 12:38
Having this issue years later. Clearly not fixed unfortunately. Very disappointing to not be able to use the boards as intended.
