### ISSUE TITLE
Unable to run Falcon Models

### ISSUE THREAD

**Issue by mebinjoy77** [ollama/ollama#3236] opened 2024-03-19 07:18 UTC
### What is the issue?

Unable to run falcon models through ollama. Running falcon models crashes ollama service.

Here is the log :

![image](https://github.com/ollama/ollama/assets/62318229/2125b14f-64e4-4c40-91fd-ae4c92f4d866)

### What did you expect to see?

ollama  working fine with falcon.

### Steps to reproduce

Follow the commands :
ollama run falcon

### OS

Linux

### Architecture

amd64

### Ollama version

0.1.29

### GPU

Nvidia

### GPU info

NVIDIA A10G
Driver Version: 470.199.02   CUDA Version: 11.4

### CPU

Intel

**Comment by pdevine** [comment] 2024-03-19 13:25
This is a dupe of #2024

**Closed by pdevine** 2024-03-19 13:25 UTC
Labels: bug, needs-triage
