### ISSUE TITLE
模型mattw/loganalyzer，按照example/python_loganalysis中的readme操作，但是http://localhost:11434/api/generate一直404

### ISSUE THREAD

**Issue by syuan-Boom** [ollama/ollama#6745] opened 2024-09-11 07:55 UTC
### What is the issue?

模型mattw/loganalyzer，按照example/python_loganalysis中的readme，全程操作，但是http://localhost:11434/api/generate一直404

### OS

macOS

### Ollama version

0.3.6

**Comment by syuan-Boom** [comment] 2024-09-11 09:48
我怀疑是不支持mattw/loganalyzer这个模型了。。。。

**Comment by igorschlum** [comment] 2024-09-11 17:23
duplicate of https://github.com/ollama/ollama/issues/6745

**Comment by pdevine** [comment] 2024-09-11 18:36
cc @jmorganca

**Comment by jmorganca** [comment] 2024-09-12 00:03
Hi @syuan-Boom make sure to pull the model:

```
mattw/loganalyzer
```

Note this is a larger model and this example will be updated soon.

**Closed by jmorganca** 2024-09-12 00:03 UTC
Labels: bug

**Comment by syuan-Boom** [comment] 2024-09-19 03:23
> Hi @syuan-Boom make sure to pull the model:嗨，请务必拉取模型：
> 
> ```
> mattw/loganalyzer
> ```
> 
> Note this is a larger model and this example will be updated soon.请注意，这是一个更大的模型，此示例将很快更新。

you mean this model will be updated later? how can I describe this news? By the way, I have pull the model. It does not work turly.
