### ISSUE TITLE
It seems that the new KV cache quantization feature is incorrectly allocating resources.

### ISSUE THREAD

**Issue by necrogay** [ollama/ollama#7965] opened 2024-12-06 09:53 UTC
### What is the issue?

For example (q4_0 kv):
/set parameter num_ctx 88000
Rombos-LLM-V2.6-Qwen-14b-Q4_K_M:latest 81d0d17e9f6a 21 GB 100% GPU 4 minutes from now

However, the actual VRAM usage amounts to 13,880,772K

There is a significant difference between the actual VRAM usage (13.24 GB) and what Ollama reports (21 GB).

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.5.0

**Comment by rick-github** [comment] 2024-12-06 11:10
https://github.com/ollama/ollama/issues/6160

**Comment by pdevine** [comment] 2024-12-20 22:19
Going to close this as a dupe of the other issue.

**Closed by pdevine** 2024-12-20 22:19 UTC
Labels: bug
