### ISSUE TITLE
Codestral doesn't output correct response

### ISSUE THREAD

**Issue by jasonhotsauce** [ollama/ollama#4713] opened 2024-05-30 00:19 UTC
### What is the issue?

Example:
```
>>> write a python function to calculate fibonacci sequence
[control_8][control_11][control_19][control_35][control_18][control_11]▅[control_20][control_20][control_20][TOOL_RESULTS][control_27][control_32][control_20][control_8][control_11][control_19][control_35][control_18][control_11]▅[control_20][control_20][control_20][TOOL_RESULTS][control_27][control_32][control_20][control_32][control_19][control_21][control_26][control_19][/TOOL_RESULTS][control_11][control_30][control_16][control_14]

>>> /bye
```

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.39

**Comment by cwijayasundara** [comment] 2024-05-30 07:00
I see the same error with codestral:latest

**Comment by MrShenhongbo** [comment] 2024-05-30 08:29
me too!

**Comment by maxruby** [comment] 2024-05-30 09:16
```
>>> 10 + 10
[control_34][control_23]▅[control_25][control_8][control_14][control_15]
```

**Comment by mosh98** [comment] 2024-05-30 09:34
same here

**Comment by yangroro** [comment] 2024-05-30 16:35
Same here
M1 
Sonoma 14.5 
16GB RAM 
ollama version is 0.1.39

**Comment by ZanMax** [comment] 2024-05-31 05:59
Works fine with (M2, 64 GB RAM, Sonoma 14.5)

`ollama run codestral
>>> write a python function to calculate fibonacci sequence
 Sure, here is a simple Python function that calculates the Fibonacci sequence up to the nth term:

```python
def fibonacci(n):
    if n <= 0:
        return "Input should be positive integer."
    elif n == 1:
        return [0]
    elif n == 2:
        return [0, 1]
    else:
        sequence = [0, 1]
        while len(sequence) < n:
            sequence.append(sequence[-1] + sequence[-2])
        return sequence
```

You can use this function by calling it with the number of terms you want to generate as an argument, like so:

```python
print(fibonacci(10))
```

This will print the first 10 numbers in the Fibonacci sequence.

>>> 10 + 10
 The expression "10 + 10" does not have any relation to the previously defined function or the concept of the Fibonacci sequence. It's a simple arithmetic operation that adds two numbers together, and in
this case, it results in 20.`

**Comment by jasonhotsauce** [comment] 2024-05-31 17:56
Is it only a M1 issue then?

**Comment by ZanMax** [comment] 2024-05-31 18:00
I think it's a problem with the amount of RAM. 
v0.1.40 already has a fix: "Fixed out of memory and incorrect token issues when running Codestral on 16GB Macs"

**Comment by jimccadm** [comment] 2024-06-01 16:13
Same here also
M1
Sonoma 14.5
16GB RAM
ollama version is 0.1.39 

ZanMax - thanks for the update on 1.40 will try when I can.

**Comment by maxruby** [comment] 2024-06-01 16:31
> MacBook Pro M1 Sonoma 14.4 16 GB RAM ollama version is 0.1.39
> 
> ```
> >>> 10 + 10
> [control_34][control_23]▅[control_25][control_8][control_14][control_15]
> ```

I can confirm that `0.1.40` fixes the output issue on M1 with 16 GB RAM. 
Be warned, in my experience its extremely slow most likely due to the limited RAM available.

**Comment by jmorganca** [comment] 2024-11-17 22:24
Closing as this is fixed. Thanks for the help, all!

**Closed by jmorganca** 2024-11-17 22:24 UTC
Labels: bug
