### ISSUE TITLE
Can Ollama run more than one instance on Ubuntu

### ISSUE THREAD

**Issue by myrainbowandsky** [ollama/ollama#2201] opened 2024-01-26 07:35 UTC
Since Ubuntu is multi-user operation system.
But I found if sb (not necessarily sudo user) is using Ollama, the other users cannot use it. How to deal with it?

**Comment by wookayin** [comment] 2024-01-26 08:11
`OLLAMA_HOST=0.0.0.0:<some-different-port> ollama run`

Ollama can run without sudo permissions of course.

**Comment by pdevine** [comment] 2024-01-26 23:51
If two requests happen at the same time, ollama will block until the first request is finished. We'll look at handling concurrent requests in a future version.

Going to close this as a duplicate of #358

**Closed by pdevine** 2024-01-26 23:51 UTC
