### ISSUE TITLE
CUDA error: an illegal memory access was encountered 

### ISSUE THREAD

**Issue by lizhichao999** [ollama/ollama#3164] opened 2024-03-15 09:41 UTC
### What is the issue?

![image](https://github.com/ollama/ollama/assets/34128722/101417a2-b080-4f5e-9ef1-9a5daca16959)
![image](https://github.com/ollama/ollama/assets/34128722/f3cd93fa-1882-4089-927b-d9048fee5346)
![image](https://github.com/ollama/ollama/assets/34128722/fda0c05b-08e2-4ea2-b9f3-a1ce642a3e11)

ollama run llama2 
When I executed the command: ollama run llama2, an error occurred related to the data information.

system：Windows Server 2022
GPU： NVIDIA RTX A6000
nvidia driver version：31.0.15.5123

### What did you expect to see?

Operate normally: ollama run llama2

### Steps to reproduce

ollama run llama2 

### OS

Windows

### Architecture

amd64

### Ollama version

 0.1.29

### GPU

Nvidia

### GPU info

RTX A6000

### CPU

Intel

**Comment by dhiltgen** [comment] 2024-03-15 19:58
Looks like a duplicate of #3074

**Closed by dhiltgen** 2024-03-15 19:58 UTC
Labels: bug, windows, nvidia, needs-triage
