### ISSUE TITLE
[Linux] Ran out of space while installing llama2 model, can't delete or find

### ISSUE THREAD

**Issue by saamerm** [ollama/ollama#2497] opened 2024-02-14 18:28 UTC
I installed ollama on my Linux EC2 machine with 8GB of Hard disk space and 4GB of free disk space.

I ran `ollama run llama2` by mistake before checking the space, but it was too quick to download before I could react and I ran out of space, with this error "no space left on device"
Now can't delete or find the model, and `ollama rm llama2` is useless. Where can I find the partially downloaded model to delete?

**Comment by saamerm** [comment] 2024-02-14 18:34
Any idea? @easp @wrapss @remy415 @shersoni610

**Comment by remy415** [comment] 2024-02-14 18:39
@saamerm as mentioned by @jeffdhooton, delete the files in /usr/share/ollama/.ollama/models and check ~/.ollama/models

**Comment by remy415** [comment] 2024-02-14 18:41
Ollama when run as a service seems to save them in /usr/share/ollama by default, and my user mode binaries  when I compile on my own seem to use ~/.ollama.

**Comment by saamerm** [comment] 2024-02-14 18:42
This is amazing, thank you all! I just need to figure out how to get around the permission issue when I try to get to that ollama directory now
Would it make sense to add this answer to an FAQ of some kind if someone else has the issue?

**Comment by remy415** [comment] 2024-02-14 18:45
> This is amazing, thank you all! I just need to figure out how to get around the permission issue when I try to get to that ollama directory now Would it make sense to add this answer to an FAQ of some kind if someone else has the issue?

If you installed as a service as root, you would’ve had to have root permissions to even complete the install. Try using sudo rm -rf /usr/share/ollama/.ollama/models/*

**Comment by jeffdhooton** [comment] 2024-02-14 18:45
> This is amazing, thank you all! I just need to figure out how to get around the permission issue when I try to get to that ollama directory now Would it make sense to add this answer to an FAQ of some kind if someone else has the issue?

If you run `su` and authenticate as a root user you can get there.

You can then cd into the dir and run something like `find . -type f -name "*-partial*" -delete` to get rid of all partials. I wouldn't blindly run that last command if I were you though, would double check.

**Comment by saamerm** [comment] 2024-02-14 19:06
there seems to have been an error with that session, I disconnected and came back and I didnt see the permission error. @jeffdhooton that was perfect. I used `ollama run dolphin-phi` instead. Right at the end I got this
```
...
verifying sha256 digest 
writing manifest 
removing any unused layers 
success 
Error: Post "http://127.0.0.1:11434/api/chat": EOF
```
Any ideas ?

**Comment by pdevine** [comment] 2024-02-18 07:04
You shouldn't need to delete any of the files manually. If you stop the ollama service and restart it it should clean up any dangling files. You can also change the location of where the files are stored with the `OLLAMA_MODELS` env variable for the server. More details are [here in the FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-set-them-to-a-different-location).

The EOF error seems should be unrelated. Usually it's because you have run out of memory or something has happened to the server. You'll need to look at the server logs to figure that out.

**Comment by saamerm** [comment] 2024-02-29 03:06
I also noticed that restarting and starting the server doesn't delete the temporary files in linux from the `tmp` directory

**Comment by remy415** [comment] 2024-02-29 03:52
@saamerm by design, all files in /tmp can be deleted at any time (that’s the whole point of the folder). You can manually clear them if they’re an issue

**Comment by 0xrsydn** [comment] 2024-04-23 06:35
im using wsl and there is no .ollama or models in my ollama folder. The folder looks like this:

```
(base) rsydn9@RASYIDAN-PC:/usr/share/ollama$ ll
total 20
drwxr-x---   2 ollama ollama 4096 Feb 26 12:13 ./
drwxr-xr-x 145 root   root   4096 Apr  7 07:51 ../
-rw-r--r--   1 ollama ollama  220 Jan  6  2022 .bash_logout
-rw-r--r--   1 ollama ollama 3771 Jan  6  2022 .bashrc
-rw-r--r--   1 ollama ollama  807 Jan  6  2022 .profile
```

any idea how to free up my space as i want to delete mistral model from my local pc?

**Comment by remy415** [comment] 2024-04-23 11:26
@0xrsydn  check /home/ollama/.ollama and /home/rsydn9/.ollama. Worst comes to worst, give it the ‘ole `sudo find / -name ‘*.ollama*’ 2>/dev/null’

**Comment by infofromca** [comment] 2024-04-27 17:14
C:\Users\<YourUsername>\.ollama
 in windows?

**Comment by pdevine** [comment] 2024-05-09 00:44
Ack, forgot to close this before. Just restart the ollama server. @0xrsydn check out the [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored) to see where the models are stored.

**Closed by pdevine** 2024-05-09 00:44 UTC
Labels: bug
