### ISSUE TITLE
Speech-To-Text Transcription

### ISSUE THREAD

**Issue by HerroHK** [ollama/ollama#5451] opened 2024-07-03 00:56 UTC
Issue: our company has audio recordings that are confidential in nature. We have setup a linux server (Ubuntu) running Ollama with both Open-WebUI and AnythingLLM as interface. However, it seems both are not able to transcribe long (up to 8 hours) audio recordings, and we only get back snippets. It is also unclear where the boundaries are in terms of time, as it seems some parts do get translated.  

It would make a great addition to Ollama if we could make use of Whisper or other models locally to do this. 

I am pretty sure it is a very common use-case of AI, with plenty of "commercially available options". But it is mostly that we can't use commercial services easily to fullfill our needs and contracts at the same time. 

Thanks for considering this.

**Comment by pdevine** [comment] 2024-07-03 16:33
@HerroHK Thanks for the issue. Definitely something we'd like to add at some point. I'm going to close this though as a dupe of #3265. There's also #1234 for Text-to-Speech.

**Closed by pdevine** 2024-07-03 16:33 UTC
Labels: feature request
