### ISSUE TITLE
mxbai-embed-large embedding not consistent with original paper

### ISSUE THREAD

**Issue by deadbeef84** [ollama/ollama#4207] opened 2024-05-06 19:21 UTC
### What is the issue?

I'm trying to use embeddings from `mxbai-embed-large` to create a similarity/semantic search functionality, but the quality of the embeddings coming from ollama doesn't seem to be very good.

I've tried replicating the numbers from [the original blog post](https://www.mixedbread.ai/blog/mxbai-embed-large-v1):

```js
import { Ollama } from 'ollama'
import cosineSimilarity from 'compute-cosine-similarity'

const ollama = new Ollama({ host: 'http://127.0.0.1:11434' })

const docs = [
  'Represent this sentence for searching relevant passages: A man is eating a piece of bread',
  'A man is eating food.',
  'A man is eating pasta.',
  'The girl is carrying a baby.',
  'A man is riding a horse.',
]

const [queryEmbedding, ...embeddings] = await Promise.all(
  docs.map(
    async (doc) => (await ollama.embeddings({ model: 'mxbai-embed-large', prompt: doc })).embedding
  )
)

const similarities = embeddings.map((e) => cosineSimilarity(queryEmbedding, e))
console.log(similarities)
```

```js
[
  0.6231103528590645,
  0.6258446589848462,
  0.5631986516911313,
  0.5891047395895846
]
```

Those numbers are nowhere close to the original numbers, and if I compare the embedding vectors they are completely different.

The [javascript implementation at huggingface](https://huggingface.co/mixedbread-ai/mxbai-embed-large-v1) produces the same numbers as the original post.

### OS

Linux, Docker

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.1.33

**Comment by deadbeef84** [comment] 2024-05-06 21:22
Same thing with snowflake:

Ollama using `snowflake-arctic-embed:137m-m-long-fp16`
```
Query: Represent this sentence for searching relevant passages: A man is eating a piece of bread
0.408 A man is eating food.
0.368 A man is riding a horse.
0.353 A man is eating pasta.
0.259 The girl is carrying a baby.
```

`@xenova/transformers` and `Snowflake/snowflake-arctic-embed-m-long`
```
Query: Represent this sentence for searching relevant passages: A man is eating a piece of bread
0.581 A man is eating food.
0.538 A man is eating pasta.
0.471 A man is riding a horse.
0.375 The girl is carrying a baby.
```

I expected these to give same results.

**Comment by deadbeef84** [comment] 2024-05-07 21:06
I've now also confirmed the issue is still happening in ollama v0.1.34

**Comment by deadbeef84** [comment] 2024-05-10 21:36
https://github.com/ollama/ollama/issues/3777
Perhaps related?

**Comment by ActionsPerMinute** [comment] 2024-05-11 00:12
I also have this issue  v0.1.35. following the blog with mxbai-embed-large gives the wrong results. switching embedding models provide the correct results

**Comment by VMinB12** [comment] 2024-05-11 15:13
I can also confirm that Ollama embeddings for `snowflake-arctic-embed:137m-m-long-fp16` are not behaving as expected. I set up a synthetic benchmark for internal testing. I take 500 articles and use an LLM to generate a question for each article. Then I retrieve based on a given question and check if the top retrieved article matches the article that was used to generate the question.
I'm using LangChain and get the following results:
```
# embeddings = OpenAIEmbeddings(model="text-embedding-3-small") # 0.8709677419354839
# embeddings = OpenAIEmbeddings(model="text-embedding-3-large") # 0.8951612903225806
# embeddings = OllamaEmbeddings(model="nomic-embed-text")  # 0.7842741935483871
# embeddings = OllamaEmbeddings(
#    model="nomic-embed-text",
#    query_instruction="",
#    embed_instruction="",
#    num_ctx=8192,
#    temperature=0,
#)  # 0.8185483870967742
# embeddings = OllamaEmbeddings(model="mxbai-embed-large")  # 0.6653225806451613
# embeddings = OllamaEmbeddings(model="all-minilm")  # 0.45564516129032256
# embeddings = OllamaEmbeddings(model="snowflake-arctic-embed")  # 0.14516129032258066
# embeddings = OllamaEmbeddings(
#     model="snowflake-arctic-embed:137m-m-long-fp16",
#     query_instruction="",
#     embed_instruction="",
#     num_ctx=8192,
#     temperature=0,
# )  # 0.06854838709677419
# OllamaEmbeddings(model="snowflake-arctic-embed:137m-m-long-fp16") # 0.07661290322580645
```
I'm not sure if the result from `nomic-embed-text` is in alignment with expectations. If so, it could be an indication that the problem is not with Ollama itself, but rather the model weights of the snowflake and mxbai models.

**Comment by deadbeef84** [comment] 2024-05-13 17:50
Similarities after PR #4399:

### mxbai-embed-large
```
Query: Represent this sentence for searching relevant passages: A man is eating a piece of bread
0.791 A man is eating food.
0.636 A man is eating pasta.
0.360 A man is riding a horse.
0.163 The girl is carrying a baby.
```

### snowflake-arctic-embed:137m-m-long-fp16
```
Query: Represent this sentence for searching relevant passages: A man is eating a piece of bread
0.581 A man is eating food.
0.538 A man is eating pasta.
0.471 A man is riding a horse.
0.375 The girl is carrying a baby.
```

**Comment by fredrik-smedberg** [comment] 2024-05-14 15:44
Tack @deadbeef84 for creating this issue. I've been scratching my head over the weekend, changed to different embedding models and had very odd results. Good to know I wasn't crazy and that Ollama actually was a bit broken. I'll update Ollama and see if my ChromaDB <-> Ollama experiment runs better.

**Comment by hazelwolf** [comment] 2024-05-18 10:05
@deadbeef84 thanks for the fix, this solves the issue.

**Comment by moracca** [comment] 2024-06-06 22:45
@jmorganca have you seen this issue and the related PR?  Wondering if you have any thoughts on the proposed fix and what we might be able to do to gain some traction on the issue, since as it stands the embeddings generated by ollama are not accurate, breaking most RAG applications.  Thanks!

**Comment by jeugregg** [comment] 2024-06-07 05:01
I have the same issue. I would like to know when the the fix can be merged.

**Closed** 2024-06-09 01:47 UTC
Labels: bug

**Comment by jeugregg** [comment] 2024-06-12 14:38
I think I have tried with the ollama server version 0.1.43 and ollama-python Version: 0.2.1 with the same test as @deadbeef84  before and after the fix and it is still not working. 
same wrong results 
Is it normal?
this fix is merged?

**Comment by jeugregg** [comment] 2024-07-17 15:02
It is still not working with ollama-python 0.2.1 and ollama version 0.2.5
@jmorganca  it is only solver on javascript ? 
If I test with python, it is still not working. No change.

**Comment by fredrik-smedberg** [comment] 2024-07-17 20:11
> Actually, for my issue, it is working with ollama-python 0.2.1 and ollama version 0.2.5 but not with langchain ! So the issue is with langchain. sorry.

Maybe you've forgotten to begin your query prompt with "Represent this sentence for searching relevant passages:"
If you don't, the mxbai model will not work for retrieval. Source: https://huggingface.co/mixedbread-ai/mxbai-embed-large-v1

**Comment by jeugregg** [comment] 2024-07-18 05:29
Yes but no. I have reproduce the original blob post test in python. 
It works with :
-  Langchain + Llamafile
- Ollama directly

BUT NOT  with : 
- Langchain + Ollama
