### ISSUE TITLE
model in 3 part

### ISSUE THREAD

**Issue by werruww** [ollama/ollama#7245] opened 2024-10-17 19:40 UTC
How do I run a model divided into parts in Olam?

**Comment by werruww** [comment] 2024-10-17 19:40
model gguf

**Comment by werruww** [comment] 2024-10-17 19:41
with modelfile

**Comment by werruww** [comment] 2024-10-17 19:57
k.gguf-00001-of-00003.gguf
k.gguf-00002-of-00003.gguf
k.gguf-00003-of-00003.gguf

how to run on ollama without merg?

**Comment by werruww** [comment] 2024-10-17 20:34
Does Obama support fragmented models? Important: They must be merged before running in Olama by modelfile

**Comment by pdevine** [comment] 2024-10-23 01:45
Dupe of #7272

**Closed by pdevine** 2024-10-23 01:45 UTC
Labels: feature request
