### ISSUE TITLE
ollama serve yields "'model' not found" error because of incorrect default OLLAMA_MODELS value on Linux

### ISSUE THREAD

**Issue by cedricvidal** [ollama/ollama#3740] opened 2024-04-19 00:42 UTC
### What is the issue?

On Linux, the `pull` and `run` commands use the `/usr/share/ollama/.ollama/models` models folder but `serve` uses the `OLLAMA_MODELS` env var which defaults to `~/.ollama/models` as per the help:

```
$ ollama serve --help
    OLLAMA_MODELS       The path to the models directory (default is "~/.ollama/models")
```

By default, the `serve` command will therefore not see any models and will yield an error such as the following:

```
'llama3:latest' not found, try pulling it first
```

A workaround is to set the `OLLAMA_MODELS` to point to the `/usr/share/ollama/.ollama/models` directory like so:

```
export OLLAMA_MODELS=/usr/share/ollama/.ollama/models
```

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.32

**Comment by woshilaowanga** [comment] 2024-05-14 07:00
same question in windows

**Comment by pdevine** [comment] 2024-05-14 23:41
Hey @cedricvidal , the `ollama pull` and `ollama run` commands talk directly to the ollama server using the REST API and do not look for models on disk at all.

Did you by chance change the `OLLAMA_MODELS` environment variable _after_ using `pull` or `run`? Are you running ollama through systemd or in some other way?

I'll go ahead and close the issue since it's running as intended, but please feel free to keep commenting.

**Closed by pdevine** 2024-05-14 23:41 UTC
Labels: bug

**Comment by woshilaowanga** [comment] 2024-05-16 02:19
then I try to pull in CMD，issue is only pull in webui

**Comment by pdevine** [comment] 2024-05-16 21:11
@woshilaowanga I think check with the webui project? Maybe they are doing things incorrectly.

**Comment by PranayShah** [comment] 2024-06-01 07:00
I did run into exactly the same issue on Linux. As you can see below
<img width="1303" alt="Screenshot 2024-06-01 at 12 29 04 PM" src="https://github.com/ollama/ollama/assets/2013275/c18d2005-c281-4ce2-894e-cf20ccfae65a">

And setting `OLLAMA_MODELS` fixed it for me.

**Comment by EzeLLM** [comment] 2024-11-22 07:49
setting OLLAMA_MODELS fixed it for me too.
thanks

**Comment by sourcesync** [comment] 2026-03-19 20:40
OLLAMA_MODELS works on Jetson Orin
I run the following:
```
OLLAMA_HOST=0.0.0.0:1234 OLLAMA_MODELS=/usr/share/ollama/.ollama/models ollama serve
```
