### ISSUE TITLE
streaming for tools support

### ISSUE THREAD

**Issue by ZHOUxiaohe1987** [ollama/ollama#7776] opened 2024-11-21 07:01 UTC
I try to use tools in stream way  with langchain, but it do not work.

**Comment by rick-github** [comment] 2024-11-21 08:37
https://github.com/ollama/ollama/issues/5796

**Comment by ParthSareen** [comment] 2024-11-21 09:55
Closing this as duplicate of #5796

**Closed by ParthSareen** 2024-11-21 09:55 UTC
Labels: feature request
