### ISSUE TITLE
truly opensource model called olmo

### ISSUE THREAD

**Issue by userforsource** [ollama/ollama#3673] opened 2024-04-16 13:40 UTC
### What model would you like?

Build with truly open dataset and fully open-source model can this be supported in olllama thanks.
https://allenai.org/olmo
https://huggingface.co/allenai/OLMo-7B

**Comment by pdevine** [comment] 2024-04-16 23:15
Dupe of #2337

**Closed by pdevine** 2024-04-16 23:15 UTC
Labels: model request

**Comment by userforsource** [comment] 2024-04-20 13:03
https://github.com/ggerganov/llama.cpp/pull/6741
Now

    Hello, as referenced in issue https://github.com/ollama/ollama/issues/2287 the models supported are the ones llama.cpp supports. Check their forum and see if they support it.

This is now support in llama.cpp can you new support into ollama thanks
