### ISSUE TITLE
`CUDA error 100` after detecting GPU libraries on system

### ISSUE THREAD

**Issue by jmorganca** [ollama/ollama#1940] opened 2024-01-12 01:13 UTC
It seems that upon detecting an Nvidia card, `ollama` may error with `CUDA error 100`:

```
Jan 11 15:37:50 LR9135SQP ollama[5616]: 2024/01/11 15:37:50 gpu.go:88: Detecting GPU type
Jan 11 15:37:50 LR9135SQP ollama[5616]: 2024/01/11 15:37:50 gpu.go:203: Searching for GPU management library libnvidia-ml.so
Jan 11 15:37:50 LR9135SQP ollama[5616]: 2024/01/11 15:37:50 gpu.go:248: Discovered GPU libraries: [/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.535.104.05 /usr/lib/wsl/lib/libnvidia-ml.so.1]
Jan 11 15:37:50 LR9135SQP ollama[5616]: 2024/01/11 15:37:50 gpu.go:259: Unable to load CUDA management library /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.535.104.05: nvml vram init failure: 9
Jan 11 15:37:51 LR9135SQP ollama[5616]: 2024/01/11 15:37:51 gpu.go:94: Nvidia GPU detected
Jan 11 15:37:51 LR9135SQP ollama[5616]: 2024/01/11 15:37:51 gpu.go:135: CUDA Compute Capability detected: 7.5
```

```
Jan 11 15:55:41 LR9135SQP ollama[5616]: CUDA error 100 at /go/src/github.com/jmorganca/ollama/llm/llama.cpp/ggml-cuda.cu:495: no CUDA-capable device is detected
Jan 11 15:55:41 LR9135SQP ollama[5616]: current device: 1881676272
Jan 11 15:55:41 LR9135SQP ollama[5616]: Lazy loading /tmp/ollama958766944/cuda/libext_server.so library
Jan 11 15:55:41 LR9135SQP ollama[5616]: GGML_ASSERT: /go/src/github.com/jmorganca/ollama/llm/llama.cpp/ggml-cuda.cu:495: !"CUDA error"
```

**Comment by abdinal1** [comment] 2024-01-13 10:26
Error can be reproduced with the Kaggle notebook I released easily:

https://www.kaggle.com/code/aliabdin1/ollama-server/

**Comment by jmorganca** [comment] 2024-01-14 19:46
@abdinal1 thanks!

**Comment by MaxPhilipss** [comment] 2024-01-16 14:54
Having the same issue leading to Error: Post "http://127.0.0.1:11434/api/generate": EOF #1991

**Comment by dhiltgen** [comment] 2024-01-21 20:24
Based on the log message line numbers, I have a feeling this is a variation of #1877

**Comment by dhiltgen** [comment] 2024-01-22 16:50
```
    /**
     * This indicates that no CUDA-capable devices were detected by the installed
     * CUDA driver.
     */
    cudaErrorNoDevice                     =     100,
```

It's still unclear to me why nvidia-ml reports devices but the cuda library does not.  My suspicion is mismatched libraries/drivers.  In 0.1.21 we've switched to linking against the cuda v11 shared libraries and carrying them as payloads instead of linking the v11 static libraries directly into ollama.  This might be sufficient to get us linked to the underlying host cuda libraries, although we might need some further mod's to our rpath settings.

Please give the pre-release [0.1.21](https://github.com/jmorganca/ollama/releases/tag/v0.1.21) a try on any system that was failing with the `CUDA error 100` and report back if the problem is resolved, or still present.

One other possible explanation might be a mistaken driver install in the WSL2 setup.  According to the [CUDA WSL2 docs](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#cuda-support-for-wsl-2), you're not supposed to install the linux driver, as they have wired up a pass-through model for WSL2, but it's possible to accidentally install the driver and cause things not to work.

**Comment by bala-nullpointer** [comment] 2024-01-24 08:19
Hello,
I have updated to version 0.1.21 but still getting a CUDA error - although it is not `CUDA error 100`.

```
CUDA error: an illegal memory access was encountered
  current device: 0, in function ggml_backend_cuda_buffer_clear at /go/src/github.com/jmorganca/ollama/llm/llama.cpp/ggml-cuda.cu:10346
  cudaDeviceSynchronize()
GGML_ASSERT: /go/src/github.com/jmorganca/ollama/llm/llama.cpp/ggml-cuda.cu:233: !"CUDA error"
SIGABRT: abort
PC=0x7fa94dcc900b m=8 sigcode=18446744073709551610
signal arrived during cgo execution.
```

I assuming `ollama serve` does detect a GPU from this output:-
```
2024/01/24 08:02:29 gpu.go:137: INFO CUDA Compute Capability detected: 7.0
2024/01/24 08:02:29 gpu.go:137: INFO CUDA Compute Capability detected: 7.0
2024/01/24 08:02:29 cpu_common.go:11: INFO CPU has AVX2
loading library /tmp/ollama2178682280/cuda_v11/libext_server.so
2024/01/24 08:02:29 dyn_ext_server.go:90: INFO Loading Dynamic llm server: /tmp/ollama2178682280/cuda_v11/libext_server.so
2024/01/24 08:02:29 dyn_ext_server.go:145: INFO Initializing llama server
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: Tesla V100-PCIE-16GB, compute capability 7.0, VMM: yes
llama_model_loader: loaded meta data with 23 key-value pairs and 291 tensors from /home/fincopilot-tijori/.ollama/models/blobs/sha256:8934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef9246 (version GGUF V3 (latest))
```

`nvidia-smi` output:-
```
Wed Jan 24 08:10:00 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100-PCIE-16GB           Off | 00000001:00:00.0 Off |                  Off |
| N/A   30C    P0              24W / 250W |      0MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                    
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```
And, `nvcc --version` output:-
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:17:15_PST_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0`

Setup:-
Azure VM Standard NC6s v3 (6 vcpus, 112 GiB memory) with one V100 GPU.

Worst part, was running perfectly with version `0.1.20` last week.

**Comment by dhiltgen** [comment] 2024-01-24 19:04
@bala-nullpointer I think this is probably a different issue - Looking upstream at llama.cpp I see a recent issue tracking a similar problem. https://github.com/ggerganov/llama.cpp/issues/5102

**Comment by bala-nullpointer** [comment] 2024-01-24 20:17
@dhiltgen thanks for pointing it out. Will track that issue.

Nope it was a `CUDA error 700`, with this trace. 

```
CUDA error 700 at /go/src/github.com/jmorganca/ollama/llm/llama.cpp/ggml-cuda.cu:9177: an illegal memory access was encountered
current device: 0
GGML_ASSERT: /go/src/github.com/jmorganca/ollama/llm/llama.cpp/ggml-cuda.cu:9177: !"CUDA error"
SIGABRT: abort
PC=0x7f4a7f30f00b m=8 sigcode=18446744073709551610
signal arrived during cgo execution
```
Apologies, if that caused any confusion. 

With respect to my issue, I deleted that instance (with a V100 16GB GPU), spun up a new instance with an A100 40GB GPU on Google Cloud and installed Nvidia drivers and Ollama from scratch - which I had tried on the older instance too. And now `ollama serve` and `ollama run llama2` are working fine.

Here are outputs of `nvidia-smi` and `nvcc --version`.

```
Wed Jan 24 20:08:53 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-SXM4-40GB          On  | 00000000:00:04.0 Off |                    0 |
| N/A   30C    P0              52W / 400W |   5728MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A       622      C   /usr/local/bin/ollama                      5710MiB |
+---------------------------------------------------------------------------------------+
```

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:17:15_PST_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0
```

**Comment by dhiltgen** [comment] 2024-01-27 00:16
I'll keep this issue open for a while to see if anyone else is still able to repro on 0.1.22 or later builds.  If not, I'll close it as fixed based on various improvements we've made to the way we link the libraries, and upstream fixes in llama.cpp.

**Closed** 2024-02-19 19:50 UTC
Labels: bug, nvidia
