### ISSUE TITLE
Per-Model Concurrency

### ISSUE THREAD

**Issue by ProjectMoon** [ollama/ollama#5693] opened 2024-07-15 00:14 UTC
I like the new concurrency features. I'm wondering if it would be possible to add a new Modelfile parameter to control parallel requests on a per-model basis. This would override `OLLAMA_NUM_PARALLEL` if set. The primary use-case for this idea is to allow small models like embedding models to serve many quick requests at once, while the larger models that take longer can serve a smaller number of requests at a time. This would allow larger models to be loaded more into the GPU, while the embedding models can work much faster.

Embedding creation from OpenWebUI is much much faster when hitting a bunch of documents (~45) with a high parallelism (20 in the test). However, this high parallelism forces the LLM model that will generate text to be mostly loaded into CPU, because it is also expecting to serve 20 parallel requests (when in reality it's going to serve one).

**Comment by ProjectMoon** [comment] 2024-07-15 00:21
Based on quick skim of the code, it could perhaps be stuck in sched.go under `processPending`, and just set `numParallel` to the Modelfile's value, if it exists?

**Comment by ProjectMoon** [comment] 2024-07-15 00:25
https://github.com/ollama/ollama/pull/5657 also relevant.

**Comment by pdevine** [comment] 2024-09-17 01:44
This is definitely something that we're thinking about, but I'm going to close it as a dupe of #4894 

cc @dhiltgen

**Closed by pdevine** 2024-09-17 01:44 UTC
Labels: feature request
