### ISSUE TITLE
Support For TPU's 

### ISSUE THREAD

**Issue by Moonlight1220** [ollama/ollama#5550] opened 2024-07-08 20:10 UTC
**Hello Ollama Community,**

Single board computers such as the Raspberry Pi have limitless possibilities when it comes to expansion, this can be very useful for AI. With products such as the Raspberry Pi AI Kit from seed studio and the Coral AI family of TPU's from Google this can accelerate LLM's and may prove useful for a small AI computer that you can take anywhere!

**Comment by pdevine** [comment] 2024-07-08 22:24
This is a dupe of #990 . It's definitely something on the radar!

**Closed by pdevine** 2024-07-08 22:24 UTC
Labels: feature request

**Comment by Moonlight1220** [comment] 2024-07-09 22:01
Great! Let me know if there is any updates.
