### ISSUE TITLE
Windows defender alert & false-positive detection

### ISSUE THREAD

**Issue by allandclive** [ollama/ollama#2519] opened 2024-02-15 19:41 UTC
![Captureq](https://github.com/ollama/ollama/assets/43777357/c6f0dd3f-fdc9-4635-9b19-1ccaafc2414c)

**Comment by jmorganca** [comment] 2024-02-15 19:47
Hi @allandclive, would it be possible to make sure your virus is up to date? Ollama on Windows preview is a new piece of software, signed with an EV certificate by DigiCert. To state the obvious: no trojan script is packaged with Ollama.

Windows Defender has a [history](https://forums.developer.nvidia.com/t/windows-defender-flags-cudnn64-6-dll-as-trojan-win32-peals-f-cl/56734) of flagging CUDA libraries (which Ollama includes). Will work to figure out how to make sure this doesn't appear any more.

**Comment by allandclive** [comment] 2024-02-15 19:49
It's up to date

**Comment by fristhon** [comment] 2024-02-15 20:11
+1
AFAIK code signing takes some days to get approved by Microsoft

**Comment by dhiltgen** [comment] 2024-02-15 21:28
Digging around, it seems this false positive is common for Inno Setup based installers.
Since we just got our signing key in the past few days, I'm inclined to wait a little bit to see if this self-corrects.  If not, then we may want to take a look at the uninstall aspects [here](https://github.com/ollama/ollama/blob/windows-preview/app/ollama.iss#L113-L117) which seem be be what triggers this AV detection logic according to others who have hit this false positive.

**Comment by dhiltgen** [comment] 2024-02-15 23:55
To test my theory above, I've produced a test build of the installer that removes 2 of plausible uninstall paths (`"{%TEMP}\ollama*"` and `"{%USERPROFILE}\.ollama"`) that may be resulting in this AV flag.  Would someone who's seen this AV warning be willing to give this installer a try and report back?

https://github.com/dhiltgen/ollama/releases/download/v0.1.25/OllamaSetup.exe

**Comment by rezonant** [comment] 2024-02-16 03:19
For me the file listed on the Github README identifies as `Trojan:Win32/Sabsik.FL.A!ml` on Windows Defender (Windows 11). 

Uploading that to VirusTotal yields no flags: https://www.virustotal.com/gui/file/80f7cb53c6ddba62076bcffabf926e070bec78587ee4a927208165f8afe9afce

I scanned your updated installer and it does not flag Windows Defender for me, but I did upload it to VirusTotal as well and it did hit a flag on Microsoft's AV for `Trojan:Win32/Wacatac.B!ml` as originally reported. 

https://www.virustotal.com/gui/file/68157bfc0a9385a0aaf809e6621a6d6de5219a8444b22573ce483269fc25fe1d/details

**Comment by Leonai-do** [comment] 2024-02-16 16:31
![Screenshot 2024-02-16 122900](https://github.com/ollama/ollama/assets/23642230/9f299fa4-431e-4eaf-86ca-7cd7b80438db)
Kaspersky also detect some files with trojans

**Comment by dhiltgen** [comment] 2024-02-16 17:11
Thanks for checking!

So it sounds like those two removals didn't resolve the problem.  Another plausible cause is the way we carry payloads inside the primary executable, which isn't strictly necessary on windows now, so I'll start exploring a change to carry everything as installer payloads and no nesting inside the ollama binary.

**Comment by dhiltgen** [comment] 2024-02-16 22:23
I've tried various permutations and our setup installer always triggers the Microsoft AV in virtustotal.  The underlying ollama.exe shows clean with or without the nested payloads.  Maybe Microsoft just doesn't trust our cert yet.

**Comment by rezonant** [comment] 2024-02-17 07:07
Sources online say this is common and that having a cert doesn't guarantee you aren't flagged. You need to run your releases through something like VirusTotal, and then submit your executable in a whitelist request. Microsoft has a form for that. After awhile you won't be flagged as your reputation grows. Good luck.

**Comment by fristhon** [comment] 2024-02-17 10:58
Some useful insights and the form that @rezonant is talking about can be found here
https://learn.microsoft.com/en-us/microsoft-365/security/defender/criteria

**Comment by dhiltgen** [comment] 2024-02-19 21:26
We've submitted a ticket to Microsoft so hopefully that will work through the system before we cut our next release and fix the false positives.

**Comment by jmorganca** [comment] 2024-02-21 20:45
Hi all, wanted to post an update. As mentioned by @dhiltgen, we've contacted Microsoft to resolve this false-positive issue. It is common with Go projects (see https://go.dev/doc/faq#virus) and has affected similar projects such as Docker for Windows.

While we work on fixing this with Microsoft (we are in contact with their Security Intelligence team), you can fix the false-positive warning by updating your Windows Defender Virus Definitions:

* Open **Virus & threat protection** in the **Windows Security** application
* Click on **Protection updates** under **Virus & threat protection updates**:
![image](https://github.com/ollama/ollama/assets/251292/79ceb680-3bad-4c48-87d6-5e7b0229416c)
* Click **Check for updates**
![image](https://github.com/ollama/ollama/assets/251292/0eb0465b-25f2-4216-a65e-023fd439ba2f)

**Comment by OMGnotThatGuy** [comment] 2024-02-21 21:16
Security intelligence version: 1.405.380.0 still alerts false positive.

**Comment by solitaryurt** [comment] 2024-02-21 21:54
> I also just had a trojan warning with Microsoft Defender when trying to update ollama - all virus definitions are up to date

Same with `v0.1.26`

**Comment by internetscooter** [comment] 2024-02-21 22:38
Security intelligence version: 1.405.391.0 still alerts false positive.

Different alert though?

[Trojan:Script/Sabsik.FL.A!ml](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FSabsik.FL.A!ml&threatid=2147780199)

![Capture](https://github.com/ollama/ollama/assets/630867/1f99b8e4-42aa-44e2-9987-4b3afef8ef8d)

**Comment by solitaryurt** [comment] 2024-02-21 23:35
> Security intelligence version: 1.405.391.0 still alerts false positive.
> 
> Different alert though?
> 
> [Trojan:Script/Sabsik.FL.A!ml](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FSabsik.FL.A!ml&threatid=2147780199)

These false positives are very common with Windows binaries unfortunately.

**Comment by EmmaWebGH** [comment] 2024-02-22 05:23
Soooo how do we get it to run?

**Comment by EmmaWebGH** [comment] 2024-02-22 05:44
Also - I can't tell if it's running or not.
I have Ollama in WSL, working well. I have now also installed the Windows version (and got that shock of the virus flag!).
In powershell I enter
ollama run llama2
And it starts up pretty quick.
It didn't seem to download. Is it using the model I already have from WSL?

If not, and I'm NOT running my WSL version, well there's no Ollama icon in the system tray like the video said there would be.

I assume it's windows because I didn't enter the command in the Ubuntu terminal, but in powershell.
But assume I have the brain of a 5 year old, is my own assumption correct?

**Comment by Lunarisnia** [comment] 2024-02-22 05:54
![image](https://github.com/ollama/ollama/assets/50898372/5b5412aa-b473-4be5-aa5a-21536171b913)
Happened when trying to update

**Comment by EmmaWebGH** [comment] 2024-02-22 07:17
I tried starting Ollama anyway. It started. BUT

When I start Ollama using WIndows Powershell, is it running the windows one or the WSL one? I would have thought Windows version, because surely only the Ubuntu prompt would start the WSL one.

Bear with me here - the reason I can't tell if it's Windows is:
1.
For `ollama run llama2` it starts up pretty quick - it didn't seem to download. So is it running the model file I already downloaded for WSL?

2.
I thought the Windows version would have it's models in the users home folder?
I looked, and C:\Users\COMPUTERFACE\.ollama has no models in it. So IS it using the WSL models?
(If I download a new model, where will it go? WSL folder or windows version folder?)

3.
Also - there's no Ollama icon in the system tray like the video said there would be for the windows version. So how do I tell if Win version is running?

Maybe this is a dumb question, but given the ambiguities I've listed I am confused.

**Comment by nagkumar** [comment] 2024-02-22 09:28
<img width="230" alt="image" src="https://github.com/ollama/ollama/assets/332234/06d86ac2-646a-4c45-bc7a-23249707b853">

Upon an update to this version, virus alert is shown

<img width="519" alt="image" src="https://github.com/ollama/ollama/assets/332234/d4a3c5d1-95f1-4427-9a4b-68ebe06fe902">

**Comment by shiro-videXX** [comment] 2024-02-22 10:59
When trying to update to the newest version (v0.1.26), Windows Defender also flagged this as a threat for me on Windows 10.

Interestingly, ollama seems to be version 0.1.26 according to version info and it seems to run commands normally.

![ollama_update_threat](https://github.com/ollama/ollama/assets/127434682/fb781f31-4ea6-4056-a46a-bf2eee4004b9)

**Comment by schergr** [comment] 2024-02-22 14:21
I received the same.  Let me know if you need any logs.

**Comment by dasjet** [comment] 2024-02-22 15:45
![Screenshot 2024-02-22 211151](https://github.com/ollama/ollama/assets/1393520/513a942c-f423-4040-b915-74092d7b57b0)
Kaspersky warning

**Comment by davidlehub** [comment] 2024-02-22 15:55
same for me on windows 11. Not sure if it's really safe to "allow" it to run

**Comment by Alias4D** [comment] 2024-02-22 20:19
![Screenshot 2024-02-22 230809](https://github.com/ollama/ollama/assets/27604791/8d28b38d-c244-48d0-8aeb-270c4d786053)

**Comment by MisterAG** [comment] 2024-02-22 20:24
Exact same error message as Alias4D above....

**Comment by metathron** [comment] 2024-02-22 20:36
> ![Screenshot 2024-02-22 230809](https://private-user-images.githubusercontent.com/27604791/307138187-8d28b38d-c244-48d0-8aeb-270c4d786053.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MzQ0NzUsIm5iZiI6MTcwODYzNDE3NSwicGF0aCI6Ii8yNzYwNDc5MS8zMDcxMzgxODctOGQyOGIzOGQtYzI0NC00OGQwLThhZWItMjcwYzRkNzg2MDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDIwMzYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiOGZiZWU1NDI0NDQ2YTg2N2IzMDk5MWM5NjE5NmVjNjkyMTk5Mjg2NThiMmUyZDA1YzliMGUwNTkyNmVlNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uFdOoD2mUIEvbMl8b0Y8LszSMw-WyEtAbqIdeP-T0E8)

I got the same Trojan warning

**Comment by jmorganca** [comment] 2024-02-23 01:07
Hi folks, we're almost done resolving this with Microsoft. 2/3 of the binaries included with Ollama no longer seem to be triggering false alarms, one more to go and we have an ongoing ticket with Microsoft for it.

Thanks for your patience and I'm so sorry for the alert.

**Comment by ahmedhamdy78** [comment] 2024-02-23 05:14
![still warning](https://github.com/ollama/ollama/assets/159552521/5752fec9-9852-4f3d-9a01-e123944eeeba)

**Comment by jmorganca** [comment] 2024-02-23 23:24
Hi all, this should be much improved for the time being. I'm going to close this, with a plan to re-open it should it become a problem again. Note: it may take some time for the Windows Defender definitions to update to account for this (although all machines where I was able to reproduce it have stopped showing alerts at this point).

To everyone who hit this issue: I'm sorry and understand how shocking it might have been in the moment. I hope it doesn't deter you from giving Ollama on Windows another try.

Many more improvements to Windows to come!

**Comment by EmmaWebGH** [comment] 2024-02-24 00:22
@jmorganca Will the new installer resolve the ambiguities I detailed in my message above?

My initial theory was that incomplete installation (due to virus being flagged) meant I never saw the system tray icon appear.

Pasting the original comment here, so you don't have to scroll up:
***
When I start Ollama using WIndows Powershell, is it running the windows one or the WSL one? I would have thought Windows version, because surely only the Ubuntu prompt would start the WSL one.

Bear with me here - the reason I can't tell if it's Windows is:
1.
For ollama run llama2 it starts up pretty quick - it didn't seem to download. So is it running the model file I already downloaded for WSL?

I thought the Windows version would have it's models in the users home folder?
I looked, and C:\Users\COMPUTERFACE.ollama has no models in it. So IS it using the WSL models?
(If I download a new model, where will it go? WSL folder or windows version folder?)

Also - there's no Ollama icon in the system tray like the video said there would be for the windows version. So how do I tell if Win version is running?

Maybe this is a dumb question, but given the ambiguities I've listed I am confused.

**Comment by dotysan** [comment] 2024-02-24 00:39
Hi @EmmaWebGH, I'm new here too. But happen to have learned the answers to your questions from recently reading the source and docs. https://github.com/ollama/ollama/blob/main/docs/faq.md

> I tried starting Ollama anyway. It started. BUT

If the false-threat got blocked/quarantined, you'll need to uninstall and try again with a newer release--and after updating your MS Defender crud.

> 
> When I start Ollama using WIndows Powershell, is it running the windows one or the WSL one? I would have thought Windows version, because surely only the Ubuntu prompt would start the WSL one.

PowerShell is Windows not WSL. WSL is bash by default.

> 
> Bear with me here - the reason I can't tell if it's Windows is: 1. For `ollama run llama2` it starts up pretty quick - it didn't seem to download. So is it running the model file I already downloaded for WSL?
> 
> 
> I thought the Windows version would have it's models in the users home folder? I looked, and C:\Users\COMPUTERFACE.ollama has no models in it. So IS it using the WSL models? (If I download a new model, where will it go? WSL folder or windows version folder?)

https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored

> 
> 
> Also - there's no Ollama icon in the system tray like the video said there would be for the windows version. So how do I tell if Win version is running?

This is likely due to the quarantine/blocking. See above.

> 
> Maybe this is a dumb question, but given the ambiguities I've listed I am confused.

There are no dumb questions.

I've been able to use it by downloading the source and compiling from scratch. No Defender alerts!

Not to tricky, but does require you carefully satisfy all the dependencies--some not fully documented yet. https://github.com/ollama/ollama/blob/main/docs/development.md#windows

**Comment by jphat** [comment] 2024-02-24 03:42
ollama 0.1.27 and intelligence 1.405.505.0 produces no errors for me

**Comment by EmmaWebGH** [comment] 2024-02-25 11:48
@dotysan 

You're saying if it was quarantined it WOULDN'T start? Because it did. A file was supposedly quarantined and yet I can run llama2 from Powershell.

Thanks for the link to where the models are stored / docs.
But... there are no models in that folder! (nothing in Windows: C:\Users\<username>\.ollama\models) 
And yet... Ollama started and ran llama2 it started and responded to prompts. 

Hence my confusion, and I'm still confused.

**Comment by dotysan** [comment] 2024-02-25 17:43
> You're saying if it was quarantined it WOULDN'T start? Because it did.

I did not say that.

This issue about the false-positive is closed. If you have another issue, open a new one.

If you are curious about the client/server architecture of the ollama Go binary (as I was), read the source, documentation, or watch some videos about it. https://www.youtube.com/@technovangelist

**Comment by boessu** [comment] 2024-05-13 18:35
Today I've got a warning from Windows Defender that ollama app.exe is infected with Trojan:Win32/Wacatac.H!ml. Is that a false positive too?

**Comment by dhiltgen** [comment] 2024-05-13 22:34
Sorry you hit this.  We've submitted the latest release binaries to the false positive site to get it resolved.

**Comment by dhiltgen** [comment] 2024-05-31 21:24
I haven't heard and fresh reports of false positives, so I'll close this.

**Comment by mhubregtse** [comment] 2024-08-01 08:59
Hi today i wanted to install ollama on a Bitdefender protected machine, it triggers as a trojan **Atc4.Detection**.
So it seems the problem has returned ?

**Comment by dhiltgen** [comment] 2024-08-01 23:25
@mhubregtse can you share which version, and which file triggered the AV detection?

**Comment by dhiltgen** [comment] 2024-08-02 20:45
We'll get the latest binaries submitted to msft to clear up the false positive.  We recently updated Go versions so that likely explains why it's popping up again.

**Comment by dhiltgen** [comment] 2024-08-09 23:02
It should be clear by now.  If anyone is still seeing the false positive pop up, please let us know.

**Closed by dhiltgen** 2024-08-09 23:02 UTC
Labels: bug, windows

**Comment by Sascha353** [comment] 2024-08-13 09:18
Just today I got the first false-positive detection:
![image](https://github.com/user-attachments/assets/79e27adf-abee-4639-8f01-daa66badd91f)

**Comment by pschaer** [comment] 2024-08-13 11:06
same here:
![image](https://github.com/user-attachments/assets/3c717df9-3c29-4438-af8b-913bc15fa8e7)

**Comment by xaydras-2** [comment] 2024-08-13 18:25
I updated ollama before it finish window detected a Trojan. It did finish downloading
![Capture](https://github.com/user-attachments/assets/0fa07d32-fb4d-4759-83f6-0c1520cd4e3b)

**Comment by TraoreMorike** [comment] 2024-08-13 18:50
Hello, 

Same here : 

Windows 11 Pro 23H2

![image](https://github.com/user-attachments/assets/c72821bb-222e-4232-b8ac-02c3bf5fb0c7)

**Comment by livioenrico** [comment] 2024-08-14 07:48
For me the same today:

```

Threat removed
14/08/2024 08:15

Severe

Detected: Trojan:Script/Wacatac gil
Status: Removed or restored

This threat or app was removed from quarantine or
restored to the device.

Date: 14/08/2024 08:15
Details: This program is dangerous and executes
commands from an attacker.

Affected items:

file: C:\Users\Win10\AppData\Local\Programs\Ollama\ollama app.exe

file: C:\Users\Win10\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Ollama.ink

file: C:\Users\Win10\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Ollama\Ollama nk

file: C:\Users\Win10\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\startup\Ollamaink

startup: C:\Users\Win10\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Ollama.ink

startup: C:\Users\Win10\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Ollama\Ollama.nk

startup: C:\Users\Win10\AppData\Roaming\Microsoft\Windows\start Menu\Programs\Startup\Ollamaink
```

**Comment by dhiltgen** [comment] 2024-08-14 16:41
@livioenrico please confirm this was version 0.3.5 that was flagged, correct?  0.3.6 shouldn't trigger the false positive.

**Comment by jpaveg** [comment] 2024-08-14 18:14
> @livioenrico please confirm this was version 0.3.5 that was flagged, correct? 0.3.6 shouldn't trigger the false positive.

For me, 0.3.6 was flagged. It triggered after hitting 'restart to update'.

**Comment by dhiltgen** [comment] 2024-09-03 19:04
@jpaveg or others, are you still seeing AV false positives with the latest versions?

**Comment by jpaveg** [comment] 2024-09-03 19:05
> @jpaveg or others, are you still seeing AV false positives with the latest versions?

I haven't seen any false positives since reinstalling.

**Comment by mfarme** [comment] 2024-09-03 19:11
@dhiltgen updated today and no issues.

**Comment by xaydras-2** [comment] 2024-09-03 19:55
Since the last update, there isn't any false positive

**Comment by jaseva** [comment] 2024-09-17 14:09
Tried downloading today and received this warning:
<img width="318" alt="image" src="https://github.com/user-attachments/assets/259c2923-16b6-4d1e-bf61-fd75a9779664">

**Comment by dhiltgen** [comment] 2024-09-17 16:13
I've confirmed the 0.3.10 (currently latest) binary is signed with our signing key, and uploaded it to Virus Total, and it reports [clean](https://www.virustotal.com/gui/file/3be19a085685324066762f33c46c4a1121f27e7a1ea9b441d0becf57dbb34375/details) (including McAffee's VT integration)

@jaseva do you have the latest definitions installed from McAfee?

**Comment by jaseva** [comment] 2024-09-17 16:27
Hi @dhiltgen, I only have the McAfee WebAdvisor Extension plugin installed in Microsoft Edge and I do not see any section to manually update the definitions.  I assume the definitions are managed automically. My browser and extension are up to date.

<img width="632" alt="image" src="https://github.com/user-attachments/assets/9abcb2c0-7c87-496c-84d6-f58bb24b448d">

**Comment by dhiltgen** [comment] 2024-09-17 18:35
I tried to submit our installer to their portal for false positive disputes, but it doesn't accept large files so I was unable to complete the process.  @jaseva if you have an account with McAfee, can you try to upload?

**Comment by jaseva** [comment] 2024-09-17 18:48
Hi @dhiltgen I submitted a form to McAfee asking that they check the software and update the definitions for their WebAdvisor tool. I'll update this ticket when they reply. The upload form would only accept a maximum file size of 500 MB.
