### ISSUE TITLE
Llama3.1 405b q1 q2 q5 q6 q8 fp16

### ISSUE THREAD

**Issue by Llamadouble999q** [ollama/ollama#5945] opened 2024-07-25 10:26 UTC
Would support?

**Comment by kozuch** [comment] 2024-07-28 10:24
Related issue: https://github.com/ollama/ollama/issues/5889

**Comment by gileneusz** [comment] 2024-08-02 17:09
it's quite concerning why ollama team ignores gpu rich users 🤑😁

**Comment by igorschlum** [comment] 2024-08-06 07:42
Hello, they are all there in instruct:
405b-instruct-q2_K
811dcd740cc3 • 151GB • Updated 2 hours ago
405b-instruct-q3_K_L
98babcc85c29 • 215GB • Updated 28 minutes ago
405b-instruct-q3_K_M
2d60e04cc717 • 197GB • Updated 56 minutes ago
405b-instruct-q3_K_S
8efe69b31081 • 177GB • Updated 2 hours ago
405b-instruct-q4_0
78f97162a617 • 231GB • Updated 5 hours ago
405b-instruct-q4_1
5db145603842 • 257GB • Updated 4 hours ago
405b-instruct-q5_0
1fb70cf0a02b • 282GB • Updated 4 hours ago
405b-instruct-q5_1
c8ba45da8139 • 308GB • Updated 3 hours ago
405b-instruct-q8_0
f5ac28d40d17 • 436GB • Updated 3 hours ago

@Llamadouble999q could you please close the issue to keep the issues under 1000 :-)

**Comment by kozuch** [comment] 2024-08-06 09:02
Still Q1 missing...

**Comment by alvincho** [comment] 2024-08-06 10:20
I tried q2 but got an error: wrong number of tensors; expected 1138, got 1137

**Comment by kozuch** [comment] 2024-08-06 13:21
> I tried q2 but got an error: wrong number of tensors; expected 1138, got 1137

@alvincho Same problem was reported at https://github.com/ollama/ollama/issues/5889. Please report the problem as bug in separate issue.

**Comment by igorschlum** [comment] 2024-08-11 23:49
Hi @Llamadouble999q I tried 405b-insctruct-q2_K and it is less powerfull than 70b-instruct-q8_0 in solving math + logical question.
I don't think that q1 could be effective. Do you have a link on internet to Llama3.1:405-instruct-q1 ? I search and find nothing.

**Comment by MaxJa4** [comment] 2024-08-14 22:53
@Llamadouble999q 405B has been uploaded a few days ago, can this issue be closed?

**Comment by igorschlum** [comment] 2024-08-15 05:09
@alvincho @kozuch 405b models have been updated several times in the library without versioning. It's possible that this occurred while you were pulling your model. Can you confirmed that you could successfully pull them since?

**Comment by alvincho** [comment] 2024-08-15 05:47
I update a new version of ollama and it works now

**Comment by igorschlum** [comment] 2024-08-15 05:59
Hi @Llamadouble999q,

Working with an extremely large model, such as a 405 billion parameter model, using a quantization level of Q1 is not effective and that's why it's not proposed in the library.

Quantization reduces the computational load and memory footprint of LLMs by approximating the weights of the model, which reduces the precision of the answers. This is true for any model size, but especially for very large models.

The minimum recommended quantization level is Q2. Ideally, aim for Q4 and progressively move up to Q8 if you have the computational resources and time. This ensures progressively higher degrees of precision and better answers.

Could you please close the issue if you agree?

**Comment by pdevine** [comment] 2024-08-28 21:19
Closing since this is supported now. You can find the tags here: https://ollama.com/library/llama3.1/tags

**Closed by pdevine** 2024-08-28 21:19 UTC
Labels: model request
