### ISSUE TITLE
BCEmbedding model support

### ISSUE THREAD

**Issue by laipz8200** [ollama/ollama#4650] opened 2024-05-26 16:10 UTC
Hello,

I would like to request support for the [BCEmbedding](https://github.com/netease-youdao/BCEmbedding) model, which is an embedding model that performs exceptionally well in both Chinese and English.

Thank you very much for your work.

**Comment by thinkverse** [comment] 2024-05-26 23:14
Duplicate of https://github.com/ollama/ollama/issues/3630.

**Closed** 2024-05-26 23:54 UTC
Labels: model request
