### ISSUE TITLE
Some issues on Windows

### ISSUE THREAD

**Issue by vrubzov1957** [ollama/ollama#2766] opened 2024-02-26 16:49 UTC
Guys, have some issues with Ollama on Windows (11 + WSL2). 
Ollama version - was downloaded 24.02.2024 from off-site, version for Windows.

1. Ollama models works on CPU, not on GPU (Nvidia 1080 11G). Once upon a time it somehow run on the video card - but the pattern of how and when it works could not be found out, looks that select GPU/CPU randomly. On CPU good/big models works very slow.
2. After restart of Windows Ollama server not up. Need manually open cmd-terminal, type "ollama serve", and hold terminal-windows opened.

**Comment by dhiltgen** [comment] 2024-02-26 17:35
Could you share the server log?

Have you considered the new native Windows version instead of WSL2?

**Comment by vrubzov1957** [comment] 2024-02-26 23:57
> Could you share the server log?
Sure. This?
[server.log](https://github.com/ollama/ollama/files/14412548/server.log)

> Have you considered the new native Windows version instead of WSL2?
I am using this version:
<img width="522" alt="ollama" src="https://github.com/ollama/ollama/assets/54937209/61e6c78e-e39c-439a-a989-cc33fc4c6bea">

**Comment by dhiltgen** [comment] 2024-02-27 16:39
Thanks for the log files.

It looks like things are behaving as expected, and the models are being loaded into the GPU.  When you load the larger model, it's only able to load `26/81 layers to GPU` given your limited VRAM.  As a result, the GPU spends most of its time idle waiting for the CPU to process the layers it has loaded into system memory.  This is expected behavior.


In the opening comment you mention `After restart of Windows Ollama server not up` which sounds like it is likely the result of the AV scan.  That was tracked in issue #2519 and has been resolved with Microsoft.  Please make sure you've updated your AV definitions, and Ollama should no longer be tagged with this false positive.

**Closed by dhiltgen** 2024-02-27 16:39 UTC
