### ISSUE TITLE
Handle Multiple parallel request

### ISSUE THREAD

**Issue by lauvindra** [ollama/ollama#1956] opened 2024-01-12 16:48 UTC
Does Ollama uses some kind of scheduling algorithm to manage high concurrent request? can you explain this

**Comment by easp** [comment] 2024-01-13 19:09
It queues the requests and processes them serially.

**Comment by pdevine** [comment] 2024-01-15 22:51
We'll add in better support for scheduling in the future, but as @easp mentioned, it just blocks all the other clients on a request and then those clients race to get fulfilled next. Definitely not ideal.

**Comment by pdevine** [comment] 2024-01-26 23:51
Going to close this as a dupe of #358

**Closed by pdevine** 2024-01-26 23:51 UTC
