### ISSUE TITLE
API enhancement - create endpoint to fetch hosted models

### ISSUE THREAD

**Issue by aroffe99** [ollama/ollama#2544] opened 2024-02-16 17:11 UTC
I'd like to create a UI where users have the option of clicking any model listed in https://ollama.com/library and that model would be pulled in the background. Right now I provide free text for users to insert the model and tag but `model:tag` can get pretty long and error prone for users to type it.

Alternatively instead of a new api endpoint to get this information, add a boolean parameter `remote` to /api/tags to show remote, downloadable models.

**Comment by joshmedeski** [comment] 2024-03-28 22:11
Is this something that an open-source contributor can add? I'd be willing to help add support for listing remote models.

**Comment by pdevine** [comment] 2024-05-10 21:37
Sorry for the slow response on this. We definitely want to do something with this in the future.

Going to close this as a dupe of #1070

**Closed by pdevine** 2024-05-10 21:37 UTC
Labels: feature request
