### ISSUE TITLE
Can please used huh forms for better ui?

### ISSUE THREAD

**Issue by nikhil-swamix** [ollama/ollama#5584] opened 2024-07-09 22:48 UTC
https://github.com/charmbracelet/huh

after [seeing this issue](https://github.com/miniscruff/changie/issues/611) i understood the ollama cli needs an overhaul, for example if json response is generated by llm the form can dynamically update. im not sure how this would implement, but it will enable ollama to be used as agent out of box. or atleast not type `ollama -h` 100 times or memorize stuff.

let me know your perspective.

**Comment by pdevine** [comment] 2024-07-10 17:57
Hey @nikhil-swamix , I have looked at Charm before and using a viewport for buffering output from the LLM. The problem is that the buffer has to redraw a lot of characters repeatedly and ends up with a "flickering" effect when it's updating which was really visually distracting.

Regardless, the CLI is really supposed to be "bare bones" to show developers how to properly use the API to write their own clients. I think it's pretty successful at doing that right now (particularly with line wrapping / multi-byte character support), so there aren't any plans currently to change away from that. I'm going to close the issue, but I do appreciate the comments though!

**Closed by pdevine** 2024-07-10 17:57 UTC
Labels: feature request
