### ISSUE TITLE
ollama save  feature

### ISSUE THREAD

**Issue by CorollaD** [ollama/ollama#4785] opened 2024-06-02 15:23 UTC
Can you add the feature of ollama save as well as docker save that export the local docker image to migration to other envenriment?

**Comment by pdevine** [comment] 2024-06-05 20:51
@CorollaD Do you want to copy a single model, or all of the models?

**Comment by yuge-byte** [comment] 2024-06-06 07:54
> @CorollaD Do you want to copy a single model, or all of the models?

I want to know to copy a single model, did ollama support this function now?

**Comment by pdevine** [comment] 2024-06-07 22:36
Currently there's no way to export a single model, however, you can copy the models directory if you want to copy all of them. This is actually a dupe of #335 (which is old, but let's track it there).

**Closed by pdevine** 2024-06-07 22:36 UTC
Labels: feature request
