### ISSUE TITLE
Multiple requests at once

### ISSUE THREAD

**Issue by trymeouteh** [ollama/ollama#2845] opened 2024-02-29 21:31 UTC
Would take more computing power on the users machine, but to allow Ollama to be able to make multiple requests at once.

Lets say you have two terminal windows running and you ask the AI in Window 1 to do X and ask the AI in Windows 2 which will either be using the same model or a different model and ask it to do Y and it will do X and Y at the same time, and not wait to do Y once X is done.

Or even if you have one application that integrated Ollama and another application that integrated Ollama, to be able to do X in application 1 and Y in application 2 at the same time.

**Comment by pdevine** [comment] 2024-03-01 01:01
Closing as dupe of #358

**Closed by pdevine** 2024-03-01 01:01 UTC
