### ISSUE TITLE
May I know whether Ollama support DBRX model?

### ISSUE THREAD

**Issue by OPDEV001** [ollama/ollama#3443] opened 2024-04-01 22:56 UTC
### What model would you like?

I checked the https://ollama.com/library but can not find the DBRX in list.

May I run DBRX model on local machine, CPU and GPU, like ollama run dbrx-xxx-yyyy?

Thanks,

**Comment by crmne** [comment] 2024-04-02 08:53
duplicate of #3370

**Closed** 2024-10-23 18:11 UTC
