### ISSUE TITLE
ollama run deepseek-coder-v2 creates gibberish output

### ISSUE THREAD

**Issue by flo-ivar** [ollama/ollama#5787] opened 2024-07-19 06:40 UTC
### What is the issue?

Hi,

I am trying to run the 16b ollama deepseek-coder-v2, which leads to a "gibberish" output.
Strangely enough it works after a fresh download, but then after trying to run it in Aider it doesnt.

![image](https://github.com/user-attachments/assets/9e6df4f7-dc47-49bc-a306-2e73c73b4098)

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.2.7

**Comment by RobinEccleston** [comment] 2024-07-19 09:13
I have also experienced the same issue, but for me it only occurs with codegeex4 and glm4. All other models are fine. I removed and reinstalled the models with no luck and also updated ollama with no difference. Generally a few messages are fine and then it turns to gibberish seemingly at random.

**Comment by rick-github** [comment] 2024-07-19 10:22
Server logs might enable diagnosis of the problem.

**Comment by hieuminh65** [comment] 2024-07-19 15:36
I have this too. I dont know if this is a bug or what. I have this with qwen 2 too.
I chat "hello" but it outputs a lot of non-sense things.

<img width="1247" alt="Screenshot 2024-07-19 at 11 35 19 AM" src="https://github.com/user-attachments/assets/126813d4-a8a4-4277-885a-b5ce009d067e">

**Comment by alzubitariq** [comment] 2024-07-20 08:36
I have also experienced the same issue with deepseek-coder-v2

**Comment by nicolasraj** [comment] 2024-07-20 09:37
I am experiencing the same issue with Llama3:8b

**Comment by strangeryf** [comment] 2024-07-20 10:57
I have experienced similar issue with glm4
![image](https://github.com/user-attachments/assets/f0c4d646-2c9d-4d70-be75-84328f908e0d)

**Comment by RobinEccleston** [comment] 2024-07-20 12:10
I managed to trigger this error reliably on my system. If I first use codegeex4, it's fine, then I used phi3 for a single message, and then change back to codegeex4 for one more message, this triggers the problem. I have 4GB of VRAM so only enough for one model at a time. Phi3 has no issues.

**Comment by pdevine** [comment] 2024-09-17 01:39
Dupe of #5339

**Closed by pdevine** 2024-09-17 01:39 UTC
Labels: bug
