### ISSUE TITLE
about jetson atx orin 64G run ollama

### ISSUE THREAD

**Issue by cplasfwst** [ollama/ollama#6800] opened 2024-09-14 10:15 UTC
### What is the issue?

![image](https://github.com/user-attachments/assets/1b9824dc-0ac5-4b38-966a-d94008c26178)
My relevant version is
![image](https://github.com/user-attachments/assets/932f957a-20ec-4744-b9e3-ff013052fd53)

I will get an error when I run it, and it will not run successfully
cplasfwst@ubuntu:~$ ollama ps
NAME        	ID          	SIZE  	PROCESSOR	UNTIL              
qwen2:latest	dd314f039b9d	5.7 GB	100% GPU 	4 minutes from now	
cplasfwst@ubuntu:~$ ollama ps
NAME        	ID          	SIZE  	PROCESSOR	UNTIL              
qwen2:latest	dd314f039b9d	5.7 GB	100% GPU 	4 minutes from now	
cplasfwst@ubuntu:~$ ollama ps
NAME        	ID          	SIZE  	PROCESSOR	UNTIL              
qwen2:latest	dd314f039b9d	5.7 GB	100% GPU 	4 minutes from now	
cplasfwst@ubuntu:~$ jtop
cplasfwst@ubuntu:~$ ollama run qwen2
Error: timed out waiting for llama runner to start - progress 1.00 - 
cplasfwst@ubuntu:~$ 

### OS

Linux

### GPU

Nvidia

### CPU

Other

### Ollama version

0.3.10

**Comment by pdevine** [comment] 2024-09-14 16:27
I think this is a dupe of #2408

**Comment by pdevine** [comment] 2024-09-14 16:27
cc @dhiltgen

**Closed by pdevine** 2024-09-14 16:27 UTC
Labels: bug
