### ISSUE TITLE
Ollama returns: Error: error loading model when importing a fined-tuned converted and quantized model

### ISSUE THREAD

**Issue by FotieMConstant** [ollama/ollama#2935] opened 2024-03-05 12:04 UTC
Hi everyone, i am having an issue running a fine-tuned quantized version of llama2 on ollama. i followed all the stops at: https://github.com/ollama/ollama/blob/main/docs/import.md

however after quantizing and creating my model on ollama. i can see my model on the list however when i run it i get this error

```bash
Error: error loading model /Users/🤓.ollama/models/blobs/sha256:1c75cbd55211b7505be15c897b3ca1766708e5808558139e1531e182
```

can someone help with this? as i am not sure what is going on. technically it should work.

**ollama version is 0.1.27**
**OS: Mac OS Sonama, version 14.3.1 on Apple M1 chip**

**Comment by V4G4X** [comment] 2024-03-06 04:20
Same here

**Comment by mxyng** [comment] 2024-03-06 22:20
Can you share the model? Without knowing the specifics, there's not much we can do to help troubleshoot

**Comment by bmizerany** [comment] 2024-03-06 22:21
@FotieMConstant Can you please share a step-by-step minimal reproduction (Modelfile included) by chance?

**Comment by FotieMConstant** [comment] 2024-03-07 05:38
Sure, so i have fine-tuned a version of Llama2 7b [https://huggingface.co/fotiecodes/Llama-2-7b-chat-jarvis](here). and follwing these instructions [https://github.com/ollama/ollama/blob/main/docs/import.md](here), i cloned, converted and quantized the model and got a "quantized.bin" of about 3.8 GB. i then created a Modelfile and imported the quantized version from there with which i used to create my new model. which is not running.

few things to note. while converting the model, i encountered an error related to vocab size, here is the error: 
```bash
vocab size mismatch (model has 32000, but jarvis-hf/tokenizer.model has 32001).
```
then i followed the fix here-> https://github.com/ggerganov/llama.cpp/issues/3900
went into my hugging face model folder and edited the `config.json` file.
from:
<img width="385" alt="image" src="https://github.com/ollama/ollama/assets/42372656/11318671-f2de-4f3e-bc42-5dec79617be6">

to:

<img width="472" alt="image" src="https://github.com/ollama/ollama/assets/42372656/6f958ba3-3bde-4a54-9611-268879b1fcae">

After this, i wasn then able to convert and quantize, however the model won't run on ollama. by the way, i am able to create and list the model on ollama but it doesn't run. also, all other downloaded models from olllama with the ollama command works perfectly.

please let me know if there is anything else you want me to add.

**Comment by V4G4X** [comment] 2024-03-07 17:47
@mxyng @bmizerany  
Can you share which details you might need for debugging and how I may fetch those?

**Comment by FotieMConstant** [comment] 2024-03-07 19:08
Sure here: `FROM ./ollama/quantized.bin`

**Comment by FotieMConstant** [comment] 2024-03-07 19:11
> Okay weird behaviour.
> 
> It's working now. Hmmm. I don't remember changing anything.

the thing is when i try to convert model with llama.cpp i get this error:

```bash
Writing converted.bin, format 1
Traceback (most recent call last):
  File "/Users/🤓/opensource/jarvis/ollama/llm/llama.cpp/convert.py", line 1483, in <module>
    main()
  File "/Users/🤓/jarvis/ollama/llm/llama.cpp/convert.py", line 1477, in main
    OutputFile.write_all(outfile, ftype, params, model, vocab, special_vocab,
  File "/Users/🤓/jarvis/ollama/llm/llama.cpp/convert.py", line 1117, in write_all
    check_vocab_size(params, vocab, pad_vocab=pad_vocab)
  File "/Users/🤓/jarvis/ollama/llm/llama.cpp/convert.py", line 963, in check_vocab_size
    raise Exception(msg)
Exception: Vocab size mismatch (model has 32000, but ../jarvis-hf/tokenizer.model has 32001).
```

**Comment by FotieMConstant** [comment] 2024-03-07 20:12
@bmizerany i noticed this too, the hash has something at the end, is it normal.

<img width="1089" alt="image" src="https://github.com/ollama/ollama/assets/42372656/a8e9386f-54da-435d-aef8-e2cacad78567">

**Comment by FotieMConstant** [comment] 2024-03-12 11:42
Hey, any update one this issue? anyone?

**Comment by FYYHU** [comment] 2024-03-15 21:00
Question could it be that you finetuned your model using this https://github.com/georgesung/llm_qlora ?

If so I encountered a similar problem: 
I fixed this problem by editing this part of QloraTrainer.py

![Screenshot from 2024-03-15 21-54-14](https://github.com/ollama/ollama/assets/44072346/63e45dd2-1ba0-41c6-9b34-b5d57a0fd16e)
and set it back to
        if not tokenizer.pad_token:
            # Add padding token if missing, e.g. for llama tokenizer
            tokenizer.pad_token = tokenizer.eos_token  

re fine tuning the model will result in a model that does not have that extra vocab

**Comment by FotieMConstant** [comment] 2024-03-15 21:05
Hi there @FYYHU, thanks for your comment, i used an open Jupyter notebook for the fine-tuning, here you can see what i did, any thoughts?

https://colab.research.google.com/drive/1FTt_Z1eGOsl2VgPVb8pnM4yUTczhSutM?usp=sharing

**Comment by FotieMConstant** [comment] 2024-03-15 21:09
I did same here, but seems not to work, also here is a notebook to download and run my custom model, which works fine on Jupyter notebook

https://colab.research.google.com/drive/19ZuropXXc2_jMC_qxqa8MO4mHHxOqxxe?usp=sharing

**Comment by FYYHU** [comment] 2024-03-15 21:39
Ok, I'm not sure if this is the bug but if you look at the model you pull from the NousResearch/Llama-2-7b-chat-hf
![image](https://github.com/ollama/ollama/assets/44072346/48c76818-8ac3-4af7-9b72-dfef0090d26a)
you see in the config.json that they have vocab_size of 32000. But what is weird is that when you load the tokenizer it says it has a length of 32001

![image](https://github.com/ollama/ollama/assets/44072346/dc0a11a3-ade4-49d8-bd8d-99fb5293389a)

I don't know exactly where the bug is, but you could maybe try using a different pre-trained llama chat model?

**Comment by FotieMConstant** [comment] 2024-03-15 21:50
You right @V4G4X i thought as much, any recommendations of another 7B pre-trained llama chat model I can use? I’m pretty new to this and it’s been giving me some headaches for a while now

**Comment by FotieMConstant** [comment] 2024-03-15 21:54
The model from the link you shared above is same actually: https://huggingface.co/georgesung/llama2_7b_openorca_35k/blob/main/config.json

**Comment by V4G4X** [comment] 2024-03-17 01:27
@FotieMConstant I'm new to local OS models as well.  
My laptop only has 8GB RAM, so I use the 1B tier of models. xD  

But if you're taking suggestions, I use starcoder and deepseek-coder for code autocomplete.  
And found Gemma the best for chatting.

**Comment by saul-jb** [comment] 2024-03-17 21:17
I'm getting the same issue with one of the hosted models:

```
$ ollama pull yarn-llama2:13b-128k-q5_K_M
pulling manifest 
pulling 6768c57cf9ca... 100% ▕████████████████▏ 9.2 GB                         
pulling 1639d5c1f004... 100% ▕████████████████▏   18 B                         
pulling 4d4cf0639ed3... 100% ▕████████████████▏  310 B                         
verifying sha256 digest 
writing manifest 
removing any unused layers 
success
```

```
$ ollama run yarn-llama2:13b-128k-q5_K_M
Error: error loading model /usr/share/ollama/.ollama/models/blobs/sha256:6768c57cf9ca3415c5ba91c6483fe5b2938d660520f1fb8dddeb74e5bae91
```

**Comment by FotieMConstant** [comment] 2024-03-18 06:29
Update: I finally was able to fix my issue, it wasn’t me nor the way I trained my model but an issue with the base model I used for fine-tuning. After a couple tweaks here and there and with some help from the llama.cpp community I could fix the issue.

PS: though it might not be a guaranteed solution however, it works:)

**Comment by FotieMConstant** [comment] 2024-03-18 06:31
> I'm getting the same issue with one of the hosted models:
> 
> ```
> $ ollama pull yarn-llama2:13b-128k-q5_K_M
> pulling manifest 
> pulling 6768c57cf9ca... 100% ▕████████████████▏ 9.2 GB                         
> pulling 1639d5c1f004... 100% ▕████████████████▏   18 B                         
> pulling 4d4cf0639ed3... 100% ▕████████████████▏  310 B                         
> verifying sha256 digest 
> writing manifest 
> removing any unused layers 
> success
> ```
> 
>  ```
> $ ollama run yarn-llama2:13b-128k-q5_K_M
> Error: error loading model /usr/share/ollama/.ollama/models/blobs/sha256:6768c57cf9ca3415c5ba91c6483fe5b2938d660520f1fb8dddeb74e5bae91
> ```

this could occur for various reasons, you can check the ollama logs for more information however, I'd say contact the developer who pushed the model.

**Comment by pdevine** [comment] 2024-05-10 20:25
@FotieMConstant thanks for being persistent here and sorry about not updating the issue. There have been a number of changes for the `create` command which should make it somewhat easier to do conversions, but it's definitely far from being perfect at this point.

Since you were able to resolve the issue, I'll go ahead and close it.

**Closed by pdevine** 2024-05-10 20:25 UTC
