### ISSUE TITLE
No "Restart to update" option for Windows auto update

### ISSUE THREAD

**Issue by vootox** [ollama/ollama#5094] opened 2024-06-17 06:33 UTC
Popup says there is an Ollama update; I find I must _Click on the taskbar or menubar item and click "Restart to update" to apply the update._ But, I only see `View Log` and `Quit Ollama` and no `Restart to update`. The logs do appear to have installed the update so
I guess it's being done automatically. I'd rather the message stated that or allowed me to do it.

**Comment by dhiltgen** [comment] 2024-06-18 18:16
We've wired up the notification so that if you click on it, it also triggers the update.  From the sounds of it, you probably clicked on that.

**Comment by vootox** [comment] 2024-06-19 10:30
Yes, I was probably lucky this time. The notification is so fast but that's a good thing, it's less intrusive and more efficient than my fumbling. Thank you for responding and explaining.

**Comment by dhiltgen** [comment] 2024-06-19 16:32
This is an area we'll be improving as we enhance the windows tray application, but it sounds like it's working as intended right now, so I'll go ahead and close this.

**Closed by dhiltgen** 2024-06-19 16:32 UTC
Labels: feature request, windows
