### ISSUE TITLE
How to interrupt streaming output via request?

### ISSUE THREAD

**Issue by wltime** [ollama/ollama#5270] opened 2024-06-25 06:47 UTC
When using ollama for streaming dialogue in the terminal, I can stop the output using CTRL+C, how do I interrupt ollama's output if I use the request?

curl http://localhost:11434/api/generate -d '{
  "model": "llama3",
  "prompt": "Why is the sky blue?",
  "stream": true
}'

**Comment by pdevine** [comment] 2024-07-08 23:23
`CTRL+C` should work in that case too:

```
pdevine@MacBook-Pro-5 ollama % curl http://localhost:11434/api/generate -d '{
"model": "llama3",
"prompt": "Why is the sky blue?",
"stream": true
}'
{"model":"llama3","created_at":"2024-07-08T23:21:07.755286Z","response":"The","done":false}
{"model":"llama3","created_at":"2024-07-08T23:21:07.772244Z","response":" sky","done":false}
{"model":"llama3","created_at":"2024-07-08T23:21:07.788902Z","response":" appears","done":false}
{"model":"llama3","created_at":"2024-07-08T23:21:07.805707Z","response":" blue","done":false}
{"model":"llama3","created_at":"2024-07-08T23:21:07.82271Z","response":" because","done":false}
{"model":"llama3","created_at":"2024-07-08T23:21:07.839931Z","response":" of","done":false}
{"model":"llama3","created_at":"2024-07-08T23:21:07.857103Z","response":" a","done":false}
{"model":"llama3","created_at":"2024-07-08T23:21:07.874151Z","response":" phenomenon","done":false}
{"model":"llama3","created_at":"2024-07-08T23:21:07.891806Z","response":" called","done":false}
{"model":"llama3","created_at":"2024-07-08T23:21:07.908785Z","response":" Ray","done":false}
{"model":"llama3","created_at":"2024-07-08T23:21:07.926127Z","response":"leigh","done":false}
{"model":"llama3","created_at":"2024-07-08T23:21:07.943237Z","response":" scattering","done":false}
{"model":"llama3","created_at":"2024-07-08T23:21:07.96033Z","response":",","done":false}
{"model":"llama3","created_at":"2024-07-08T23:21:07.977535Z","response":" which","done":false}
{"model":"llama3","created_at":"2024-07-08T23:21:07.994651Z","response":" is","done":false}
{"model":"llama3","created_at":"2024-07-08T23:21:08.012004Z","response":" the","done":false}
^C
```

This is in MacOS, but it should work the same regardless of your OS. I'm going to close the issue, but feel free to keep commenting and if there's something I missed we can re-open.

**Closed by pdevine** 2024-07-08 23:23 UTC
Labels: question

**Comment by wltime** [comment] 2024-07-09 01:50
I would like to know if there is an API to interrupt the output of the model

**Comment by kevin-stableedge** [comment] 2024-07-19 19:21
Looking for something similar. Seeing a lot of other posts recommending to just cancel streaming client side but i want Ollama to stop it's inference. 

But i cant find anything in the API docs for how to achieve this.

**Comment by wes-kay** [comment] 2024-11-24 07:38
> `CTRL+C` should work in that case too:
> 
> ```
> pdevine@MacBook-Pro-5 ollama % curl http://localhost:11434/api/generate -d '{
> "model": "llama3",
> "prompt": "Why is the sky blue?",
> "stream": true
> }'
> {"model":"llama3","created_at":"2024-07-08T23:21:07.755286Z","response":"The","done":false}
> {"model":"llama3","created_at":"2024-07-08T23:21:07.772244Z","response":" sky","done":false}
> {"model":"llama3","created_at":"2024-07-08T23:21:07.788902Z","response":" appears","done":false}
> {"model":"llama3","created_at":"2024-07-08T23:21:07.805707Z","response":" blue","done":false}
> {"model":"llama3","created_at":"2024-07-08T23:21:07.82271Z","response":" because","done":false}
> {"model":"llama3","created_at":"2024-07-08T23:21:07.839931Z","response":" of","done":false}
> {"model":"llama3","created_at":"2024-07-08T23:21:07.857103Z","response":" a","done":false}
> {"model":"llama3","created_at":"2024-07-08T23:21:07.874151Z","response":" phenomenon","done":false}
> {"model":"llama3","created_at":"2024-07-08T23:21:07.891806Z","response":" called","done":false}
> {"model":"llama3","created_at":"2024-07-08T23:21:07.908785Z","response":" Ray","done":false}
> {"model":"llama3","created_at":"2024-07-08T23:21:07.926127Z","response":"leigh","done":false}
> {"model":"llama3","created_at":"2024-07-08T23:21:07.943237Z","response":" scattering","done":false}
> {"model":"llama3","created_at":"2024-07-08T23:21:07.96033Z","response":",","done":false}
> {"model":"llama3","created_at":"2024-07-08T23:21:07.977535Z","response":" which","done":false}
> {"model":"llama3","created_at":"2024-07-08T23:21:07.994651Z","response":" is","done":false}
> {"model":"llama3","created_at":"2024-07-08T23:21:08.012004Z","response":" the","done":false}
> ^C
> ```
> 
> This is in MacOS, but it should work the same regardless of your OS. I'm going to close the issue, but feel free to keep commenting and if there's something I missed we can re-open.

This isn't canceling the request through the API but is instead terminating the client-side process. this issue shouldn't have been closed, we're looking for a way to handle canceling the stream to start a new stream.

**Comment by acinnes** [comment] 2024-12-18 18:02
> Looking for something similar. Seeing a lot of other posts recommending to just cancel streaming client side but i want Ollama to stop it's inference.
> 
> But i cant find anything in the API docs for how to achieve this.

I have the same issue. My application is generating a series of speculative LLM requests based on a stream of irregular external system inputs. When a new system input appears, any currently running LLM request is now irrelevant as the latest request will supersede it. 

I'm interrupting the async for loop for consuming the chat completion, and even closing the async response streaming context (using OpenAI Python SDK), but the problem is that the **next** LLM request starts receiving the **remainder of the response from the previous request**. At the very least, I need that to not happen (which I can hack by not allowing my app to send a new request until the current one has finished naturally), but really I want to cancel the previous request, stopping any further output token generation, and have Ollama started on processing the latest request immediately (reusing as much KV cache as possible, based on the common prefix of the previous and latest requests).

**Comment by pdevine** [comment] 2025-01-18 05:51
@wes-kay hanging up on the stream will stop inference. The model stays loaded in memory of course until you unload it or it times out, but there is no more inference running once you hang up on the stream.

If you watch the GPU with something like `asitop` on macOS you should be able to see the GPU immediately stop processing data. LMK if I'm missing something here. Are you looking to stop a different user's API call?

**Comment by wes-kay** [comment] 2025-01-30 03:45
> [@wes-kay](https://github.com/wes-kay) hanging up on the stream will stop inference. The model stays loaded in memory of course until you unload it or it times out, but there is no more inference running once you hang up on the stream.
> 
> If you watch the GPU with something like `asitop` on macOS you should be able to see the GPU immediately stop processing data. LMK if I'm missing something here. Are you looking to stop a different user's API call?

The entire point of this  issue is to be able to interrupt through code so you can start and stop when you want. I  don't think this issue should be closed, as there's still no solution. 

CTRL+C sends a interrupt in the terminal that terminates the process, OP and myself and the 3 other people that gave the 👍 are looking for a way to stop the stream to start another api generate.

**Comment by davidmorrill** [comment] 2025-02-06 20:34
I think there was a bit of a disconnect between @pdevine 's answer and @wes-kay 's question. I stumbled across this thread because I had the same exact problem of wanting to programmatically cancel a streaming response from within my web browser-based client. I think the misunderstanding is in the interpretation of what was meant by "hanging up on the stream".

After reading it a couple of times, I realized that what he probably meant was "cancel the ReadableStream being used to transfer the Ollama responses to the receiving client". At least that's how it translates in the case of a web browser client. It took me a bit time to sort out the details, since I'm using a Web Worker thread to handle the communication with the Ollama server, which the web worker then uses to post progress messages back to the main browser UI thread.

But once I did, I was able to add a button in my client UI which causes the Web Worker to cancel the ReadableStream it uses to funnel the individual Ollama responses back to the UI, which instantly shuts down any further messages from Ollama. I can then type in a new prompt and submit that to Ollama and start receiving responses for the new prompt.

So, while it's not a specific Ollama Rest API function to cancel an existing stream, it's certainly possible to terminate the stream using other API's (in my case, by canceling the Web standard ReadableStream used to transport the Ollama responses to the client).

I hope this helps clarify how it is possible to go about doing this without having to terminate the Ollama client.

**Comment by pdevine** [comment] 2025-02-06 22:15
> My issue is currently there's no way to stop the API from generating, if I need to cancel the context and restart a new prompt I can't and have to wait for it to finish before I can send another request.

The way we handle this in the Ollama client in `cmd.go` is:

```
...
        cancelCtx, cancel := context.WithCancel(cmd.Context())
        defer cancel()

        sigChan := make(chan os.Signal, 1)
        signal.Notify(sigChan, syscall.SIGINT)

        go func() {
                <-sigChan
                cancel()
        }()
...

        if err := client.Chat(cancelCtx, req, fn); err != nil {
                if errors.Is(err, context.Canceled) {
                        return nil, nil
                }
                return nil, err
        }
```

Which just says if you hit Ctrl-C (SIGINT) it will trigger `cancel()` to be called and an error gets returned from `client.Chat()` that we can trap (`context.Canceled`). Ultimately in `client.Chat()` (which is in api/client.go) it calls `c.http.Do(request)` and the cancel will propagate to here and hang up the stream which will immediately stop inference from happening on the ollama server. I know this is in golang, but it should be possible to replicate in other languages as well too.

I was mulling over what you had mentioned before and was trying to determine if you building a multi-user application where you needed to hang up on someone _else's_ stream. That's possible right now too, but definitely trickier to implement.

**Comment by pdevine** [comment] 2025-02-06 22:25
I just realized we also have some [examples](https://github.com/ollama/ollama-js/blob/main/examples/abort) in the [ollama javascript client](https://github.com/ollama/ollama-js) which show how to abort a stream.

**Comment by wes-kay** [comment] 2025-02-06 22:25
> > My issue is currently there's no way to stop the API from generating, if I need to cancel the context and restart a new prompt I can't and have to wait for it to finish before I can send another request.
> 
> The way we handle this in the Ollama client in `cmd.go` is:
> 
> ```
> ...
>         cancelCtx, cancel := context.WithCancel(cmd.Context())
>         defer cancel()
> 
>         sigChan := make(chan os.Signal, 1)
>         signal.Notify(sigChan, syscall.SIGINT)
> 
>         go func() {
>                 <-sigChan
>                 cancel()
>         }()
> ...
> 
>         if err := client.Chat(cancelCtx, req, fn); err != nil {
>                 if errors.Is(err, context.Canceled) {
>                         return nil, nil
>                 }
>                 return nil, err
>         }
> ```
> 
> Which just says if you hit Ctrl-C (SIGINT) it will trigger `cancel()` to be called and an error gets returned from `client.Chat()` that we can trap (`context.Canceled`). Ultimately in `client.Chat()` (which is in api/client.go) it calls `c.http.Do(request)` and the cancel will propagate to here and hang up the stream which will immediately stop inference from happening on the ollama server. I know this is in golang, but it should be possible to replicate in other languages as well too.
> 
> I was mulling over what you had mentioned before and was trying to determine if you building a multi-user application where you needed to hang up on someone _else's_ stream. That's possible right now too, but definitely trickier to implement.

I'm specifically talking about the cli API and since OP is using curl he would most likely be too. 

In terms of your code your just canceling the SIGINT is doing the same thing (like you mentioned) as interrupt, that's not what we're looking for. We don't have access to the same context. 

We need the ability to cancel an inference with the API.

**Comment by wes-kay** [comment] 2025-02-06 22:28
> I just realized we also have some [examples](https://github.com/ollama/ollama-js/blob/main/examples/abort) in the [ollama javascript client](https://github.com/ollama/ollama-js) which show how to abort a stream.

Almost but: https://github.com/ollama/ollama-js/blob/main/src/browser.ts#L51

But `request.abort()` is a method used to cancel an ongoing HTTP request in JavaScript. It is commonly available in the XMLHttpRequest (XHR) and Fetch API (via AbortController). 

Not available to the CLI.

**Comment by pdevine** [comment] 2025-02-07 19:40
@wes-kay I'm not sure what your operating system is, but in linux/macos you can use `kill -SIGINT <pid>` to send an interrupt signal to a process. That's the equivalent of pressing `Ctrl-C`.

**Comment by wes-kay** [comment] 2025-02-07 19:49
> [@wes-kay](https://github.com/wes-kay) I'm not sure what your operating system is, but in linux/macos you can use `kill -SIGINT <pid>` to send an interrupt signal to a process. That's the equivalent of pressing `Ctrl-C`.

But that's killing the process, something we're not looking to do, we just want to stop inference and start a new one with the same stream.

**Comment by pdevine** [comment] 2025-02-07 20:54
> But that's killing the process, something we're not looking to do, we just want to stop inference and start a new one with the same stream.

The API doesn't work that way; the stream only stays open for a single request. To generate a new chat completion you'll have to open a new connection and make a new request.
