### ISSUE TITLE
Expose API via swagger-ui

### ISSUE THREAD

**Issue by haferwolle** [ollama/ollama#3487] opened 2024-04-04 13:27 UTC
### What are you trying to do?

Using the ollama REST API. It's possible, but could be better.

### How should we solve this?

The API is described here: https://github.com/ollama/ollama/blob/main/docs/api.md
However, it is so much more convenient to use an API with a SwaggerUI, especially in the initial phase and to see all available endpoints. There should be a library for golang, which just does that automatically.

### What is the impact of not solving this?

TL;DR Exposing your API as OpenAPI specification opens it up to the entire OpenAPI ecosystem and tools, which makes it much more accessible/usable.

Making your product accessible contributes tremendously to its success. Exposing the API via OpenAPI/swagger-ui not only provides a convenient way to see and use all available endpoints. It also allows to use OpenAPI tools like OpenAPI code-gen, to generate client libraries for basically any programming language. I have seen ollama Java clients developed on github, which is not necessary. With an OpenAPI specification in place a Java client library can be autogenerated with OpenAPI code-gen.

**Comment by jimscard** [comment] 2024-04-07 04:03
See also #3383 for more support for providing an OpenAPI specification and maintaining it.

**Comment by pdevine** [comment] 2024-05-15 00:48
Thanks for the issue! Let's close this as a dupe of #3383

**Closed by pdevine** 2024-05-15 00:48 UTC

**Comment by haferwolle** [comment] 2024-05-15 08:03
@pdevine Thanks for taking care of this so quickly.

**Comment by haferwolle** [comment] 2024-05-15 08:47
@pdevine No worries, great to see things moving.
I'm not a golang developer, otherwise I'd love to join your team. In Java, I use a library called springdoc-openapi, which auto-detects all my REST controllers and endpoints/payloads. Based on that it generates an OpenAPI spec and even serves an embedded swagger-ui. All I need to do is add the library as a dependency. It takes 5 minutes. I especially like the code-first approach, because I always start with developing REST endpoints. I never start with the OpenAPI spec. The library just constantly updates the OpenAPI/swagger based on my code changes. So that's super simple and just enhances my services with no additional effort for me.
For golang I found this project, which seems to be doing a similar thing: https://github.com/swaggest/rest?tab=readme-ov-file
Maybe it helps.
Keep up the good work!
