### ISSUE TITLE
llama3.1:70b CPU battle neck?

### ISSUE THREAD

**Issue by jasonliuspark123** [ollama/ollama#6993] opened 2024-09-27 03:30 UTC
### What is the issue?

CPU only use one core at 100%, while gpu cores mostly run at at less than 20%. 

Model is not responding at good speed. 

I'm wondering if this usage of one cpu core becomes the bottle neck for the performance.

I have read https://github.com/ggerganov/llama.cpp/issues/8684, but have not seen an exact answer.

![c24f866aff701f57270e97aa4b667cd](https://github.com/user-attachments/assets/ddf4b9fe-7d60-4a4c-9c10-ee857afecf9d)

![922760ada75a01e64b76b9c323825fd](https://github.com/user-attachments/assets/280d8540-0a1d-4e0d-a93c-75ba8ac1500e)

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.10

**Comment by jasonliuspark123** [comment] 2024-09-27 03:33
I understand GPU is doing the actural calculating work.  In my case, would it make sense that cpu hasn't send enough requests to GPU to utilize all the computinng power?

**Comment by dhiltgen** [comment] 2024-09-28 23:26
Duplicate of #6913

**Closed by dhiltgen** 2024-09-28 23:26 UTC
Labels: bug
