### ISSUE TITLE
An operation on a socket could not be performed

### ISSUE THREAD

**Issue by ipzzzzz** [ollama/ollama#6869] opened 2024-09-19 03:42 UTC
### What is the issue?

The error reported in the terminal: dial tcp [xxx]:443: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.3.10

**Comment by ipinp** [comment] 2024-09-19 03:42
When I open ollama, the above error occurs, and at this time, other software also cannot connect to the internet. When I turn off ollama, the internet connection of other software returns to normal.

**Comment by dhiltgen** [comment] 2024-09-20 23:42
Were you trying to pull a model at the time this took place?

Can you share your server logs?  https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md

**Comment by gyassine** [comment] 2024-09-24 04:51
Maybe I've got more info on this issue: maybe bandwith... I don't really know how to check... 

But at the beginning of download everything is going well, after a few minutes some apps are deconnecting from internet (like teams, etc.) while the download is still going on. After some more minutes, some webpages doesn't work (mostly the one that have not any cache),  and the download also stops. 

I've got to quit ollama.app to gain access to the net again... otherwise it still prevent me from accessing the net...

**Comment by bvwidt** [comment] 2024-09-24 14:29
I have had the same issue. I installed a fresh ollama and I have started it.
However I was unable to download a model and I received the same error messages as above.
Then I shut down ollama and tried hours later. 🌟 TADA... It works now.

When I consult the logs it looks like another server has been started or ollama was stuck in a loop trying to answer endless requests.

See the corresponding log files attached:

* [server.success.log](https://github.com/user-attachments/files/17116158/server.success.log)
* [server.error.log](https://github.com/user-attachments/files/17116160/server.error.log)
* [app.error.log](https://github.com/user-attachments/files/17116161/app.error.log)
* [app.success.log](https://github.com/user-attachments/files/17116162/app.success.log)

**Comment by dhiltgen** [comment] 2024-09-24 15:51
@ipzzzzz it sounds like Ollama might be overwhelming your network.  We have a feature request tracking rate limiting for slower network connections with #2006 .  In general, Ollama tries to optimize pulling to be as fast as possible given the large size of the models.  We're working to improve the behavior on slower networks.

@bvwidt your problem may not be related.  If you're seeing multiple instances of Ollama conflicting on windows, you may be hitting #2854  We don't fully understand the root cause on that one but 2 possible scenarios are another Ollama running under another user account on the system, or setting OLLAMA_HOST differently.

**Comment by Bdestasio33** [comment] 2024-10-07 02:59
Opened powershell as an admin and ran `netstat -nbt` to list all ports

Killing the process with `netstat -ano | findstr :8080` seemed to solve my issue. Also ran the same with 11434 just incase. all my web pages loaded fine after and solved my pull issue. Might be something that needs optimized here?

**Comment by dhiltgen** [comment] 2024-10-08 23:28
We recently fixed a bug related to retries leaking file descriptors which is likely the root cause of this.  This should be fixed in v0.3.13

**Closed by dhiltgen** 2024-10-08 23:28 UTC
Labels: bug, windows, needs more info
