### ISSUE TITLE
GPU Support for older CPUs lacking AVX

### ISSUE THREAD

**Issue by kaleid1337** [ollama/ollama#6827] opened 2024-09-16 13:15 UTC
I've been trying to run ollama on my server for weeks now, trying to find a workaround to use my GPU for ai tasks, but my Xeon x5670 doesn't support AVX so I'm left with this error.

`WARN source=gpu.go:222 msg="CPU does not have minimum vector extensions, GPU inference disabled" required=avx detected="no vector extensions"
`

My CPU cannot handle such tasks and it needs to be palmed off to the gpu.

**Comment by tcreek** [comment] 2024-09-16 18:44
Nothing can be done about that. And many models will require AVX2. AVX2 was released on CPUs in 2013, so you have a very old CPU.  You can get a whole new desktop motherboard which comes with a much newer Xeon with 12 cores, and 16GB off Aliexpress for only $50 shipped.

**Comment by pdevine** [comment] 2024-09-16 22:40
Hey @kaleid1337 , thanks for the issue. I don't think there are a lot of machines out there that fall into that category, so we wouldn't support that out of the box. It is, however, pretty easy to rebuild ollama from source. Follow the directions [here](https://github.com/ollama/ollama/blob/main/docs/development.md#advanced-cpu-settings).

I think you want to turn `-DGGML_AVX=off`, but I'm not sure what kind of GPU you want to use. I'll close the issue, but would love to know how it goes if you want to comment here. Good luck!

**Closed by pdevine** 2024-09-16 22:40 UTC
Labels: feature request

**Comment by pdevine** [comment] 2024-09-17 00:04
@dhiltgen mentioned this is actually a dupe of #2187 which should have some more clues in it.
