### ISSUE TITLE
Concurrency and multiple calls

### ISSUE THREAD

**Issue by enriquesouza** [ollama/ollama#1356] opened 2023-12-03 02:01 UTC
Hi, I would like to know if running Ollama and making multiple calls is possible. I would love to add a server and use it for my users. 

Therefore, when testing it, I saw it is waiting until a process finishes when I use the liteLLM proxy. 

Is it possible?

**Comment by austin-starks** [comment] 2023-12-03 02:14
Plus one. I love Ollama but I'm failing to see how I could deploy it as a cloud server.

**Comment by easp** [comment] 2023-12-04 16:42
Right now you'd need to start multiple ollama servers on different ports and put them behind a reverse proxy.

I don't have any inside knowledge, but I'd expect this to change since Llama.cpp, which Ollama uses, has added support for batched requests, which is much more efficient than load balancing among separate instances.

**Comment by enriquesouza** [comment] 2023-12-11 17:13
Thanks. I used it with docker and docker swarm, and then it solved with 10 instances running, therefore it is very limited yet. I hope a new version can fix that limitation.

**Comment by pdevine** [comment] 2024-01-26 23:55
Going to close this as a dupe of #358

**Closed by pdevine** 2024-01-26 23:55 UTC
