### ISSUE TITLE
Handling High traffic

### ISSUE THREAD

**Issue by lauvindra** [ollama/ollama#1927] opened 2024-01-11 16:52 UTC
Assume I have ollama in server Tesla T4 GPU with 16GB Vram and 120 Ram, how many request can it handle in one second?

**Comment by easp** [comment] 2024-01-11 21:12
That card apparently has ~320GB/s bandwidth.  Tokens/s generated is approximately 8 bits/byte *320 GB/s / (# model parameters * # bits per parameter).  For a q4 quantization of a 4 bit model that's probably about 100 tokens/s.

Ollama currently queues concurrent requests and processes them serially. This isn't an efficient way to processes concurrent requests.

**Comment by jimscard** [comment] 2024-01-12 06:00
If Ollama is intended to be used as a *local* LLM system, then queuing requests and processing them serially is appropriate.  Enabling concurrent processing, e.g., a "server" scenario would significantly increase the attack surface and  complexity.

**Comment by pdevine** [comment] 2024-01-26 23:52
Going to close this as a dupe of #358

**Closed by pdevine** 2024-01-26 23:52 UTC
