### ISSUE TITLE
" Error: json: cannot unmarshal array into Go struct field Params.eos_token_id of type int " while importing llama 3.1 8B safetensor model from huggingface

### ISSUE THREAD

**Issue by SadeghPouriyanZadeh** [ollama/ollama#5909] opened 2024-07-24 12:15 UTC
## What is the problem?
I was importing the llama 3.1 8B model from huggingface (`meta-llama/Meta-Llama-3.1-8B-Instruct`) using `ollama create -f Modelfile` but i got this error:
`Error: json: cannot unmarshal array into Go struct field Params.eos_token_id of type int`
I found the shallow cause of the error. and i fixed it naively. but i wanted to know why this error happned and what is the better solution.

## What I get from the error?
the `Go struct` gets `int` for `eos_token_id`.
But the `config.json` file and `generation_config.json` file contain `"eos_token_id": [128001, 128008, 128009]`.
So they face type mismatch and we get the error.

## What is my naive solution?
I changed the `eos_token_id` value to `"eos_token_id": 128001` without a concrete reason why i chose `128001` instead of the others. and it solved the problem and a model is created.

## Why this error happened? What is the correct solution?
I don't know. I'd be appreciated to know.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.2.8

**Comment by mr-gorjan** [comment] 2024-07-24 14:07
Having same error, any solution?

**Comment by ygivenx** [comment] 2024-07-24 18:14
I see this error in the docker logs

`error from daemon in stream: Error grabbing logs: invalid character 'l' after object key:value pair`

**Comment by mingmars** [comment] 2024-07-25 12:30
ollama create llama3.1 -f lama31.txt
transferring model data
unpacking model metadata
Error: json: cannot unmarshal array into Go struct field Params.eos_token_id of type int

**Comment by dgallardox** [comment] 2024-07-27 01:48
This is not totally relevant but I was getting the exact same error in Postman when making a POST request to `/api/generate`. It turns out it was caused by quotes in the stream value. E.g.,:

```
{
"model":"llama3",
"prompt": "once upon a time",
"stream": "false" // this causes a problem
}

VS.

{
"model":"llama3",
"prompt": "once upon a time",
"stream": false // this works
}

You possibly have a similar syntax error somewhere?

**Comment by Dudu0831** [comment] 2024-07-29 08:22
I also encountered the same problem, upgrading to 3.0 has not been resolved

**Comment by 202030481266** [comment] 2024-07-29 14:03
same problem

**Comment by hgaong** [comment] 2024-08-01 07:16
same problem

**Comment by hgaong** [comment] 2024-08-01 07:17
I changed the eos_token_id value to "eos_token_id": 128001 without a concrete reason why i chose 128001 instead of the others. and it solved the problem and a model is created.

**Comment by nebula2020** [comment] 2024-08-02 08:42
Same issue I have faced. Switching to gguf deployment now.

**Comment by sergei202** [comment] 2024-08-15 20:16
I was tearing my hair out with this issue and finally got it working:

What fixed it for me is changing the `eos_token_id` in `config.json` to `128001`, as @hgaong had suggested.
That got the model created, but then it wouldn't stop correctly and ended up output trash.

I added to add this to the `Modelfile` before calling `ollama create` and that fixed it!
```
PARAMETER stop <|start_header_id|>
PARAMETER stop <|end_header_id|>
PARAMETER stop <|eot_id|>
TEMPLATE [removed for readability]
```

**Comment by pdevine** [comment] 2024-09-02 00:19
I'm going to go ahead and close this. You shouldn't need to specify the `TEMPLATE` as it should get autodetected.

**Closed by pdevine** 2024-09-02 00:19 UTC
Labels: bug

**Comment by nofreewill42** [comment] 2024-11-12 11:07
I had the error:

```
(.venv) nofreewill@nofreewill:~/FineTuneLLM$ ollama create mymodel -f Modelfile 
transferring model data 100% 
converting model 
Error: json: cannot unmarshal array into Go struct field .model.merges of type string
```

Modelfile content  with the error:
```
FROM ./finetuned_llama_32_3b_gguf
PARAMETER stop [INST]
PARAMETER stop [/INST]
TEMPLATE "[INST] {{ .Prompt }} [/INST]"
```

Fixed model file:
```
FROM ./finetuned_llama_32_3b_gguf/unsloth.Q4_K_M.gguf
PARAMETER stop [INST]
PARAMETER stop [/INST]
TEMPLATE "[INST] {{ .Prompt }} [/INST]"
```

Fix highlighted:
FROM ./finetuned_llama_32_3b_gguf/**unsloth.Q4_K_M.gguf**

**Comment by rtrad89** [comment] 2024-11-21 12:38
I was a similar error when using `"context": 1` in the request, so I replaced it with `"context": [1]` and the error was fixed.
