### ISSUE TITLE
Provide artefact shasums

### ISSUE THREAD

**Issue by jacobwoffenden** [ollama/ollama#3138] opened 2024-03-14 11:05 UTC
Hey 👋

Would it be possible to provide the shasums for releases so we can verify integrity when installing?

Thanks,

Jacob

**Comment by pdevine** [comment] 2024-03-14 19:52
This is a dupe of #1313 . Definitely something we want to do.

**Closed by pdevine** 2024-03-14 19:52 UTC

**Comment by jacobwoffenden** [comment] 2024-03-14 21:22
Ah, sorry! I’m must’ve missed this when I searched for shasum earlier 😅
