### ISSUE TITLE
Toggle theme

### ISSUE THREAD

**Issue by Abubakkar13** [ollama/ollama#8046] opened 2024-12-11 14:03 UTC
Hey,

Could you please add a feature for toggling between dark and light modes to ollama site? It would greatly enhance user experience by allowing customization based on preference and environment. A simple toggle button would be ideal!

**Comment by pdevine** [comment] 2024-12-25 21:51
This is actually a dupe of #1645 . I'm going to go ahead and close it.

**Closed by pdevine** 2024-12-25 21:51 UTC
Labels: feature request, ollama.com
