### ISSUE TITLE
ERROR: llama runner process has terminated: error loading modelvocabulary: _Map_base::at

### ISSUE THREAD

**Issue by CjhHa1** [ollama/ollama#6747] opened 2024-09-11 08:19 UTC
### What is the issue?

I tried the octopus v4 model using ollama, I have constrcted the model using Modelfile, but it can not work when I try to run it.
```
transferring model data 100% 
using existing layer sha256:08fc24194c1805114ed7aefcc8e5cedf7fe1e23b587f1655502afb294263b948 
using existing layer sha256:e49180b1ca46f2ea2a9d652ab44a1ab5dbd5d3f9ed3fd8e985a1122883d580d3 
using existing layer sha256:90bf36950b9123ecc20aa969070a7b3d51bbb782100f0e47b2a2c5f3cf6a24da 
writing manifest 
success 
(base) [root@ip-172-31-81-66 ollama_files]# ollama ls
NAME                            ID              SIZE    MODIFIED       
octopus-v4-Q4_K_M:latest        099ce87bccef    2.4 GB  14 seconds ago
```

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

ollama version is 0.3.6

**Comment by igorschlum** [comment] 2024-09-11 17:21
Hi @CjhHa1 Can you share you modelfile script? Could you also upgrade Ollama to version 0.3.10 and retry to create and use your new LLM?

**Comment by pdevine** [comment] 2024-09-11 18:38
Dupe of #6111

**Closed by pdevine** 2024-09-11 18:38 UTC
Labels: bug

**Comment by CjhHa1** [comment] 2024-09-12 08:14
> Hi @CjhHa1 Can you share you modelfile script? Could you also upgrade Ollama to version 0.3.10 and retry to create and use your new LLM?

```
FROM ./octopus-v4-Q4_K_M.gguf
PARAMETER temperature 0
PARAMETER num_ctx 1024
PARAMETER stop <nexa_end>
```
Just exactly as they mentioned in repo

**Comment by igorschlum** [comment] 2024-09-12 09:14
OK, I will take a look : https://huggingface.co/NexaAIDev/octopus-v4-gguf

**Comment by CjhHa1** [comment] 2025-01-08 16:06
glad to hear that!
