### ISSUE TITLE
The pull rate is slow.

### ISSUE THREAD

**Issue by dashi6174** [ollama/ollama#3943] opened 2024-04-26 13:13 UTC
### What is the issue?

![image](https://github.com/ollama/ollama/assets/1617266/97c13a33-c9d5-4612-9ff3-e572dc5c85d4)

When using the pull command to fetch models, it often slows down significantly towards the end of the download process, while it starts very fast, with speeds of around 70MB/s.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.32

**Comment by taozhiyuai** [comment] 2024-04-27 10:59
just stop and restart pulling. it will speed up. not a problem

**Comment by pdevine** [comment] 2024-04-30 19:18
Dupe of #1736

**Closed by pdevine** 2024-04-30 19:18 UTC
Labels: bug
