### ISSUE TITLE
Inconsistent or unresponsive response in llama v0.1.33 using llava model

### ISSUE THREAD

**Issue by iwannabewater** [ollama/ollama#4171] opened 2024-05-05 14:33 UTC
### What is the issue?

**Environment:**

Operating System: Ubuntu 22.04
Hardware: NVIDIA RTX 4090 GPU and Intel Xeon Gold 6326 CPU
ollama Version: v0.1.33
Model Used: llava:34b-v1.6-q4_0

**Description:**
I am experiencing issues with the llava model in ollama v0.1.33, where it fails to respond appropriately to queries or provides random and unrelated answers. This problem occurs when attempting to analyze images. For example, after running the model and querying about an image (car.jpg), the expected behavior is a detailed description relevant to the image content. However, the model either does not respond or describes content that does not match the image provided.

**Steps to Reproduce:**

Start the model using the command: ollama run llava:34b-v1.6-q4_0
Input commands to describe an image, for example, >>> describe it. the path is: car.jpg
Observe the lack of appropriate response or incorrect descriptions.

**Expected Behavior:**
The model should consistently provide accurate and relevant responses to the image content queries.

**Actual Behavior:**
Responses are either missing, delayed, or incorrect, significantly hindering project progress where image analysis is crucial.

**Additional Context:**
This behavior has been consistently reproducible, impacting our ability to efficiently use the model for critical tasks. Any insights or fixes would be greatly appreciated.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

v0.1.33

**Comment by thinkverse** [comment] 2024-05-05 14:50
Possible duplicate of https://github.com/ollama/ollama/issues/4163, fix is being worked on https://github.com/ollama/ollama/pull/4164.

**Comment by jmorganca** [comment] 2024-05-05 15:16
@iwannabewater sorry this happened. Working on fixing it with a new release very soon. In the meantime I'll close this as a duplicate of #4163

**Closed by jmorganca** 2024-05-05 15:16 UTC
Labels: bug
