### ISSUE TITLE
Problems with using multiple GPUs

### ISSUE THREAD

**Issue by yuwencool** [ollama/ollama#4696] opened 2024-05-29 06:33 UTC
### What is the issue?

When CUDA_VISIBLE_DEVICES=1,2 is used, and Ollama pulls a model, it only uses GPU numbered 1. unless ollama runs another model, GPU numbered 2 will be used. In this way, if Ollama turns on parallelism, parallel reasoning for the same model will only be performed on gpu 1, and the parallel speed is very slow. How can Ollama use multiple GPUs for one model on inference ?

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.38

**Comment by alsavu** [comment] 2024-05-29 18:09
Hello, since this was labeled as a BUG less than 12 hours ago, would it be safe to asume that this issue is still present in version 0.1.3.9 for Windows ?

**Comment by matbee-eth** [comment] 2024-05-31 16:30
I know this may not be what you're looking for but multi-gpu works perfectly fine for me on docker, so if you were to run it on docker it could avoid this issue for you

**Comment by dhiltgen** [comment] 2024-05-31 19:25
Duplicate of #4198

**Closed by dhiltgen** 2024-05-31 19:25 UTC
Labels: bug
