### ISSUE TITLE
GPU RAM not released when exiting ollama run

### ISSUE THREAD

**Issue by aseedb** [ollama/ollama#2235] opened 2024-01-27 21:38 UTC
I'm running ollama version 0.1.22 under Ubuntu and I installed it with the default procedure. After exiting a run using the command /exit the GPU RAM used by ollama is not released immediately. I either need to restart the ollama service, or wait for several minutes for that to occur. Is it an expected behavior?

**Comment by easp** [comment] 2024-01-27 22:52
Sounds like the expected behavior. Ollama unloads the model after 5m of inactivity.

This will be configurable in an upcoming version.

**Comment by jukofyork** [comment] 2024-01-28 20:49
> Sounds like the expected behavior. Ollama unloads the model after 5m of inactivity.
> 
> This will be configurable in an upcoming version.

Unless this has been fixed in the last week or so (currently running 'main' pulled a few days ago), It still seems to hang on to a around 800 to 1500mb of VRAM for me even when the server unloads the model (even many hours after!). It seems to be a leak in the wrapped lllama.cpp server from what I could see.

This can be quite irritating if you push the number of layers offloaded to the limit as it will work fine with the 3mb "freshy crashed" Ollama server but then crash again when switching models and take 30s+ to recover.

**Comment by remy415** [comment] 2024-01-31 01:06
Most AI servers have this problem, I ran into it a lot with stable-diffusion. I would implement frequent server restarts into an application you want to leave running indefinitely.

**Comment by aseedb** [comment] 2024-02-05 16:11
> It still seems to hang on to a around 800 to 1500mb of VRAM for me even when the server unloads the model (even many hours after!).

Same here and yes it would be nice to have it fixed.

**Comment by dhiltgen** [comment] 2024-03-11 19:22
Let's track this via #1848 

We fixed a number of scenarios, but there are still some where GPU memory isn't properly freed when we go idle.

**Closed by dhiltgen** 2024-03-11 19:22 UTC
