### ISSUE TITLE
add support MiniCPM-Llama3-V-2_5

### ISSUE THREAD

**Issue by LDLINGLINGLING** [ollama/ollama#5698] opened 2024-07-15 08:37 UTC
This model is the most powerful multi-modal model I have tried so far. It has a large number of users. However, it is not currently supported by ollama.

**Comment by rick-github** [comment] 2024-07-15 09:00
in progress: https://github.com/ggerganov/llama.cpp/pull/7599

**Comment by pdevine** [comment] 2024-08-28 21:48
dupe of #6417

**Closed by pdevine** 2024-08-28 21:48 UTC
Labels: model request
