### ISSUE TITLE
Is it possible to use the API to pass my documents to the model and have it understand them in depth? 

### ISSUE THREAD

**Issue by robotom** [ollama/ollama#7340] opened 2024-10-24 08:14 UTC
I have a basic front end that talks via the Ollama API. 

Should I just pass the entire document (300+ pages) as a prompt every time? Or is there some better way to do this. 

I want it to know the documents extremely well or as well as possible. 

Is this achievable?

**Comment by rick-github** [comment] 2024-10-24 09:56
Have a look at the RAG solutions in the  [integrations list](https://github.com/ollama/ollama?tab=readme-ov-file#community-integrations).

**Comment by pdevine** [comment] 2024-10-24 18:08
I'm going to close this as a dupe of #5762 . I think it's a cool idea to have something like this in Ollama, but right now it's beyond the scope. As @rick-github mentioned, there are some existing solutions out there that might work.

**Closed by pdevine** 2024-10-24 18:08 UTC
Labels: feature request

**Comment by robotom** [comment] 2024-10-24 23:01
Guess I just want to know, is it recommended to just pass entire walls of text into each prompt? Are there any tunable settings? Or is it just as simple of dumping all the text into the message that I send to the model. 

Thanks!
