### ISSUE TITLE
Windows version "/api/generate" 404 not found

### ISSUE THREAD

**Issue by t41372** [ollama/ollama#2736] opened 2024-02-24 21:59 UTC
<img width="1310" alt="截圖 2024-02-24 下午2 48 29" src="https://github.com/ollama/ollama/assets/36402030/8d1aac17-75f5-4a5c-8f27-a6569db7256c">
<img width="431" alt="截圖 2024-02-24 下午2 54 17" src="https://github.com/ollama/ollama/assets/36402030/99030d6f-9393-4eb5-b617-e04c369fdefe">

The "/api/generate" is not functioning and display 404 on the Windows version (not WSL), despite the Ollama server running and "/" being accessible. The same code works on the Ollama server on my Mac, so I guess the issue is not with my code.

**Comment by xrb12250** [comment] 2024-02-25 00:02
Same happens to me on macOS after several generations... /api/generate ist dead despite the app and server is running... Before it stopped, the GPU load was gradually decreasing and then suddenly drops to 0.

**Comment by jmorganca** [comment] 2024-02-25 04:36
Hi there, 404 can be returned with `POST /api/generate` when the model doesn't exist. Would it be possible to first `ollama pull <model>` to make sure it's available locally?

@xrb12250 sorry about this - would it be possible to share the prompt and model you're using (and if so – would it be possible to open a separate GitHub issue?). Thanks so much - will make sure to look at this.

**Comment by t41372** [comment] 2024-02-25 07:16
I can confirm that the model is available locally.

**Comment by jmorganca** [comment] 2024-02-25 07:59
@t41372 thanks! Does running this powershell script work for you?

```
(Invoke-WebRequest -method POST -Body '{"model":"llama2", "prompt":"Why is the sky blue?", "stream": false}' -uri http://localhost:11434/api/generate ).Content | ConvertFrom-json
```

**Comment by t41372** [comment] 2024-02-25 09:20
<img width="1096" alt="截圖 2024-02-25 上午2 15 36" src="https://github.com/ollama/ollama/assets/36402030/5577c9ce-dc04-4aa0-892e-17ea878c5b8e">
<img width="886" alt="截圖 2024-02-25 上午2 14 39" src="https://github.com/ollama/ollama/assets/36402030/d7462094-888e-4d2f-80e8-72b7edbb68a8">

[app.log](https://github.com/ollama/ollama/files/14395857/app.log)
[server.log](https://github.com/ollama/ollama/files/14395858/server.log)

**Comment by lavahasif** [comment] 2024-02-25 13:27
`Invoke-RestMethod -Uri 'http://localhost:11434/api/generate' -Method Post -Headers @{ 'Content-Type' = 'application/json' } -Body '{"model":"gemma:latest", "prompt":"create a codeigniter form", "stream": false}`

Replace gemma:latest with your model like llama2 or mistral

Or 

Run this in postman 

```
curl --location 'http://localhost:11434/api/generate' \
--header 'Content-Type: text/plain' \
--data '{"model":"gemma:latest", "prompt":"create a codeigniter form", "stream": false}
'
```

**Comment by andrewnguonly** [comment] 2024-03-10 15:11
This issue may also be happening on WSL2 (Ubuntu 22.04.3 LTS) on Windows: https://github.com/andrewnguonly/Lumos/issues/126

**Comment by andrewnguonly** [comment] 2024-03-11 00:00
> This issue may also be happening on WSL2 (Ubuntu 22.04.3 LTS) on Windows: [andrewnguonly/Lumos#126](https://github.com/andrewnguonly/Lumos/issues/126)

False alarm. We did not reproduce this issue.

**Comment by jmorganca** [comment] 2024-03-12 04:34
Hi there, it seems like the model might not be available locally – you can run `ollama pull <model>` to make sure it's available. Will close this for now but feel free to re-open it

**Closed by jmorganca** 2024-03-12 04:34 UTC

**Comment by WiseMarius** [comment] 2024-03-12 07:30
Hi, I have the same issue on windows.
![image](https://github.com/ollama/ollama/assets/25198837/b4baa85e-0bde-449c-a9ac-b10d3354581d)
![image](https://github.com/ollama/ollama/assets/25198837/643fa9d2-c9a5-4395-b26d-6ef49ef5bdef)
![image](https://github.com/ollama/ollama/assets/25198837/30535251-3f80-4dd2-95e8-45893f0ce92b)

**Comment by daudrain** [comment] 2024-03-16 09:05
I got the same issue with Ubuntu 20.04 after running `ollama run codellama:7b` , `/api/generate` was returning 404.
Then I did a `ollama pull codellama` and `/api/generate` returns 200

**Comment by alialili** [comment] 2024-03-17 13:29
got the same issue with MacOS (Sonoma 14.4)...

**Comment by mxyng** [comment] 2024-03-18 07:56
Using a browser to reach `/api/generate` will not work because there is no `GET /api/generate`. Please use curl, postman, etc. which allows you to call `POST /api/generate` with JSON data

**Comment by PhPv** [comment] 2024-04-05 16:26
Hi. I ran into the same problem when I tried to walk through the quickstart from [llamindex](https://docs.llamaindex.ai/en/stable/getting_started/starter_example_local/). Crashes with the error that the api endpoint/chat url was not found http://localhost:11434/api/chat it also says that 404 is not found. (on http://localhost:11434/ i see that "ollama is running".
What am I doing wrong?

**Comment by asma-faraji** [comment] 2024-04-06 18:44
I have the similiar issues as @PhPv . the api/generate return the response but I am getting 404 is not found for api/chat. How can I solve this issue?

**Comment by marctrem** [comment] 2024-04-11 01:36
I ran into the same issue and I was able to get it working.

The issue is that Twinny is attempting to use a model which is not installed. Looks like by default, it wants to use `codellama:7b-code` for FIM and `codellama:7b-instruct` for chat. It's going to attempt this even though those models are not installed.

You can go and modify the Twinny configuration so that it uses a model that you've previously pulled

-or-

You can pull the models that Twinny wants to use.
`ollama pull <model>` and try again. Replace `<model>` by 


The following image shows the initial twinny configuration. It's attempting to use models that I haven't pulled yet.
<img width="503" alt="image" src="https://github.com/ollama/ollama/assets/1619947/38eed2b8-5e25-44d5-a5fd-22537a171350">

**Comment by NtaylorOX** [comment] 2024-04-22 09:55
Any update on this? I have tried installing ollama in multiple places and systems and the api/generate always works, but the api/chat never works - tried multiple models that others report as working. 

ollama version==0.1.8

**Comment by BenBatsir** [comment] 2024-04-25 14:08
any update on this?

I'm getting:
```
[GIN] 2024/04/25 - 16:38:43 | 404 |     408.542µs |       127.0.0.1 | POST     "/api/chat"
```

**Comment by ysfscream** [comment] 2024-04-26 17:25
I encountered this issue until I changed my GET method to a POST method.

**Comment by MustCodeAl** [comment] 2024-04-29 02:12
getting same issue on m1 mac Sonoma 14.4

**Comment by trybonk** [comment] 2024-05-22 19:38
This command helped me solve the 404 error problem
Win11 ollama v0.1.38

> ollama pull <model>

**Comment by Satyam7166-tech** [comment] 2024-05-25 09:54
Hey I have Macos Sonoma 14.5 and I got the same issue.

I tried using Ollama with Llamaindex.

The strange thing is "./ollama run phi3:latest" works absolutely fine in the terminal but `response = query_engine.query("hello")` in llamaindex doesn't where it shows `[GIN] 2024/05/25 - 15:18:34 | 200 | 19.810265083s |       127.0.0.1 | POST     "/api/generate"` in the ./ollama serve terminal tab

I can confirm that the same code worked in Macos Ventura.

**Comment by gustavoarchuby71** [comment] 2024-05-25 15:45
New enviroment, new libraries all work.

Thanks

**Comment by strongbugman** [comment] 2024-05-31 07:21
check your `ollama_api_base` in config/setting and make sure there is no `/` after hostname like `http://localhost:11434/`, this maybe wrong because the finnal api url may become `http://localhost:11434//api/generate`(double slash!) which will return 404 always:
```
❯ curl --location 'http://localhost:11434//api/generate' \
--header 'Content-Type: text/json' \
--data '{"model":"codegemma:latest", "prompt":"say hi to me", "stream": false}
'

404 page not found
```

**Comment by AlmaAROM** [comment] 2024-06-23 07:34
Hi there! 
I'm trying to learn how to connect ollama with crewai or Praison, but it seems is not working at my end. I don't understand how to set up the port. This is what I'm putting inside the console `curl http://localhost:11434api/generate -d '{"model": "openhermes"}'`

the error display is below

curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (3) unmatched close brace/bracket in URL position 11:
openhermes}'

I'm using windows 10... Let me know

**Comment by yurochang** [comment] 2024-07-22 01:41
same problem make graphrag broken for me:

**Comment by smrinalsingh** [comment] 2024-08-18 17:05
> I encountered this issue until I changed my GET method to a POST method.

Exactly. I tried reproducing this issue using python and seems like the requests sent as GET return 404. Changing it to POST did the job.

**Comment by vitustockholm** [comment] 2024-10-14 05:51
Modellife could not exist try to check first : 
`` ollama list `` if its empty, - thats the reason and follow with ,, ``ollama pull modelname`` modelname mistral, llama2 etc. Then it should work, check modelife innstead of base url , because localhost or 127,0,0 should work both if  0,0,0 was whitelisted in envariables

**Comment by vimalamaldas** [comment] 2024-11-16 07:56
Does ollama ps list the model?
If not  Try ollama run <modelname>

**Comment by thrishank007** [comment] 2025-01-08 12:47
use postman or insomnia with POST request, it will work. and make sure you pull model and check if it's there in `ollama list`
url: `http://localhost:11434/api/generate`
data (json): `{
  "model": "qwen2.5-coder:3b",
  "prompt": "Why is the sky blue?",
	"stream": false
}`
method: `POST`
![image](https://github.com/user-attachments/assets/3e86ebbd-a23e-401a-a3c4-9f5933b25e13)
