### ISSUE TITLE
Please add support for Audio models such as Qwen2-Audio

### ISSUE THREAD

**Issue by carlosforster** [ollama/ollama#6367] opened 2024-08-15 01:31 UTC
Please add support to audio files / streams...
so we can use models such as
https://huggingface.co/Qwen/Qwen2-Audio-7B-Instruct

**Comment by goetzc** [comment] 2024-08-17 00:34
Having audio models support in Ollama would be great, not many nice tools support this, AFAIK only [LocalAI](https://localai.io) currently does.

I would like to see OpenAI's [Whisper](https://github.com/openai/whisper), which is open source.

**Comment by pdevine** [comment] 2024-09-02 02:52
Dupe of #3471

**Closed by pdevine** 2024-09-02 02:52 UTC
Labels: feature request
