### ISSUE TITLE
[Website] Allow users to sort models in the library by " (most) recently updated"

### ISSUE THREAD

**Issue by Malrama** [ollama/ollama#5942] opened 2024-07-25 08:13 UTC
Hello everyone and greetings.

It always bugged me, that I am not able to search the Ollama model library by the "most recently updated" model. Currently, it's only possible to search for the newest model in this regard, but this isn't quite the same.

Sometimes I want to look at the library to see if there is an update for the current models I use. Either because it got re-quantized (just as happened with llama 3.1) or a newer version is released. For now, I have to search for that model individually and see, with the "last updated" field, if there is an update for that specific model.

Sorting by "recently updated" would allow me to see all model updated within a timeframe with just 1 click! (since they are chronologically ordered)

![Ollama](https://github.com/user-attachments/assets/d8bbe711-5b43-4677-8488-e1be53857483)

I added this for illustration.
What do you think? Thank you very much.

**Comment by Cephra** [comment] 2024-07-25 16:26
I may be wrong, but I think that the newest filter already shows the most recently updated models.

**Comment by Cephra** [comment] 2024-07-25 16:29
Okay I was wrong, it doesn't sort by recently updated. Nevermind then.

**Comment by pdevine** [comment] 2024-09-17 15:50
Hey @Malrama thanks for the issue. There are a bunch of changes happening to the registry but aren't live yet. I'm going to close this as a dupe of #4596 though.

**Closed by pdevine** 2024-09-17 15:50 UTC
Labels: feature request, ollama.com

**Comment by abitrolly** [comment] 2025-02-07 04:42
@pdevine where is the source for the registry and how it is deployed?
