### ISSUE TITLE
Exception using command-r-plus:104b-q4_0

### ISSUE THREAD

**Issue by mehdiataei** [ollama/ollama#3660] opened 2024-04-15 22:49 UTC
### What is the issue?

Ollama: exception done_getting_tensors: wrong number of tensors; expected 642, got 514

**Comment by park** [comment] 2024-04-16 02:43
Same issue here on Ubuntu w/ 5950x + NVIDIA 2080Ti 22GB + 128GB memory.

**Comment by madroidmaq** [comment] 2024-04-16 03:27
The problem was also encountered on the Apple M3 Max, which reported the following error:

```
ollama run command-r-plus
pulling manifest
pulling 503c8cac166f... 100% ▕███████████████████████████████▏  59 GB
pulling f0624a2393a5... 100% ▕███████████████████████████████▏  13 KB
pulling 42499e38acdf... 100% ▕███████████████████████████████▏  270 B
pulling 36b9655abe6a... 100% ▕███████████████████████████████▏   81 B
pulling 748dd5320e31... 100% ▕███████████████████████████████▏  493 B
verifying sha256 digest
writing manifest
removing any unused layers
success
Error: exception done_getting_tensors: wrong number of tensors; expected 642, got 514
```

PS：ollama version is 0.1.31

**Comment by madroidmaq** [comment] 2024-04-16 05:52
ollama version is 0.1.32 is work for me

**Comment by lunyang** [comment] 2024-04-16 10:41
Try to install `curl -fsSL https://ollama.com/install.sh | OLLAMA_VERSION=0.1.32 sh`, it woks.

**Comment by ai-Ev1lC0rP** [comment] 2024-04-16 15:33
I had the same issue on MBP M2 Max 64GB. Candidly i'm on pre-release OS 14.5 Sonoma. 
Never the less.
I just pulled the latest from the ollama site and it's still on version 1.31, 1.32 is pre-release so you will need to head on over to the releases page. 

But i can confirm @lunyang is right. It's resolved in pre-release version 1.32 as indicated in the docs. 

## on version 0.1.31
`
ollama -v
ollama version is 0.1.31
Warning: client version is 0.0.0
ollama run command-r-plus
Error: exception done_getting_tensors: wrong number of tensors; expected 642, got 514
`

##working on version 0.1.32 % 
```

ollama run command-r-plus
>>> hello how are you?
I  ^C

>>> /bye
ollama -v     
ollama version is 0.1.32
Warning: client version is 0.0.0
```

I think this should be marked as resolved no-issue. 


**As a Note.....This model is *huge* and i'm not expecting it to work well if at all on my m2 Max or my 4090TI/64 gigs of ram. @park  with the 2080 and all the DDRegularram. . . . I think you might be dreaming thinking that will run but i've been wrong many times before. ;) I have a 1TB of DDR4 in a machine WITHOUT a gpu and run dual massive intel cpu's and.... cpu + ddr3/4/5 isnt the same and doesnt translate 1:1 

Good luck everyone!

**Comment by park** [comment] 2024-04-17 00:34
I can confirm that after removing and re-pulling the docker container v0.1.32, and it works alright. The speed is very slow though.

I guess this issue is resolved.

**Comment by jmorganca** [comment] 2024-04-17 00:41
Hi there, command-r-plus requires 0.1.32! Sorry the error message for this isn't more obvious - will improve this in an upcoming release

**Closed by jmorganca** 2024-04-17 00:41 UTC
Labels: bug, needs-triage
