### ISSUE TITLE
RFE: provide checksum for artefacts released

### ISSUE THREAD

**Issue by truatpasteurdotfr** [ollama/ollama#2323] opened 2024-02-02 10:19 UTC
Hi,

would it be possible to provide sha256 checksums/signature to verify the downloaded artefacts when
a new version is released? Just to be sure that the executables have not modified. :D

Thanks

Tru

**Comment by pdevine** [comment] 2024-03-14 19:53
This is a dupe of #1313. We definitely want to do this in the future.

**Closed by pdevine** 2024-03-14 19:53 UTC
Labels: feature request
