### ISSUE TITLE
pull error EOF with gemma2:27b-instruct-q8_0

### ISSUE THREAD

**Issue by rcanand** [ollama/ollama#8088] opened 2024-12-13 14:51 UTC
### What is the issue?

When I call `ollama pull gemma2:27b-instruct-q8_0`, I get error `EOF`. 

I have pulled other models successfully (including other gemma2 models) from the same system. And I have disk space etc. -  running into this issue with just this model.
Based on web search, I suspect the file on the server itself is invalid or corrupted.

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.5.1

**Comment by rcanand** [comment] 2024-12-13 15:22
Thanks, @rick-github - how can I debug this? I am consistently getting this EOF error for just this model - other models are working fine.

**Comment by rick-github** [comment] 2024-12-13 15:34
What does the following return:
```
curl -D - https://registry.ollama.ai/v2/library/gemma2/manifests/27b-instruct-q8_0
```

**Comment by rick-github** [comment] 2024-12-13 15:35
[Server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) might help.

**Comment by rcanand** [comment] 2024-12-13 15:50
Here is the curl output:

```
> curl -D - https://registry.ollama.ai/v2/library/gemma2/manifests/27b-instruct-q8_0
HTTP/2 200
date: Fri, 13 Dec 2024 15:45:00 GMT
content-type: text/plain; charset=utf-8
content-length: 857
via: 1.1 google
alt-svc: h3=":443"; ma=86400
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=mUx6k6nHkDhdKJfxlivkc8FJ4Nn6ds8TDWtZO9rQ%2B1neUiKovyn7OG%2BYl24EDQ23HEoDwXuEiYZbkYClZ5sl9MxELwOm6PsKIzaeC2ocDKgg5PAJG6EK%2Bs1WbnuPnQ6BeijOxyQ%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 8f17142a9e86c399-SEA
server-timing: cfL4;desc="?proto=TCP&rtt=16096&min_rtt=15650&rtt_var=5079&sent=6&recv=10&lost=0&retrans=0&sent_bytes=2881&recv_bytes=607&delivery_rate=151781&cwnd=214&unsent_bytes=0&cid=d22e2a69e67adb02&ts=224&x=0"

{"schemaVersion":2,"mediaType":"application/vnd.docker.distribution.manifest.v2+json","config":{"mediaType":"application/vnd.docker.container.image.v1+json","digest":"sha256:d55baf7df634fde80fa35eb04c670762bc6e7c335c3e0787bd2b199a4f526c2b","size":488},"layers":[{"mediaType":"application/vnd.ollama.image.model","digest":"sha256:1b971f02fb8f2cb34d37f83dcd1d9cc982cb1b3701d0a169e45fcd8fed0750d6","size":28937388256},{"mediaType":"application/vnd.ollama.image.template","digest":"sha256:109037bec39c0becc8221222ae23557559bc594290945a2c4221ab4f303b8871","size":136},{"mediaType":"application/vnd.ollama.image.license","digest":"sha256:097a36493f718248845233af1d3fefe7a303f864fae13bc31a3a9704229378ca","size":8433},{"mediaType":"application/vnd.ollama.image.params","digest":"sha256:2490e7468436707d5156d7959cf3c6341cc46ee323084cfa3fcf30fe76e397dc","size":65}]}%
```

Server logs don't have anything related to this model:

`cat ~/.ollama/logs/server.log | grep 27b-instruct-q8_0` gives no entries.

**Comment by rcanand** [comment] 2024-12-13 15:53
Here is the error  I get:

```
> ollama pull gemma2:27b-instruct-q8_0
pulling manifest
Error: EOF
```

**Comment by rcanand** [comment] 2024-12-13 16:11
This may be relevant: I have overridden OLLAMA_MODELS to point to an external drive in my shell profile. And if I run `ollama serve` and call `ollama pull` the models are saved in the external disk, logs are in default ~/.ollama/logs. And this issue happened in that configuration. 

While debugging this issue, I found that some times I had the ollama app running instead of the shell based server, which did not have the external models location configured. This led to the models being downloaded to the default location ~/.ollama/models - To clean it up, I merge moved everything from ~/.ollama/models into the external drive models folder.

Note:
1. This issue happened before the merge move of models, and I did that only to debug this issue. So the merge itself is not the cause of the issue.
2. This detail may help explain some of the stuff in the logs.

**Comment by rick-github** [comment] 2024-12-13 16:19
The server has never tried to pull 1b971f02fb8f (model weights) or d55baf7df634 (config)  for 27b-instruct-q8_0.

When you merged into the external folder, did you set he ownership of the moved files?  What's the result of:
```
ls -ld $OLLAMA_MODELS/blobs/{,sha256-{1b971f02fb8f,109037bec39c,097a36493f71,2490e7468436,d55baf7df634}*}
```

**Comment by rick-github** [comment] 2024-12-13 16:22
Also
```
ls -ld $OLLAMA_MODELS/manifests/registry.ollama.ai/library/gemma2/27b-instruct-q8_0
cat $OLLAMA_MODELS/manifests/registry.ollama.ai/library/gemma2/27b-instruct-q8_0
```

**Comment by rcanand** [comment] 2024-12-13 16:52
[gemma2_debug_ls_cat_dumps.server.log](https://github.com/user-attachments/files/18129044/gemma2_debug_ls_cat_dumps.server.log)

**Comment by rcanand** [comment] 2024-12-13 17:02
I tried removing the gemma2/27b manifest file referenced in that dump, restarted ollama server, reran pull, but it still gave me the EOF error (so I put it back).

**Comment by rick-github** [comment] 2024-12-13 17:11
So it looks like the pull was started but the server was taken down half way through.  What would normally happen is that when the server restarted, it would go through the failed pulls and delete the orphaned `partial` files.  However, because of all the ._xx files, the server is abandoning any cleanup attempt, and I think the incomplete state causes a new pull to fail.  I would suggest deleting all the ._xx files and restarting the server, and see if the partial files are gone (`ls -l $OLLAMA_MODELS/blobs/sha256-*partial*`).  If they are, try re-pulling 27b-instruct-q8_0.  If not, add the recent logs and see what the new blocker is.

**Comment by rcanand** [comment] 2024-12-13 17:28
Yeah, that worked, thanks! I mean after deleting these ._ files, it started pulling the model (I didn't check for the partial files, just ran pull) - I need to look deeper for a way to make mac stop creating these ._ files.

**Closed** 2024-12-14 16:39 UTC
Labels: bug

**Comment by eschwartz** [comment] 2026-06-08 19:18
I see this issue was closed, but it's not actually fixed. You just found a workaround that requires deleting ollama-internal files.

Can we re-open this issue, so we might get an actual fix?

**Comment by rick-github** [comment] 2026-06-08 19:32
The issue is `corrupt manifests detected, skipping prune operation`.  The ollama server has detected that the manifests are corrupted and doesn't continue with deleting files in case this is a recoverable issue, which the user can deal with.  The actual fix is to not corrupt the manifests.
