### ISSUE TITLE
Codellama70b runs, but Codellama70b-Instruct spins forever after downloading

### ISSUE THREAD

**Issue by ewebgh33** [ollama/ollama#2286] opened 2024-01-31 04:44 UTC
Wondering if this is a config issue or something else? IE are any of the additional model files that are downloaded alongside the 38gb main file, borked in any way?

Ollama is via WSL in windows.

`ollama run codellama:70b`
works and gives me code

`ollama run codellama:70b-instruct`
downloads but has the spinning dots thing and never progresses.
That is to say
Verifies
"removing any unused layers"
"success"
But then nothing. Can't prompt, it just sits here and spins.

Exit and restart, try it again. Already downloaded so it skips re-downloading... but spins again for infinite amount of time.

Since 70b vanilla runs, it can't be memory or GPUs?
I have 2x 4090 and 64gb RAM. Sure 128 would be better but as I said, 70b vanilla runs fine.

Thanks

**Comment by bmizerany** [comment] 2024-03-12 20:25
Are you still seeing this issue with the latest release of Ollama? We are unable to reproduce with a similar environment.

If the issue persists, can you run with `OLLAMA_DEBUG=1` and see if anything stands out in the logs at `~/.ollama/logs`?

**Comment by pdevine** [comment] 2024-07-19 21:39
`codellama:70b-instruct` should be working fine right now. I know the issue was from a while ago, but let's go ahead and close it. We can reopen if you're still seeing problems.

**Closed by pdevine** 2024-07-19 21:39 UTC
Labels: windows, needs more info
