### ISSUE TITLE
qwen2 not run correctly

### ISSUE THREAD

**Issue by FreemanFeng** [ollama/ollama#4890] opened 2024-06-07 02:14 UTC
### What is the issue?

ollama run qwen2
>>> tell a story
GG

OnceGGG thereGGGGGGGGGGGG wasGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG

>>> 讲一个故事
GG

GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG

>>>

Above is what qwen2 model response, not sure if it is ollama not supporting qwen2 yet or not?

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.41

**Comment by slash130** [comment] 2024-06-07 02:22
在linux服务器上遇到相同的问题，在macmini上是正常的。

**Comment by tonightmare** [comment] 2024-06-07 02:22
I meet the same problem with 4090 in ubuntu linux platform

**Comment by freeng** [comment] 2024-06-07 02:29
I meet the same problem
3060 6g
16g ram
windows 11

**Comment by Moeblack** [comment] 2024-06-07 02:31
I meet the same problem on wsl2.
![9b330dc35f2c203d8278807de423842c](https://github.com/ollama/ollama/assets/28835093/4912f714-8223-4131-ab3b-743d540846b0)

**Comment by ajie425** [comment] 2024-06-07 02:42
win11上也出现这种问题
![image](https://github.com/ollama/ollama/assets/40158391/a8102510-fa5c-4d9b-b1a1-b64c228f9e4f)

**Comment by jingyibo123** [comment] 2024-06-07 03:00
Same on linux,

Also, similar bug with `qwen_v1.5` when `num_ctx >2048`, if it's related

**Comment by Forevery1** [comment] 2024-06-07 03:45
一样输出一堆gggggggg

**Comment by Tining123** [comment] 2024-06-07 03:55
./ollama --version
ollama version is 0.1.41

same issue

**Comment by lingyezhixing** [comment] 2024-06-07 04:04
same question

**Comment by HorseLuke** [comment] 2024-06-07 04:26
Seems that if it is run by CPU only, result is normal but run slowly. Using GPU will result such problem.

**Comment by catnaut** [comment] 2024-06-07 05:51
same question

**Comment by vasilhayatov** [comment] 2024-06-07 07:05
i just added this parameter OLLAMA_FLASH_ATTENTION=1 when running ollama serve, and qwen2 worked on my gpu

**Comment by Moeblack** [comment] 2024-06-07 07:22
> i just added this parameter OLLAMA_FLASH_ATTENTION=1 when running ollama serve, and qwen2 worked on my gpu我刚刚在运行 ollama 服务时添加了 OLLAMA_FLASH_ATTENTION=1 参数，结果 qwen2 在我的显卡上正常运行了。

well, succeed.
![image](https://github.com/ollama/ollama/assets/28835093/b97c27f2-ecbb-4cea-97f8-c7931fa584d6)

**Comment by jiangweiatgithub** [comment] 2024-06-07 08:02
This works for me!

**Comment by vincent-guo** [comment] 2024-06-07 08:35
> i just added this parameter OLLAMA_FLASH_ATTENTION=1 when running ollama serve, and qwen2 worked on my gpu

Well done.

**Comment by denijane** [comment] 2024-06-07 10:10
Not working for me with "ollama run". I get "GladGladGlad" (to infinity). And "ollama serve" complains "Error: accepts 0 arg(s), received 1". Any idea what is the problem?

**Comment by denijane** [comment] 2024-06-07 10:41
Yeah, well, my ollama is still 0.1.30 (manjaro) and arch's latest is ollama 0.1.41-1 as far as I can see. I guess the problem is that Manjaro doesn't prioritize ollama imports. Oh well, I'll think of a workaround.

**Comment by dllp007king** [comment] 2024-06-07 10:48
写一个有关于windows用户的详细的解决方案
1.更新你的ollama到最新版本
2.系统找到环境变量中添加一条内容名字为OLLAMA_FLASH_ATTENTION值为1的环境变量
3.重启你的电脑
就解决了必须重启windows
<img width="370" alt="1" src="https://github.com/ollama/ollama/assets/41323573/9eba5b8a-0480-4ea3-b27d-1d0cf5566b97">

![Uploading 2.png…]()

**Comment by dllp007king** [comment] 2024-06-07 10:50
> 写一个有关于windows用户的详细的解决方案 1.更新你的ollama到最新版本 2.系统找到环境变量中添加一条内容名字为OLLAMA_FLASH_ATTENTION值为1的环境变量 3.重启你的电脑 就解决了必须重启windows <img alt="1" width="370" src="https://private-user-images.githubusercontent.com/41323573/337625955-9eba5b8a-0480-4ea3-b27d-1d0cf5566b97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NTc3MjMsIm5iZiI6MTcxNzc1NzQyMywicGF0aCI6Ii80MTMyMzU3My8zMzc2MjU5NTUtOWViYTViOGEtMDQ4MC00ZWEzLWIyN2QtMWQwY2Y1NTY2Yjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDEwNTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMGJkOGQ4NjEzNTQ5OWZhYTg2YjFiOGY2OGQxNzVhZWUxNGFjMGUyMzlhMzYzYzVkOGVlNTgwZDAyZWVhZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RGYwAiDhxlHxyAEFAndz0fpGbMH-Qzw3qNA9ajOeX2M">

<img width="481" alt="2" src="https://github.com/ollama/ollama/assets/41323573/503d69b9-bd3d-472e-a35f-81eabc6b424d">

**Comment by jmorganca** [comment] 2024-06-07 22:57
Hi all sorry about this, it was fixed in Hi all, sorry about this. It is fixed in 0.1.42: https://github.com/ollama/ollama/releases/tag/v0.1.42

**Closed by jmorganca** 2024-06-07 22:57 UTC
Labels: bug
