### ISSUE TITLE
Error: Post "http://127.0.0.1:11434/api/chat": read tcp 127.0.0.1:49192->127.0.0.1:11434: wsarecv: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by yxl23** [ollama/ollama#2971] opened 2024-03-07 05:44 UTC
Error: Post "http://127.0.0.1:11434/api/chat": read tcp 127.0.0.1:49192->127.0.0.1:11434: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by miharekar** [comment] 2024-03-08 10:31
Probably duplicate of #2953

**Comment by jmorganca** [comment] 2024-03-12 02:12
Merging this with #2555

**Closed by jmorganca** 2024-03-12 02:12 UTC

**Comment by Ws612401** [comment] 2024-03-28 10:44
I have the same question，Run gemma:2b is well,but if i create and run a new model by modelfile, the  question appeared
Ollama version : 0.1.29
system：WIN 11 family

**Comment by xiaogu-space** [comment] 2024-09-02 07:59
I have the same question ，ollama run qwen2:7b 
Ollama version : 0.3.6
system：WIN 11
