### ISSUE TITLE
Unable to download model llama3.2-vision:11b and request update ollama.

### ISSUE THREAD

**Issue by Luckyjjjjjjj** [ollama/ollama#7651] opened 2024-11-13 12:49 UTC
### What is the issue?

I download the latest version from https://ollama.com/download and install, but cannot download llama3.2 in setting the model download - vision: 11 b, and suggest to update the ollama, but I have is the latest version, how do I solve

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.4.1

**Comment by rick-github** [comment] 2024-11-13 16:00
Did you restart the ollama server?

**Comment by Luckyjjjjjjj** [comment] 2024-11-14 08:49
I rebooted and checked that the version was 0.4.1 and reported an error

**Comment by rick-github** [comment] 2024-11-14 13:09
What was the error?

**Comment by Luckyjjjjjjj** [comment] 2024-11-15 01:07
The error content is not downloadable and requires me to update to the latest version, which I already have

**Comment by pdevine** [comment] 2024-11-15 01:37
Hey @Luckyjjjjjjj can you run `ollama -v` and paste the contents in the issue? Also, cut/paste the error as well.

**Comment by Luckyjjjjjjj** [comment] 2024-11-16 06:10
> 错误内容不可下载，需要我更新到我已经拥有的最新版本

I started ollama using the open-webui mode. I have selected llama3.2-vision:11b on the web page. When I download ollama, the following error message is displayed:

pull model manifest: 412:  The model you are attempting to pull requires a newer version of Ollama. Please download the latest version at:  https://ollama.com/download



I also checked that my version is the latest 0.4.1

C:\Users\l>ollama -v

ollama version is 0.4.1

**Comment by rick-github** [comment] 2024-11-16 21:39
In open-webui, click on your profile icon (lower left corner or upper right corner, depending on version), click on `Settings`, click on `About`, and see what version of ollama open-webui thinks it is talking to.

![Screenshot from 2024-11-16 22-29-28](https://github.com/user-attachments/assets/1c5f8798-b20f-4ab3-a0ee-203c0f2ba5b4)

**Comment by Luckyjjjjjjj** [comment] 2024-11-17 05:46
> 在 open-webui 中，点击你的个人资料图标（左下角或右上角，取决于版本），点击 ，看看 open-webui 认为它正在与哪个版本的 ollama open-webui 对话。`Settings``About`
> 
> ![Screenshot from 2024-11-16 22-29-28](https://private-user-images.githubusercontent.com/14946854/386878629-1c5f8798-b20f-4ab3-a0ee-203c0f2ba5b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MjI0OTIsIm5iZiI6MTczMTgyMjE5MiwicGF0aCI6Ii8xNDk0Njg1NC8zODY4Nzg2MjktMWM1Zjg3OTgtYjIwZi00YWIzLWEwZWUtMjAzYzBmMmJhNWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA1NDMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMzU5YjY4MzhkN2RmODZmNmE4ZjgxOGJhNzRhMTcyZDY3YWFlOTQwZjdmMTQ4NDBhZDdjMWQ5NjJjN2VkZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9nS4o9tOotGnqlyqhMscvQlCMJE6zNqS0znDqEDnC30)

是的 ，昨天我就发现了在我的webui里它是0.3.41，可是我在cmd中查询的确实0.4.1，请问我该如何让webui中的ollama升级，我找遍了webui中所有的按钮，我找不到升级的地方，对不起我可是个笨蛋

**Comment by rick-github** [comment] 2024-11-17 10:54
You are running two ollama servers.  Are you using a docker image that has an embedded ollama server?

**Comment by Luckyjjjjjjj** [comment] 2024-11-18 08:00
I just downloaded and installed docker and ollama clients on the web page. In cmd, docker run -d -p 3000:8080 --gpus=all -v ollama:/root/.ollama -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:ollama

Then I started the webui

**Comment by rick-github** [comment] 2024-11-18 11:31
The docker image you have installed has an embedded ollama server.  That server is 0.3.14.  You can either wait until the docker image is updated, or you run stand-alone ollama and open-webui services, and configure open-webui to talk to your ollama server.

**Comment by pdevine** [comment] 2024-11-18 18:24
I'll go ahead and close this since it looks like the issue is w/ open-webui. @Luckyjjjjjjj I haven't used open-webui but I think it can run outside of a container?

**Closed by pdevine** 2024-11-18 18:24 UTC
Labels: bug
