### ISSUE TITLE
Ollama v0.1.18+ does not fully unload from GPU when idle

### ISSUE THREAD

**Issue by richginsberg** [ollama/ollama#1848] opened 2024-01-08 00:09 UTC
**OS:** Ubuntu 22.04
**Environment:** Docker/nvidia container
**Server:** Dell Poweredge R720
**GPUs:** Nvidia Tesla P40 24GB
**GPU quantity:** 2
**Model:** any (ie.  dolphin-mixtral:8x7b-v2.5-q6_K)

```
 docker pull ollama/ollama:0.1.17
 docker run -d --gpus=all -v ~/ollama:/root/.ollama -p 11434:11434 --name ollama17 ollama/ollama:0.1.17
 docker exec -it ollama17 ollama run dolphin-mixtral:8x7b-v2.5-q6_K
```

Previous observation on Ollama v0.1.17. When model is loaded VRAM utilization is visible via nvidia-smi a pair of processes are also visible:
`...p/gguf/build/cuda/bin/ollama-runner`
Each process uses 50-150w per GPU while running inference, 50-52w idle but model still loaded. 

![ollama-0 1 17_modelloaded](https://github.com/jmorganca/ollama/assets/819865/ba70bd4a-c13a-42be-8694-ffb67caa0b97)

After a period of idle time, the model is **unloaded**. Both GPUs drop to 10-12w a piece with no visible process running

![ollama-0 1 17_modelunloaded](https://github.com/jmorganca/ollama/assets/819865/1aae0a06-7246-45b9-a8df-20b4ed4b378c)

```
 docker pull ollama/ollama:0.1.18
 docker run -d --gpus=all -v ~/ollama:/root/.ollama -p 11434:11434 --name ollama18 ollama/ollama:0.1.18
 docker exec -it ollama18 ollama run dolphin-mixtral:8x7b-v2.5-q6_K
```

Observation on Ollama v0.1.18. When model is loaded VRAM utilization is visible via nvidia-smi a pair of processes are also visible, but under a different path:
`/bin/ollama`
Each process uses 50-150w per GPU while running inference, 50-52w idle but model still loaded. 

![ollama-0 1 18_modelloaded](https://github.com/jmorganca/ollama/assets/819865/277c883c-34d2-442a-8807-2dcceec13e34)

After a period of idle time, the model is **unloaded**, _but process is still running_. **Both GPUs pull equivalent wattage as idle/model loaded.**

![ollama-0 1 18_modelunloaded](https://github.com/jmorganca/ollama/assets/819865/68ffefb7-c99a-4ad3-b774-450a37c5f308)

The server is powered on 24/7 and tuned to pull 120w w/o GPUs. Ollama is idle 95% of time. Prior, P40s were adding a combined 24w additional power draw idle under v0.1.17. Now with v0.1.18, the P40s adding a combined 110w additional power draw. 86w difference.

Does /bin/ollama need to be running the entire time?

**Comment by dhiltgen** [comment] 2024-01-08 21:11
In 0.1.17 we leveraged a subprocess for the LLM runner accessing the GPU.  After 5min of idle time, that subprocess was terminated, releasing all GPU allocations.  In 0.1.18 we've transitioned to loading the LLM logic in-process, and while we're still unloading after 5min of idle, it looks like there's still some GPU memory allocation that isn't being freed up.

**Comment by jukofyork** [comment] 2024-01-08 22:12
> In 0.1.17 we leveraged a subprocess for the LLM runner accessing the GPU. After 5min of idle time, that subprocess was terminated, releasing all GPU allocations. In 0.1.18 we've transitioned to loading the LLM logic in-process, and while we're still unloading after 5min of idle, it looks like there's still some GPU memory allocation that isn't being freed up.
Yeah, I've noticed this: I can set num_gpu to a very tight value and it works fine when I load the model from a newly created (or newly respawned after OOM), but if I try to swith models then I get OOM error. From looking at nvidia-smile it's the wrapped llama.cpp server that isn't freeing all it's VRAM.

**Comment by dhiltgen** [comment] 2024-01-09 04:23
Digging around a bit more, I believe this is the result of llama.cpp not completely freeing up VRAM resources when the model is freed up. e.g. https://github.com/ggerganov/llama.cpp/issues/3717 

We'll take a look at it, and keep an eye on upstream as well.

**Comment by iplayfast** [comment] 2024-01-10 05:29
Could be the cause of https://github.com/jmorganca/ollama/issues/1691

**Comment by dhiltgen** [comment] 2024-02-18 01:16
With a slight modification to server.cpp and ggml-cuda.cu, I was able to get the upstream server to run under the cuda memory leak checker tool, and was able to find 4 leaks.

```
========= Leaked 8,388,608 bytes at 0x7faf2c000000
=========     Saved host backtrace up to driver entry point at allocation time
=========     Host Frame: [0x2db39f]
=========                in /lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame: [0xc33c3e]
=========                in /usr/local/cuda/lib64/libcublas.so.12
=========     Host Frame: [0xc00373]
=========                in /usr/local/cuda/lib64/libcublas.so.12
=========     Host Frame: [0xc422f5]
=========                in /usr/local/cuda/lib64/libcublas.so.12
=========     Host Frame: [0x8aa9bd]
=========                in /usr/local/cuda/lib64/libcublas.so.12
=========     Host Frame:cublasCreate_v2 [0x7f66f1]
=========                in /usr/local/cuda/lib64/libcublas.so.12
=========     Host Frame:ggml_init_cublas.part.0 in /home/daniel/code/llama.cpp/ggml-cuda.cu:8008 [0x199ee2]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
=========     Host Frame:ggml_init in /home/daniel/code/llama.cpp/ggml.c:2428 [0x159070]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
=========     Host Frame:llama_backend_init in /home/daniel/code/llama.cpp/llama.cpp:11191 [0xf1f8e]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
=========     Host Frame:main in /home/daniel/code/llama.cpp/examples/server/server.cpp:2546 [0x25093]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
=========     Host Frame:__libc_start_call_main in ../sysdeps/nptl/libc_start_call_main.h:58 [0x29d90]
=========                in /lib/x86_64-linux-gnu/libc.so.6
=========     Host Frame:__libc_start_main in ../csu/libc-start.c:379 [0x29e40]
=========                in /lib/x86_64-linux-gnu/libc.so.6
=========     Host Frame:_start [0x2e345]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
========= 
========= Leaked 1,024 bytes at 0x7faf2dc00000
=========     Saved host backtrace up to driver entry point at allocation time
=========     Host Frame: [0x2db39f]
=========                in /lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame: [0xc33c3e]
=========                in /usr/local/cuda/lib64/libcublas.so.12
=========     Host Frame: [0xc00373]
=========                in /usr/local/cuda/lib64/libcublas.so.12
=========     Host Frame: [0xc422f5]
=========                in /usr/local/cuda/lib64/libcublas.so.12
=========     Host Frame: [0x8aa9bd]
=========                in /usr/local/cuda/lib64/libcublas.so.12
=========     Host Frame: [0x8aa20b]
=========                in /usr/local/cuda/lib64/libcublas.so.12
=========     Host Frame:cublasCreate_v2 [0x7f66f1]
=========                in /usr/local/cuda/lib64/libcublas.so.12
=========     Host Frame:ggml_init_cublas.part.0 in /home/daniel/code/llama.cpp/ggml-cuda.cu:8008 [0x199ee2]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
=========     Host Frame:ggml_init in /home/daniel/code/llama.cpp/ggml.c:2428 [0x159070]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
=========     Host Frame:llama_backend_init in /home/daniel/code/llama.cpp/llama.cpp:11191 [0xf1f8e]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
=========     Host Frame:main in /home/daniel/code/llama.cpp/examples/server/server.cpp:2546 [0x25093]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
=========     Host Frame:__libc_start_call_main in ../sysdeps/nptl/libc_start_call_main.h:58 [0x29d90]
=========                in /lib/x86_64-linux-gnu/libc.so.6
=========     Host Frame:__libc_start_main in ../csu/libc-start.c:379 [0x29e40]
=========                in /lib/x86_64-linux-gnu/libc.so.6
=========     Host Frame:_start [0x2e345]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
========= 
========= Leaked 131,072 bytes at 0x7faf2dc00400
=========     Saved host backtrace up to driver entry point at allocation time
=========     Host Frame: [0x2db39f]
=========                in /lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame: [0xc33c3e]
=========                in /usr/local/cuda/lib64/libcublas.so.12
=========     Host Frame: [0xc00373]
=========                in /usr/local/cuda/lib64/libcublas.so.12
=========     Host Frame: [0xc422f5]
=========                in /usr/local/cuda/lib64/libcublas.so.12
=========     Host Frame: [0x8aa9bd]
=========                in /usr/local/cuda/lib64/libcublas.so.12
=========     Host Frame: [0x8aa22e]
=========                in /usr/local/cuda/lib64/libcublas.so.12
=========     Host Frame:cublasCreate_v2 [0x7f66f1]
=========                in /usr/local/cuda/lib64/libcublas.so.12
=========     Host Frame:ggml_init_cublas.part.0 in /home/daniel/code/llama.cpp/ggml-cuda.cu:8008 [0x199ee2]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
=========     Host Frame:ggml_init in /home/daniel/code/llama.cpp/ggml.c:2428 [0x159070]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
=========     Host Frame:llama_backend_init in /home/daniel/code/llama.cpp/llama.cpp:11191 [0xf1f8e]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
=========     Host Frame:main in /home/daniel/code/llama.cpp/examples/server/server.cpp:2546 [0x25093]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
=========     Host Frame:__libc_start_call_main in ../sysdeps/nptl/libc_start_call_main.h:58 [0x29d90]
=========                in /lib/x86_64-linux-gnu/libc.so.6
=========     Host Frame:__libc_start_main in ../csu/libc-start.c:379 [0x29e40]
=========                in /lib/x86_64-linux-gnu/libc.so.6
=========     Host Frame:_start [0x2e345]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
========= 
========= Leaked 2,097,152 bytes at 0x4ea000000
=========     Saved host backtrace up to driver entry point at allocation time
=========     Host Frame: [0x2e90ad]
=========                in /lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame:ggml_cuda_pool_malloc_vmm(int, unsigned long, unsigned long*) in /home/daniel/code/llama.cpp/ggml-cuda.cu:7834 [0x1b2e12]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
=========     Host Frame:ggml_cuda_op_mul_mat(ggml_tensor const*, ggml_tensor const*, ggml_tensor*, void (*)(ggml_tensor const*, ggml_tensor const*, ggml_tensor*, char const*, float const*, char const*, float*, long, long, long, long, CUstream_st*), bool) in /home/daniel/code/llama.cpp/ggml-cuda.cu:9398 [0x1b4004]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
=========     Host Frame:ggml_cuda_compute_forward.part.0 in /home/daniel/code/llama.cpp/ggml-cuda.cu:10632 [0x19a3f5]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
=========     Host Frame:ggml_backend_cuda_graph_compute(ggml_backend*, ggml_cgraph*) in /home/daniel/code/llama.cpp/ggml-cuda.cu:11323 [0x19a862]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
=========     Host Frame:ggml_backend_sched_graph_compute in /home/daniel/code/llama.cpp/ggml-backend.c:1583 [0x179330]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
=========     Host Frame:llama_decode_internal(llama_context&, llama_batch) in /home/daniel/code/llama.cpp/llama.cpp:7722 [0xf8eed]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
=========     Host Frame:llama_decode in /home/daniel/code/llama.cpp/llama.cpp:12287 [0xf9aa3]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
=========     Host Frame:llama_init_from_gpt_params(gpt_params&) in /home/daniel/code/llama.cpp/common/common.cpp:1361 [0xd8e6d]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
=========     Host Frame:llama_server_context::load_model(gpt_params const&) in /home/daniel/code/llama.cpp/examples/server/server.cpp:383 [0x8024d]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
=========     Host Frame:main in /home/daniel/code/llama.cpp/examples/server/server.cpp:2669 [0x262d4]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
=========     Host Frame:__libc_start_call_main in ../sysdeps/nptl/libc_start_call_main.h:58 [0x29d90]
=========                in /lib/x86_64-linux-gnu/libc.so.6
=========     Host Frame:__libc_start_main in ../csu/libc-start.c:379 [0x29e40]
=========                in /lib/x86_64-linux-gnu/libc.so.6
=========     Host Frame:_start [0x2e345]
=========                in /home/daniel/code/llama.cpp/build/./bin/server
========= 
========= LEAK SUMMARY: 10617856 bytes leaked in 4 allocations
========= ERROR SUMMARY: 4 errors
```

The first 3 are all the same call site and the fix is pretty straight forward.  We just need to add a call to `cublasDestroy` at shutdown of the server.

I haven't quite figured out the last one yet thought.

**Comment by fomalsd** [comment] 2024-02-24 16:17
Hi @dhiltgen! I think this one might not be fully fixed as of version `0.1.27`.

I am also running an Nvidia P40 on Linux and still see around 50w of GPU usage and around 230mb of GPU memory occupied after the chat session is stopped and in idle mode.

The only thing that helps fully unload the GPU is restarting the service manually by calling `sudo service ollama restart`.

Here is the `nvidia-smi` output after the session has been closed and server was idle for a while (over 5 minutes):
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla P40                      On  | 00000000:01:00.0 Off |                  Off |
| N/A   57C    P0              53W / 175W |    240MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A       825      G   /usr/lib/xorg/Xorg                            4MiB |
|    0   N/A  N/A   1670919      C   /usr/local/bin/ollama                       234MiB |
+---------------------------------------------------------------------------------------+
```

and here is another output after forcefully restarting the service:
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla P40                      On  | 00000000:01:00.0 Off |                  Off |
| N/A   44C    P8              10W / 175W |      4MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A       825      G   /usr/lib/xorg/Xorg                            4MiB |
+---------------------------------------------------------------------------------------+
```

**OS**: Debian 12
**Environment**: Bare metal
**GPUs**: 1x Nvidia Tesla P40 24GB
**Other hardware**: Intel 8gen B360 mobo + i5 8600, 16gb DDR4
**Model**: any (e.g. miqu-1-70b.q2_K)

Please let me know if I can be of any help

**Comment by dhiltgen** [comment] 2024-02-26 16:57
Due to the way llama.cpp allocates memory on VMM vs. non-VMM cards, the fix seems to only be complete on VMM cards.  I've opened a new issue #2767 to track fixing this for non-VMM GPUs.

**Comment by fomalsd** [comment] 2024-02-29 09:46
Actually I don't think this fix is complete for VMM either - tried this in Docker+Nvidia Container like the original poster did and still getting idle GPU usage on 0.1.27:

```
docker pull ollama/ollama:0.1.27
docker run -d --gpus=all -v ~/ollama:/root/.ollama -p 11434:11434 --name ollama-27 ollama/ollama:0.1.27
docker exec -it ollama-27 ollama run dolphin-mixtral
```

When model is loaded and active:
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla P40                      On  | 00000000:01:00.0 Off |                  Off |
| N/A   48C    P0              58W / 175W |  22688MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A       828      G   /usr/lib/xorg/Xorg                            4MiB |
|    0   N/A  N/A    177482      C   /bin/ollama                               22682MiB |
+---------------------------------------------------------------------------------------+
```

After 5 minutes of inactivity:
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla P40                      On  | 00000000:01:00.0 Off |                  Off |
| N/A   54C    P0              53W / 175W |    238MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A       828      G   /usr/lib/xorg/Xorg                            4MiB |
|    0   N/A  N/A    177482      C   /bin/ollama                                 232MiB |
+---------------------------------------------------------------------------------------+
```

While the older v0.1.17 fully unloads when idle, consistent with @richginsberg's initial report.

**Comment by dhiltgen** [comment] 2024-03-20 16:17
This should be resolved by #3218

**Comment by richginsberg** [comment] 2024-04-01 19:54
> This should be resolved by #3218

Just tested v0.1.30, the issue is still present.

![ollama-p40-issues-2](https://github.com/ollama/ollama/assets/819865/22751e8b-5af7-445a-bb5f-a7e6291a607f)

**Comment by chereszabor** [comment] 2024-04-02 13:14
> > This should be resolved by #3218
> 
> Not fixed for me. Before updating, ollama didn't use any (significant, at least) memory on startup. Now, the instance mapped to my 1080 Ti (11 GiB) is using 136 MiB and the instances mapped to my 1070 Ti's (8 GiB) are using 100 MiB each. This is before loading any models. Not too cool. Restarting flushes memory, but then refills

To clarify, there is a new failure mode, in v0.1.30. In previous versions, the ollama process would unload model and then the process persisted in GPU memory until restart of the ollama process/docker container. In v0.1.30, ollama also loads itself into memory after restart. This makes things more challenging as in the case of a card like Telsa P40, there is continuous 50W draw from the card on an idle system.

**Closed** 2024-04-02 17:49 UTC
Labels: bug

**Comment by richginsberg** [comment] 2024-04-02 17:54
Above I confirmed the issue persists in v0.1.30. To confirm is wasn't new from v0.1.30, I tried in v0.1.29. Same issue.

`docker run -d --gpus=all -v /home/username/ollama:/root/.ollama -p 11434:11434 --name ollama29 ollama/ollama:0.1.29`

![Screenshot 2024-04-02 at 1 51 11 PM](https://github.com/ollama/ollama/assets/819865/9721ac42-a988-4cc9-89fb-c08216749e81)

**Comment by fomalsd** [comment] 2024-04-02 18:51
I guess we'd all have to check the future version 0.1.31 since the fix was only merged like an hour ago :)

**Comment by raldone01** [comment] 2024-04-13 10:01
I just tested with 0.1.31 and my P40s are still affected. With 0.1.17 the gpus get released properly.

**Comment by fomalsd** [comment] 2024-04-15 09:40
Fixed for me in ollama/ollama:0.1.32. Thanks a bunch!

**Comment by dhiltgen** [comment] 2025-02-22 18:21
A lot has changed in the system since 0.1.27.  @NicolasThierion can you open a new issue with the latest release (0.5.11 as of today) and include some more details about your setup.  Server logs showing a model load, and then unload, `ollama ps` confirming no model is still loaded, and `nvidia-smi` output showing which process is still on the GPU - these will all help us narrow down what is keeping the GPU active.

**Comment by ccebelenski** [comment] 2025-03-04 05:42
This is happening for me too.  4060 TI, latest docker release.  Model will not unload, even after a 'stop'.  (Also have the bug where I can't use all my GPU's for GGUFs - it just gives gibberish)
```
632b564f1dbc473dac52f7819349ceb3cc76d268dee91f762fe2 duration=1h15m0s

time=2025-03-04T05:28:13.802Z level=DEBUG source=sched.go:358 msg="after processing request finished event" modelPath=/root/.ollama/models/blobs/sha256-04381ade8b69632b564f1dbc473dac52f7819349ceb3cc76d268dee91f762fe2 refCount=0

time=2025-03-04T05:28:24.043Z level=DEBUG source=gpu.go:391 msg="updating system memory data" before.total="110.3 GiB" before.free="104.9 GiB" before.free_swap="861.7 MiB" now.total="109.6 GiB" now.free="104.1 GiB" now.free_swap="853.2 MiB"

initializing /usr/lib/x86_64-linux-gnu/libcuda.so.570.86.15

dlsym: cuInit - 0x7f5effd0de00

dlsym: cuDriverGetVersion - 0x7f5effd0de20

dlsym: cuDeviceGetCount - 0x7f5effd0de60

dlsym: cuDeviceGet - 0x7f5effd0de40

dlsym: cuDeviceGetAttribute - 0x7f5effd0df40

dlsym: cuDeviceGetUuid - 0x7f5effd0dea0

dlsym: cuDeviceGetName - 0x7f5effd0de80

dlsym: cuCtxCreate_v3 - 0x7f5effd0e120

dlsym: cuMemGetInfo_v2 - 0x7f5effd0e8a0

dlsym: cuCtxDestroy - 0x7f5effd6c9f0

calling cuInit

calling cuDriverGetVersion

raw version 0x2f30

CUDA driver version: 12.8

calling cuDeviceGetCount

device count 1

[GIN] 2025/03/04 - 05:32:51 | 200 |     126.313µs |      172.17.0.1 | HEAD     "/"

[GIN] 2025/03/04 - 05:32:51 | 200 |     387.452µs |      172.17.0.1 | GET      "/api/ps"

[GIN] 2025/03/04 - 05:33:21 | 200 |      64.413µs |      172.17.0.1 | HEAD     "/"

[GIN] 2025/03/04 - 05:33:21 | 200 |     107.261µs |      172.17.0.1 | GET      "/api/ps"

[GIN] 2025/03/04 - 05:33:34 | 200 |      46.424µs |      172.17.0.1 | HEAD     "/"

[GIN] 2025/03/04 - 05:33:34 | 200 |       4.661ms |      172.17.0.1 | POST     "/api/generate"

time=2025-03-04T05:33:34.669Z level=DEBUG source=sched.go:361 msg="runner expired event received" modelPath=/root/.ollama/models/blobs/sha256-04381ade8b69632b564f1dbc473dac52f7819349ceb3cc76d268dee91f762fe2

time=2025-03-04T05:33:34.669Z level=DEBUG source=sched.go:376 msg="got lock to unload" modelPath=/root/.ollama/models/blobs/sha256-04381ade8b69632b564f1dbc473dac52f7819349ceb3cc76d268dee91f762fe2
``` 
$ ollama ps
NAME                              ID              SIZE      PROCESSOR    UNTIL       
phi3.5:3.8b-mini-instruct-fp16    b78c17e40920    9.1 GB    100% GPU     Stopping...    

```
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            2535      C   /opt/venv/bin/python3                   118MiB |
|    0   N/A  N/A           42705      C   /bin/ollama                              10MiB |
|    0   N/A  N/A           42774      C   /usr/bin/ollama                        8130MiB |
+-----------------------------------------------------------------------------------------+

``` 

Python is unrelated.  Interesting I just noticed two paths to ollama image.  I wonder how that occurs?

**Comment by dhiltgen** [comment] 2025-03-06 00:04
@ccebelenski you didn't mention what ollama version you were running.  Models failing to unload and getting stuck in the "stopping..." state is likely caused by a race somewhere in the code.  We've fixed bugs in this area over the past few months and haven't seen recent reports.  Please make sure you're running the latest version, and if you have a repro, please open a new issue.  Also see #8178
