### ISSUE TITLE
Ollama working issue

### ISSUE THREAD

**Issue by noisyboy22** [ollama/ollama#5561] opened 2024-07-09 04:40 UTC
### What is the issue?

I have installed ollama in my system and its running in the background but while downloading and running the models there is some issue, I am unable to pull or run any model in my windows system.
This are the two error messages that was shown while trying to downloading any model in both  administrator cmd and command prompt I tried:
1)Error: pull model manifest: Get "[https://registry.ollama.ai/v2/library/gemma2/manifests/latest":](https://registry.ollama.ai/v2/library/gemma2/manifests/latest%22:)
net/http: TLS handshake timeout
2)'D:ollama' is not recognized as an internal or external command,
operable program or batch file.

### OS

Windows

### GPU

Intel

### CPU

Intel

### Ollama version

0.1.48

**Comment by pdevine** [comment] 2024-09-17 15:58
Hi @noisyboy22 . Thanks for this issue. I believe 1. is a dupe of #3786 

For 2., make sure you have the full path to the ollama executable.

**Closed by pdevine** 2024-09-17 15:58 UTC
Labels: bug
