### ISSUE TITLE
Error: llama runner process has terminated: exit status 0xc0000135

### ISSUE THREAD

**Issue by balaji1732000** [ollama/ollama#6554] opened 2024-08-29 12:16 UTC
### What is the issue?

I followed the below document to run the ollama model in GPU using Intel IPEX

https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/ollama_quickstart.md

https://www.intel.com/content/www/us/en/content-details/826081/running-ollama-with-open-webui-on-intel-hardware-platform.html

I couldn't get the inference from the model.

Error: llama runner process has terminated: exit status 0xc0000135
can anyone solve the issue

### OS

Windows

### GPU

Intel

### CPU

Intel

**Comment by devskale** [comment] 2024-08-29 12:49
on Oracle Cloud Instance with Ampere CPU


OLLAMA_DEBUG=1 ./ollama run gemma2:2b
Error: llama runner process has terminated: exit status 127

architecture:
Linux ampere aarch64
Operating System: Ubuntu 24.04 LTS
          Kernel: Linux 6.8.0-1011-oracle

**Comment by rick-github** [comment] 2024-08-29 13:05
You need to set `OLLAMA_DEBUG=1` in the server environment, not the client.
```
OLLAMA_DEBUG=1 ./ollama serve
```

**Comment by SlOrbA** [comment] 2024-08-30 07:32
time=2024-08-30T10:30:16.625+03:00 level=INFO source=sched.go:450 msg="loaded runners" count=1
time=2024-08-30T10:30:16.625+03:00 level=INFO source=server.go:591 msg="waiting for llama runner to start responding"
/tmp/ollama1044695914/runners/cpu/ollama_llama_server: error while loading shared libraries: libllama.so: cannot open shared object file: No such file or directory
time=2024-08-30T10:30:16.625+03:00 level=INFO source=server.go:625 msg="waiting for server to become available" status="llm server error"
time=2024-08-30T10:30:16.876+03:00 level=ERROR source=sched.go:456 msg="error loading llama server" error="llama runner process has terminated: exit status 127"

To me it looks like that the missing libllama.so trips the model loading.

**Comment by pdevine** [comment] 2024-09-01 23:20
This looks like a dupe of #6541 which should be fixed now.

**Closed by pdevine** 2024-09-01 23:20 UTC
Labels: bug
