### ISSUE TITLE
Error: pull model manifest: Get "https://ollama.com/token?nonce=6xXg08tJu5sXzjqrvWKxQA&scope=repository%!A(MISSING)library%!F(MISSING)llama2%!A(MISSING)pull&service=ollama.com&ts=1710652958": read tcp 192.168.5.215:60112->34.120.132.20:443: read: connection reset by peer

### ISSUE THREAD

**Issue by wbsxhh201771** [ollama/ollama#3191] opened 2024-03-17 05:32 UTC
when i  run  :
`ollama run llama2`

I ment this problems:
`Error: pull model manifest: Get "https://ollama.com/token?nonce=6xXg08tJu5sXzjqrvWKxQA&scope=repository%!A(MISSING)library%!F(MISSING)llama2%!A(MISSING)pull&service=ollama.com&ts=1710652958": read tcp 192.168.5.215:60112->34.120.132.20:443: read: connection reset by peer.
`
i tried it on windows and  unbuntu .also met this problems .and i close the vpn and firewall ,but it doesn't work.

**Comment by dhiltgen** [comment] 2024-03-20 08:58
Looks similar to #2448 (maybe a dup)

Our best guess at this point is some sort of external firewall causing networking problems.

**Comment by chopeen** [comment] 2024-03-28 13:00
Downgrading Ollama may be a workaround, see https://github.com/ollama/ollama/issues/2448#issuecomment-2025126526.

**Comment by BruceMacD** [comment] 2024-03-28 18:09
I encountered this today and saw this error in the server-side logs:
```
time=2024-03-28T13:58:39.741-04:00 level=INFO source=images.go:1199 msg="request failed: Get \"https://registry.ollama.ai/v2/library/tinyllama/manifests/latest\": read tcp 192.168.13.70:60740->172.64.80.1:443: read: can't assign requested address"
```

**Comment by mxyng** [comment] 2024-03-28 20:52
duplicate of #3112

**Closed by mxyng** 2024-03-28 20:52 UTC
Labels: networking

**Comment by wbsxhh201771** [comment] 2024-03-29 00:01
> Downgrading Ollama may be a workaround, see https://github.com/ollama/ollama/issues/2448#issuecomment-2025126526.

thank you every much bro。now i Slovethe problem

**Comment by uxhao-o** [comment] 2025-02-08 10:59
This problem maybe induce by proxy. I have meet this issue when I used ClashVerge on my macbook. Now I have solved this issue by starting TUN mode in ClashVerge. 

<img width="653" alt="Image" src="https://github.com/user-attachments/assets/483d67e4-4ad3-42f8-ba16-db687dacafe6" />
