### ISSUE TITLE
Ollama GPU not loding properly

### ISSUE THREAD

**Issue by tankvpython** [ollama/ollama#4995] opened 2024-06-12 07:01 UTC
### What is the issue?

I am facing an issue with the Ollama service. I have an **RTX 4090 GPU** with 80GB of RAM and 24GB of VRAM. When I run the Llama 3 70B model and ask it a question, it initially loads on the GPU, but after 5-10 seconds, it shifts entirely to the CPU. This causes the response time to be slow. Please provide me with a solution for this. Thank you in advance.

Note:- GPU load is 6-12 % and CPU load is 70% .

### OS

Windows

### GPU

Nvidia

### CPU

Intel

### Ollama version

v0.1.43

**Comment by phong-phuong** [comment] 2024-06-12 09:28
Your GPU has too little VRAM to run a 70 billion parameter model entirely on the GPU. Try a smaller model like a 22 billion parameter model.

**Comment by tankvpython** [comment] 2024-06-12 09:43
> Your GPU has too little VRAM to run a 70 billion parameter model entirely on the GPU. Try a smaller model like a 22 billion parameter model.

if you have any idea what is configuration needed ?

**Comment by phong-phuong** [comment] 2024-06-12 09:50
See https://huggingface.co/TheBloke/Llama-2-70B-Chat-GPTQ/discussions/2
A user used a 48GB card to run a 70b model.

**Comment by tankvpython** [comment] 2024-06-13 06:48
> Hi @tankvpython sorry about this – I have a similar system and it should definitely be partially loading the 70B model to GPU – would it be possible to check with `ollama ps` after loading a model?

Yes i am able to do this i will check it

**Comment by phong-phuong** [comment] 2024-06-13 17:03
If you are using the standard ollama3:70b version, that one is 4bit quant and uses 40GB VRAM which offloads a lot more than your GPU can handle. 
You can try a lower quant like the 2bit one which uses 26GB, much more suitable for a 24GB card : `ollama run llama3:70b-instruct-q2_K`.

**Comment by tankvpython** [comment] 2024-06-13 18:50
> If you are using the standard ollama3:70b version, that one is 4bit quant and uses ~33GB VRAM which is a lot more than your GPU can handle. When that happens, the rest of the model gets offloaded to the CPU which is much slower. If you want faster interference times, you can try a lower quant like the 2bit one which uses ~17GB, much more suitable for a 24GB card : `ollama run llama3:70b-instruct-q2_K`. Just bear in mind, that lowering the quant size may degrade the quality of the answers (think of it like compressing an image or video).

thanks for help i don't need light weight model because of i need more accuracy

**Comment by dhiltgen** [comment] 2024-09-05 22:12
I think we can close this one as it seems the system is behaving as intended.  `ollama ps` will show the model is loading split between CPU and GPU, which will result in slower performance, bottlenecked by the CPU.

**Closed by dhiltgen** 2024-09-05 22:12 UTC
Labels: question, performance
