### ISSUE TITLE
Support for Min_p

### ISSUE THREAD

**Issue by twalderman** [ollama/ollama#2344] opened 2024-02-04 04:53 UTC
I would like to have min_p as a ollama modelfile parameter.  

See the link for context of this request: https://www.reddit.com/r/LocalLLaMA/comments/17vonjo/your_settings_are_probably_hurting_your_model_why/

**Comment by mherrmann3** [comment] 2024-02-22 09:36
Duplicate of #1142 (corresponding PR: #1825)

**Comment by BruceMacD** [comment] 2024-03-11 18:28
Thanks for the request @twalderman, just resolving this one for now to keep things organized in the the one issue mentioned above.

**Closed by BruceMacD** 2024-03-11 18:28 UTC
Labels: feature request
