### ISSUE TITLE
Models are sometimes lost

### ISSUE THREAD

**Issue by iplayfast** [ollama/ollama#1478] opened 2023-12-12 06:14 UTC
This has happened before, and I don't know what causes it. (I'm using autogen and litellm)
ollama stalled, with my application and ended up with a timeout error.

I realized there were some defunct processes so I syscontrol stop ollama and killed every instance of ollama I could find. 
Upon starting it again, it didn't have the models.

The last time it happened, I believe a reboot brought everything back.

**Comment by BruceMacD** [comment] 2023-12-12 16:55
This is unexpected, thanks for reporting. It looks like you are on Linux. When Ollama fails with the timeout and you restart it are you starting `ollama serve` or the systemctl service? Ollama runs in different contexts between those two scenarios (as the current user when using `ollama server` and as an `ollama` user when run by systemctl). So it is possible it is looking at different model directories in those cases. Next time it happens take a if you're running ollama the same way when it is restarted.

As an aside, I'll try to reproduce the timeout.

**Comment by iplayfast** [comment] 2023-12-13 07:57
I am on linux, I believe this time I used systemctl

**Comment by pdevine** [comment] 2024-03-12 01:31
If you switched between `ollama serve` and `systemctl` your models will definitely be in two separate places. You can use the `OLLAMA_MODELS` env variable to point to the correct place and your models should show up again.

I'm going to go ahead and close the issue, but feel free to keep commenting or reopen it if you're still having problems.

**Closed by pdevine** 2024-03-12 01:31 UTC
Labels: bug

**Comment by FengXiaoGu** [comment] 2024-05-08 01:56
Sometimes lost also in Win
