### ISSUE TITLE
Phi-3 Vision

### ISSUE THREAD

**Issue by ddpasa** [ollama/ollama#4591] opened 2024-05-23 14:49 UTC
Phi-3 is already supported, so I hope this should not be too difficult:

https://huggingface.co/microsoft/Phi-3-vision-128k-instruct

**Comment by Replikate648** [comment] 2024-05-23 19:46
Is Phi-3-vision still have to be added in ollama?

**Comment by TadayukiOkada** [comment] 2024-05-24 03:50
https://github.com/ggerganov/llama.cpp/issues/7444

**Comment by HaoHoo** [comment] 2024-05-28 07:49
Looks like that llama.cpp convert HF to GGUF code can't support Phi3V yet.

**Comment by pdevine** [comment] 2024-06-05 20:36
Going to close this as a dupe.

**Closed by pdevine** 2024-06-05 20:36 UTC
Labels: model request

**Comment by levicki** [comment] 2024-09-15 13:06
@pdevine Can you please clarify whether Phi3-vision is supported or not? If yes, what is the proper template for it?

**Comment by pdevine** [comment] 2024-09-15 14:20
@levicki Unfortunately not yet. The dupe was to track it in #4560

**Comment by levicki** [comment] 2024-09-15 19:41
> @levicki Unfortunately not yet. The dupe was to track it in #4560

Thanks for the clarification. I am confused as to what the problem is with supporting that model? There's also a newer version (3.5) that came out in the meantime. Didn't llama.cpp already add support for it? Or is there perhaps some other issue with it?
