### ISSUE TITLE
Error: unmarshal

### ISSUE THREAD

**Issue by hemanth** [ollama/ollama#2293] opened 2024-01-31 22:30 UTC
Noticing a `Error: unmarshal: invalid character 'p' after top-level value` on `ollama run llava`

<img width="923" alt="image" src="https://github.com/ollama/ollama/assets/18315/84f04d3e-a64e-4da5-9131-20ccf56cdeca">

`client version is 0.1.22`

**Comment by hemanth** [comment] 2024-02-03 06:46
```
❯ ollama --version
Warning: could not connect to a running Ollama instance
Warning: client version is 0.1.23
```

```
❯ ollama run llava
Error: unmarshal: invalid character 'p' after top-level value
```

**Comment by mogest** [comment] 2024-02-06 06:19
I'm getting the same from a completely fresh install and wiped `~/.ollama` directory.

Installed on MacOS Sonoma 14.2.1, from download using the link on the GitHub README, onto a Mac M1 Max 32 GB.

Also tried the `brew` install, same result.

```
> ollama run mistral
pulling manifest
pulling e8a35b5937a5... 100% ▕█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ 4.1 GB
pulling 43070e2d4e53... 100% ▕█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  11 KB
pulling e6836092461f... 100% ▕█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏   42 B
pulling ed11eda7790d... 100% ▕█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏   30 B
pulling f9b1e3196ecf... 100% ▕█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  483 B
verifying sha256 digest
writing manifest
removing any unused layers
success
Error: unmarshal: invalid character 'p' after top-level value
```

**Comment by mogest** [comment] 2024-02-06 07:59
Problem only seems to have started in 0.1.21.  0.1.20 functions correctly.

**Comment by terminalkitten** [comment] 2024-02-26 23:53
In my case this issue was fixed after restarting:

`brew services start ollama` or `brew services start ollama`

**Comment by bmizerany** [comment] 2024-03-11 23:14
`ollama run llava` is working on the latest release of Ollama on macOS. Closing, but please reopen if continue to have issues.

**Closed by bmizerany** 2024-03-11 23:14 UTC

**Comment by tirithen** [comment] 2024-04-22 20:39
@bmizerany 

I'm getting the same error after re-installing ollama on Arch Linux, it worked just minutes before my re-install.

```
$ ollama run mistral
Error: unmarshal: invalid character 'p' after top-level value
```

```
$ ollama --version
Warning: could not connect to a running Ollama instance
Warning: client version is 0.1.32
```

I think that it would be helpful if the ollama cli had some health check mode where it could verify if the models are valid/have the correct format as well as that the client and server versions are compatible (I suppose that they are mostly bundled together). Anyhow, some sub command that helps troubleshoot what would be causing parsing errors.

**Comment by littson** [comment] 2024-04-24 05:40
> @bmizerany
> 
> I'm getting the same error after re-installing ollama on Arch Linux, it worked just minutes before my re-install.
> 
> ```
> $ ollama run mistral
> Error: unmarshal: invalid character 'p' after top-level value
> ```
> 
> ```
> $ ollama --version
> Warning: could not connect to a running Ollama instance
> Warning: client version is 0.1.32
> ```
> 
> I think that it would be helpful if the ollama cli had some health check mode where it could verify if the models are valid/have the correct format as well as that the client and server versions are compatible (I suppose that they are mostly bundled together). Anyhow, some sub command that helps troubleshoot what would be causing parsing errors.

I am getting the same error on macOS 14.4.1: 

```
$ ollama list
NAME                                               	ID          	SIZE  	MODIFIED
llama3:latest                                      	71a106a91016	4.7 GB	4 days ago

$ ollama run llama3
Error: unmarshal: invalid character 'p' after top-level value

$ ollama -v
Warning: could not connect to a running Ollama instance
Warning: client version is 0.1.32
```

reinstall does not help.

**Comment by Agent-E11** [comment] 2024-04-30 23:42
@littson @tirithen I was able to fix it. My server was running `v0.1.12` and my client was running `v0.1.32`. I can see you both are running it locally though, so maybe it has something to do with you running the newest version of ollama, and maybe there was some sort of change in the encoding

**Comment by littson** [comment] 2024-05-02 01:24
> @littson @tirithen I was able to fix it. My server was running `v0.1.12` and my client was running `v0.1.32`. I can see you both are running it locally though, so maybe it has something to do with you running the newest version of ollama, and maybe there was some sort of change in the encoding

@Agent-E11 Thanks. 

I fixed the issue too. By following your instructions, I realized I had two ollama version installed in my system: 

1. installed from `homebrew`.
2. installed from ollama website as `.dmg` application.

The issue is fixed after I remove the `.dmg` application.
