### ISSUE TITLE
Allow to choose a preferred variant (an AMD GPU/an NIVIDIA GPU/CPU) when running a model

### ISSUE THREAD

**Issue by Inokinoki** [ollama/ollama#3172] opened 2024-03-15 22:55 UTC
### What are you trying to do?

I have both NVIDIA and AMD cards on one PC. Both `nvml.dll`  and `amdhip64.dll` are available on Windows.
I saw in `gpu/gpu.go` ollama tries to detect first NVIDIA and will not try AMD if it found NVIDIA.

### How should we solve this?

Could it be possible to add an arg to indicate the preferred device or variant?

### What is the impact of not solving this?

As a workaround, I just move `nvml.dll` out of the path to by-pass the detection of NVIDIA.

**Comment by frostworx** [comment] 2024-03-16 10:23
I have a similar setup, but use Linux as operating system, and can confirm that the nvidia gpu is prioritized over the amd gpu.

My working workaround to "forcefully" use the amd gpu is to `LD_PRELOAD` the stub library 
`/opt/cuda/targets/x86_64-linux/lib/stubs/libnvidia-ml.so` _(belonging to cuda ironically)_

_(previously I tried a dummy self rolled library for preloading, but it crashed on program launch)_

`LD_PRELOAD` is not accepted by systemd as `Environment` override, so I use a custom `ExecStart` script and preload there.

Using this workaround I'm able to use both gpus simulatenously, because nvidia still finds its original shared library from nvidia-utils

Some function behind an environment variable like USE_CUDA or similar would fix this issue.

**Comment by louwangzhiyuY** [comment] 2024-03-16 15:12
II have the same question as you.   I want an option to choose which GPU.

**Comment by dhiltgen** [comment] 2024-03-21 11:09
I believe this should be possibly by using a mixture of `CUDA_VISIBLE_DEVICES` and `HIP_VISIBLE_DEVICES` to invalid IDs like "-1".

**Comment by frostworx** [comment] 2024-03-21 11:15
Thanks for the hint! I haven't thought of trying invalid IDs.
I won't be able to test before next week, but will report back.

**Comment by Inokinoki** [comment] 2024-03-21 14:24
> I believe this should be possibly by using a mixture of `CUDA_VISIBLE_DEVICES` and `HIP_VISIBLE_DEVICES` to invalid IDs like "-1".

Thanks for the workaround based on the env! Will try it

I created by my self an arg to select gpu variant: https://github.com/ollama/ollama/commit/bed32826d40779e620a376c24c23e929135383aa

Should it be done other way?

**Comment by dhiltgen** [comment] 2024-04-12 22:15
Within PR #3418 I've added support for mixed GPU types.  Once that merges, and we ship a release with it, please give it a try.

**Comment by frostworx** [comment] 2024-04-16 14:10
Thanks for heads up!

Sorry for the lag, a today's mention of the patch at work remembered me, that I still wanted to test it :)

I just successfully compiled current master with [3418](https://github.com/ollama/ollama/pull/3418) applied, and can confirm that ollama found both the nvidia and the amdgpu as valid gpu.
While running a quick test it picked the nvidia gpu by default.

Please let me know how to best test/force amdgpu usage.

there's a minor(?) glitch with the amdgpu kernel module btw:
`time=2024-04-16T15:48:32.254+02:00 level=WARN source=amd_linux.go:49 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers" error="amdgpu version file missing: /sys/module/amdgpu/version stat /sys/module/amdgpu/version: no such file or directory"`
_(I'm on Arch linux, currently running 6.8.5-zen1-1-zen, please let me know if more details are required)_

The gpu is detected correctly:

```
time=2024-04-16T15:48:59.836+02:00 level=INFO source=amd_linux.go:217 msg="amdgpu memory" gpu=0 totalMB=16368
time=2024-04-16T15:48:59.836+02:00 level=INFO source=amd_linux.go:218 msg="amdgpu memory" gpu=0 freeMB=16368
time=2024-04-16T15:48:59.838+02:00 level=INFO source=amd_linux.go:276 msg="amdgpu is supported" gpu=0 gpu_type=gfx1030
```

**Comment by dhiltgen** [comment] 2024-04-16 16:09
> there's a minor(?) glitch with the amdgpu kernel module

That's "working as designed" - the lack of the version file implies this is an upstream amdgpu driver merged into the linux kernel source, and is quite a bit out of date compared to the AMD downstream driver, so has bugs and missing features that may impact some GPUs.  This warning is there to guide users if they run into problems so they can try upgrading to the latest driver.  If things are working properly, then you should be OK.

The design goal for 3418 is to allow models to run on both GPUs, but we're taking it one step at a time to make sure things are solid.  You can set `OLLAMA_MAX_RUNNERS` to zero for dynamic, or some number greater than 1 to put a hard cap on the number of runners (e.g. 2 in your case) and then try to load two (or more) different models.  Once the nvidia card is full, it should move to the AMD card.

**Comment by frostworx** [comment] 2024-04-16 16:20
Ah ic, thank you for clarification!

**Comment by dhiltgen** [comment] 2024-04-28 19:08
The [0.1.33](https://github.com/ollama/ollama/releases) release is available now as a pre-release.

**Comment by dhiltgen** [comment] 2024-05-04 22:07
I believe everything should be in place for this to work now with 0.1.33, so I'll close this ticket.

**Closed by dhiltgen** 2024-05-04 22:07 UTC
Labels: windows
