### ISSUE TITLE
Ollama : phi 3 small

### ISSUE THREAD

**Issue by sebastienbo** [ollama/ollama#4819] opened 2024-06-04 19:26 UTC
Hi, 

We have the phi 3 mini (which is not smart enough) and the phi 3 medium which is too slow.

But where is phi 3 small?

It works so great on lmstudio and gpt4all
It would be great if ollama made it available

**Comment by pdevine** [comment] 2024-06-05 20:35
Dupe of #4646

**Closed by pdevine** 2024-06-05 20:35 UTC
Labels: feature request
