### ISSUE TITLE
Please add support for Molmo-7B, new SOTA multimodal model from Allen AI

### ISSUE THREAD

**Issue by robert-mcdermott** [ollama/ollama#6960] opened 2024-09-25 18:12 UTC
https://huggingface.co/allenai/Molmo-7B-O-0924

**Comment by CAFxX** [comment] 2024-09-25 22:19
Duplicate of https://github.com/ollama/ollama/issues/6958

**Comment by Owen718** [comment] 2024-09-27 07:40
Fully agree +1. REALLY NEED.

**Comment by ryanholtschneider2** [comment] 2024-09-27 20:14
and 7D please

**Comment by sfdkiaei** [comment] 2024-10-08 07:35
and https://huggingface.co/allenai/Molmo-7B-D-0924 please.

**Comment by MrCabss69** [comment] 2024-10-14 21:01
+1

There's a guide on how to contribute btw?

**Comment by rick-github** [comment] 2024-11-13 09:17
dupe https://github.com/ollama/ollama/issues/6958

**Closed by rick-github** 2024-11-13 09:17 UTC
Labels: model request

**Comment by wzhisaso** [comment] 2025-03-11 03:21
+1
