### ISSUE TITLE
Ability to keep a model in memory for longer

### ISSUE THREAD

**Issue by helloimcx** [ollama/ollama#1536] opened 2023-12-15 02:45 UTC
is there a way to  keep the model in memory or gpu memory ?

**Comment by nelsongomes** [comment] 2023-12-15 13:51
This a very important feature and models should be kept in memory by default. In reality, it makes sense even to keep multiple instances of same model if memory is available and the loaded models are already in use. This way Ollama can be cost effective and performant @jmorganca. 

This is needed to make Ollama a usable server, just came out of a meeting and this was the main reason not to choose it, it needs to cost effective and performant.

**Comment by rgaidot** [comment] 2023-12-17 15:59
Maybe you can do a curl every second with the model (it's not great but it should work)) 

```
curl http://0.0.0.0:11434/api/chat -d '{
    "model": "mistral"
 }'
```

**Comment by mLpenguin** [comment] 2023-12-17 18:28
There is a potential solution to change the timeout from the hardcoded 5 minutes to an env variable but it is still waiting to be merged #1257

**Comment by nelsongomes** [comment] 2023-12-17 20:12
Thanks for replying.

The issue is that GPUs are expensive and majority of models could have
several replicas inside of a GPU memory. This would allow several threads
running in paralelo answering different requests.
Otherwise a 64gb memory GPU is almost wasted.

Ideally you should keep adding replicas until memory is either full or
there is the need to evict an instance to make room for a different model
to be loaded and keep all instances always loaded, no eviction if not
needed.

No one wants a server to load models on the fly if memory is enough and
make requests slower.

Do you get my point?

Thanks
Nelson Gomes

A domingo, 17/12/2023, 15:59, Régis Gaidot ***@***.***>
escreveu:

**Comment by helloimcx** [comment] 2023-12-18 06:34
> There is a potential solution to change the timeout from the hardcoded 5 minutes to an env variable but it is still waiting to be merged #1257

thanks, i changed ` defaultSessionDuration` in routes.go with a longer period, it worked.

**Comment by nelsongomes** [comment] 2023-12-18 23:27
Ideally, we could have a fixed config file being passed to server:
{
   "mistral": { "instances": 3, "target": "gpu" },
   "llama2": { "instances": 1, "target": "cpu"}
}
that would allow to set up the intended usage we wanna give to the server.

**Comment by helloimcx** [comment] 2023-12-19 01:22
> Ideally, we could have a fixed config file being passed to server: { "mistral": { "instances": 3, "target": "gpu" }, "llama2": { "instances": 1, "target": "cpu"} } that would allow to set up the intended usage we wanna give to the server.

yea, that would be great!

**Comment by nelsongomes** [comment] 2023-12-26 09:10
Was I able to convince you guys that memory strategy needs some revisiting?

**Comment by nelsongomes** [comment] 2023-12-26 11:16
Another option for memory management would be to add commands to manage permanently loaded models and their count... this way we could tell the server what we wanted in memory.

**Comment by jooneyp** [comment] 2023-12-26 13:15
@nelsongomes +1, I'm the another one to make user decide the manage strategy of the memory. Need to make env variable or even dynamic option for each model.

**Comment by rgaidot** [comment] 2023-12-29 17:29
In the meantime, have you tested this solution (use_mlock) https://github.com/jmorganca/ollama/issues/1672 ?

**Comment by easp** [comment] 2024-01-02 21:38
@nelsongomes, keeping multiple instances of a single model in memory doesn't make any sense, at all. It's a waste of memory and memory bandwidth. Concurrency is better handled by batching requests and amortizing the cost of memory access across the whole batch.

If they are going to add features to support concurrency they should focus on batching, rather than a kludge.

**Comment by nelsongomes** [comment] 2024-01-03 14:31
That is a valid point. Does Ollama support concurrency? Currently running
it on my MAC it doesn't but it's obvious because my MAC does not have an
usable GPU.

Erik S ***@***.***> escreveu no dia terça, 2/01/2024 à(s)
21:38:

**Comment by nelsongomes** [comment] 2024-01-04 16:18
@easp I've done more reading about it and if I understood correctly batching is the way to go, but if a request does not enter the batch in time it needs to wait for next batch which may take seconds to start. Could it be that if we have several models loaded into GPU memory we could have several batches running continuously? Making full use of memory and concurrency?

**Comment by easp** [comment] 2024-01-04 19:30
For a single completion request, tokens are generated serially, which each token generated depending on the initial context + prompt and preceding tokens generated for the response. Generating each token involves computing, end to end, over the entirety of the model weights. With batch generation, the process is the same, but next tokens for a set of individual completions threads are calculated in a single traversal of the model weights.

Batches are continuous, so a new request only waits for the next set of "in-flight" tokens to complete before joining the batch for the next token(s). New completions can be started with each new batch, and in-progress completions may conclude with each new batch, even as others continue. So, at, say, 25 batch generation rate, a new request doesn't wait more than 80ms for its first token to be generated.

So, it only makes sense to have a single copy of the model loaded. It does make sense to have multiple models loaded, if resources permit, to allow quick switching between models.

As I said though, Ollama doesn't support this, at least not yet. It is supported by llama.cpp, which Ollama uses to "run" models, but I'd expect that it would require some work in the Ollama server as well to support and so far Ollama seems to be pretty focused on single-user scenarios.

**Comment by jmorganca** [comment] 2024-01-04 19:52
Thanks for creating this issue folks – sorry this isn't easier yet. Will investigate how to better support keeping models loaded for longer

**Comment by jmorganca** [comment] 2024-01-25 04:18
Keep an eye on this PR which will enable keeping a model in memory indefinitely (or for a custom amount of time): https://github.com/ollama/ollama/pull/2146

**Comment by pdevine** [comment] 2024-01-26 23:53
This is merged now, so I'm going to go and and close the issue. You'll be able to use this in `0.1.23`.

**Closed by pdevine** 2024-01-26 23:53 UTC
Labels: enhancement

**Comment by nelsongomes** [comment] 2024-01-28 22:14
Thank you!

Patrick Devine ***@***.***> escreveu (sexta, 26/01/2024 à(s)
23:53):

**Comment by sirkuttin** [comment] 2024-04-22 18:21
https://github.com/ollama/ollama/blob/62be2050dd83197864d771fe6891fc47486ee6a1/cmd/cmd.go#L1005

**Comment by Lokeshwaran-M** [comment] 2024-12-29 18:41
> https://github.com/ollama/ollama/blob/62be2050dd83197864d771fe6891fc47486ee6a1/cmd/cmd.go#L1005

it will be great if there is lot more control given via command line 

like for stropping server 
increasing model in memory alive state and many more
