### ISSUE TITLE
Json Mode significantly decrease GPU usage

### ISSUE THREAD

**Issue by LaetLanf** [ollama/ollama#4680] opened 2024-05-28 14:17 UTC
### What is the issue?

I am running Ollama Llama3:70b-instruct on an Azure Linux A100 VM.

I did a test with and without json mode, with the exact same prompt and python code. The only thing I changed is format='json' in the chat call.

WITHOUT json mode, I reached:
22-25 TPS for 1 chat call
The monitoring of the GPU (see attached) clearly show that the GPU is well used

WITH json mode:
6 TPS for 1 chat call
The monitoring of the GPU (see attached) clearly show that the GPU is NOT fully used

![Capture d’écran 2024-05-28 à 10 54 30](https://github.com/ollama/ollama/assets/131473617/0419ae0d-96d1-4ac0-8359-bfd4abc2bb41)

### OS

Linux

### GPU

Nvidia

### CPU

Other

### Ollama version

0.1.38

**Comment by pdevine** [comment] 2024-05-28 20:41
Dupe of #3851 

cc @jmorganca

**Closed by pdevine** 2024-05-28 20:41 UTC
Labels: bug
