### ISSUE TITLE
Run ollama list/pull got an error

### ISSUE THREAD

**Issue by imagebody** [ollama/ollama#3521] opened 2024-04-07 06:40 UTC
### What is the issue?

I run ollama in docker container,like this:

ollama pull llama2:70b

Then, I get an error:
Error: something went wrong, please see the ollama server logs for details

### OS

Linux

### Platform

Docker

**Comment by xiehongxin** [comment] 2024-04-07 09:10
What docker image are you using?

**Comment by xiehongxin** [comment] 2024-04-07 09:29
I try to run ollama in ubuntu:18.04 image, and it success!

this is my command:
```shell
# docker run -itd --name ollama_lab ubuntu:18.04
# docker exec -it ollama_lab bash
# apt update
# apt install curl
# curl -fsSL https://ollama.com/install.sh | sh
```

because of use docker, so the install.sh can not create ollama service success
```shell
# ollama --version
Warning: could not connect to a running Ollama instance
Warning: client version is 0.1.30
```

so you should be run ollama serve manually
```shell
ollama serve &
```

because of memory limit, i try small model
```shell
ollama run qwen:0.5b
```
 
and it success!  maybe you can try other model

**Comment by vishnu-dev** [comment] 2024-04-10 12:09
I have the exact same issue. I tried everything, but still doesn't work. #3526

**Comment by pdevine** [comment] 2024-04-12 21:08
@imagebody Can you attach the server logs? What type of system are you running on and how much memory is there?

**Comment by vishnu-dev** [comment] 2024-04-12 21:19
> @imagebody Can you attach the server logs? What type of system are you running on and how much memory is there?

Could you please take a look at issue #3526 ? I have included all the details mentioned. I have the same issue.

**Comment by RedemptionC** [comment] 2024-04-26 06:27
> @imagebody Can you attach the server logs? What type of system are you running on and how much memory is there?

the problem is where can I get the server logs? I'm using Apple Silicon Mac and had this issue.

**Comment by pdevine** [comment] 2024-05-06 21:49
Hey @RedemptionC, sorry for the slow response. Please refer to the [troubleshooting guide](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues) which explains how to get the logs for each platform (mac/linux/windows/docker).

**Comment by pdevine** [comment] 2024-05-18 04:13
I'm going to go ahead and close the issue. Please feel free to comment and we can reopen if you're still seeing the issue.

**Closed by pdevine** 2024-05-18 04:13 UTC
Labels: bug
