### ISSUE TITLE
add openbmb MiniCPM-V-2_6

### ISSUE THREAD

**Issue by insinfo** [ollama/ollama#6267] opened 2024-08-08 23:14 UTC
add openbmb MiniCPM-V-2_6
https://huggingface.co/openbmb/MiniCPM-V-2_6-gguf/tree/main

**Comment by rick-github** [comment] 2024-08-08 23:19
Pending support in llama.cpp: https://github.com/ggerganov/llama.cpp/pull/7599

**Comment by calonye** [comment] 2024-08-09 01:42
希望可以支持 ollama，无需再自行编译，如其他流行模型一样，run 后直接可用。
I hope there will be support for Ollama without needing to compile it myself, like other popular models, where it can be run and used directly after.
：https://github.com/OpenBMB/MiniCPM-V/issues/422

**Comment by itsPreto** [comment] 2024-08-09 14:26
https://github.com/ggerganov/llama.cpp/pull/7599 has been merged can we get the ball rolling here:)

**Comment by rick-github** [comment] 2024-08-09 14:30
Almost there, https://github.com/ggerganov/llama.cpp/pull/7599 was for MiniCPM-V-2_5, MiniCPM-V-2_6 requires another PR but that will build on the existing work and shouldn't take long.

**Comment by xuhongming251** [comment] 2024-08-11 13:15
https://ollama.com/xuxx/minicpm2.6

There is an installation package for Ollama on Windows, and the MiniCPM 2.6 model is available.

**Comment by rick-github** [comment] 2024-08-11 14:28
https://github.com/ggerganov/llama.cpp/pull/8967

**Comment by ChristianWeyer** [comment] 2024-08-16 18:21
> Pending support in llama.cpp: [ggerganov/llama.cpp#7599](https://github.com/ggerganov/llama.cpp/pull/7599)

This and this https://github.com/ggerganov/llama.cpp/pull/8967 got merged 🥳

**Comment by ttamoud** [comment] 2024-08-17 15:59
https://github.com/ggerganov/llama.cpp/pull/8967 has been merged, can we get the ball rolling here pls 💯

**Comment by tong-zeng** [comment] 2024-08-21 00:04
I've seen a lot of requests to add MiniCPM-V-2.6, but haven't seen any response / progress lately, any problems with MiniCPM-V-2.6 PR or any concerns? Thanks.

**Comment by pdevine** [comment] 2024-09-01 23:46
Dupe of #6417

**Closed by pdevine** 2024-09-01 23:46 UTC
Labels: feature request

**Comment by itsPreto** [comment] 2024-09-10 19:52
I see this ticket is marked as closed but I don't see any information on whether the video capabilities of this model are also implemented?

**Comment by rick-github** [comment] 2024-09-10 20:11
llama.cpp doesn't support video at the moment.

**Comment by ChristianWeyer** [comment] 2024-09-11 10:06
Is there an example of how to query this model with images?
Via CLI and via API @rick-github?

**Comment by rick-github** [comment] 2024-09-13 07:29
CLI (note the image to be processed must be a full (/xx/yy/xx.jpg) or relative (./xx.jpg) path, just the filename (xx.jpg) won't be recognized as a file to be added to the prompt):
```console
$ ollama run minicpm-v:8b-2.6-q4_0
>>> describe this image: ./puppy.jpg
Added image './puppy.jpg'
The image depicts a small white puppy with soft, fluffy fur sitting on what 
appears to be an outdoor step or platform. The background is blurred but seems 
to consist of neutral colors that do not distract from the subject. Notably, the 
puppy has a red collar around its neck adorned with a single gold bell and two 
red decorative pieces resembling flowers. Its expression is curious yet alert 
as it gazes off into the distance.

>>> 
```
Raw API:
```
$ curl -s http://localhost:11434/api/chat -d '{
  "model":"minicpm-v:8b-2.6-q4_0",
  "messages":[{
    "role":"user",
    "content":"describe the image",
    "images":["'$(base64 -w0 puppy.jpg)'"]}],
  "stream":false}' | jq -r .message.content

The image depicts a small, white puppy sitting on what appears to be a stone or 
concrete surface. The puppy has fluffy fur and bright eyes that convey curiosity 
or alertness. Around its neck is a red collar with a bell attached, which 
suggests the dog might have an outdoor environment where it interacts with 
people who like to hear their whereabouts through sound. There's no discernible 
context beyond this; there are no other animals, humans, or objects in the 
immediate vicinity that give further clues about the setting or story behind the 
image.
```
Python API:
```python
#!/usr/bin/env python3

import ollama
import base64

with open("puppy.jpg", "rb") as f:
  b64_image = base64.b64encode(f.read()).decode("utf-8")
  client = ollama.Client()
  response = client.chat(
      model="minicpm-v:8b-2.6-q4_0",
      messages=[{
        "role":"user",
        "content":"describe this image",
        "images":[b64_image]}
      ]
  )
  print(response["message"]["content"])

"""
This image shows a small white puppy sitting on what appears to be a concrete 
surface, possibly steps. The puppy has soft, fluffy fur and bright eyes that 
are looking off into the distance with an innocent expression. It is wearing a 
red collar adorned with a single gold bell, which adds a touch of color 
contrast against its pure white coat. In the background, there's a blurred 
urban environment suggesting this photo might have been taken in a city or town 
setting. The puppy’s posture and gaze give it a curious yet gentle demeanor, 
making for an endearing image that captures the viewer's attention with its 
simplicity and charm.
"""
```

![puppy](https://github.com/user-attachments/assets/98bef0b5-cf0b-4558-a863-4a571b7f42cd)

**Comment by ChristianWeyer** [comment] 2024-09-13 07:31
Perfect, thank you @rick-github

**Comment by colin4k** [comment] 2024-09-13 08:42
> Is there an example of how to query this model with images? Via CLI and via API @rick-github?

ollama run minicpm-v "extract all java code from the image: ./1.png"

But I compared minicpm-v and qwen2-vl, qwen2-vl performed much better.

**Comment by ChristianWeyer** [comment] 2024-09-13 08:44
> > Is there an example of how to query this model with images? Via CLI and via API @rick-github?
> 
> ollama run minicpm-v "extract all java code from the image: ./1.png"
> 
> But I compared minicpm-v and qwen2-vl, qwen2-vl performed much better.

Interesting - is `qwen2-vl `in Ollama registry? Could not find it.

**Comment by rick-github** [comment] 2024-09-13 08:55
Not supported in llama.cpp yet: https://github.com/ggerganov/llama.cpp/issues/9246

**Comment by colin4k** [comment] 2024-09-14 00:43
> > > Is there an example of how to query this model with images? Via CLI and via API @rick-github?
> > 
> > 
> > ollama run minicpm-v "extract all java code from the image: ./1.png"
> > But I compared minicpm-v and qwen2-vl, qwen2-vl performed much better.
> 
> Interesting - is `qwen2-vl `in Ollama registry? Could not find it.

Ollama didn't suppport qwen2-vl now, you have to run qwen2-vl with it's source code.
