### ISSUE TITLE
Error: error loading model

### ISSUE THREAD

**Issue by zbrkic** [ollama/ollama#2753] opened 2024-02-25 23:54 UTC
First time install `ollama version is 0.1.27`, trying to run model, getting Error loading model - No such file or directory, but files exist:
```
time=2024-02-26T00:11:49.314+01:00 level=INFO source=dyn_ext_server.go:90 msg="Loading Dynamic llm server: C:\\Users\\ELJKO~1\\AppData\\Local\\Temp\\ollama816527122\\cpu_avx2\\ext_server.dll"
time=2024-02-26T00:11:49.314+01:00 level=INFO source=dyn_ext_server.go:150 msg="Initializing llama server"
llama_model_load: error loading model: failed to open C:\Users\Željko\.ollama\models\blobs\sha256-8934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef9246: No such file or directory
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'C:\Users\Željko\.ollama\models\blobs\sha256-8934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef9246'
{"timestamp":1708902709,"level":"ERROR","function":"load_model","line":388,"message":"unable to load model","model":"C:\\Users\\Željko\\.ollama\\models\\blobs\\sha256-8934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef9246"}
time=2024-02-26T00:11:49.314+01:00 level=WARN source=llm.go:162 msg="Failed to load dynamic library C:\\Users\\ELJKO~1\\AppData\\Local\\Temp\\ollama816527122\\cpu_avx2\\ext_server.dll  error loading model C:\\Users\\Željko\\.ollama\\models\\blobs\\sha256-8934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef92"
[GIN] 2024/02/26 - 00:11:49 | 500 |    332.6058ms |       127.0.0.1 | POST     "/api/chat"
[GIN] 2024/02/26 - 00:15:10 | 200 |         509µs |       127.0.0.1 | GET      "/api/version"
```
Files exist:
```
PS C:\> ls C:\Users\Željko\AppData\Local\Temp\ollama816527122\cpu_avx2\ext_server.dll


    Directory: C:\Users\Željko\AppData\Local\Temp\ollama816527122\cpu_avx2


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        26.2.2024.      0:03        2475456 ext_server.dll


PS C:\> ls C:\Users\Željko\.ollama\models\blobs\sha256-8934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef9246


    Directory: C:\Users\Željko\.ollama\models\blobs


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        26.2.2024.      0:05     3826781184 sha256-8934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef9246
```

At some point application tries to read in invalid folder:

 `C:\Users\Ĺ˝eljko\.ollama\models\blobs\sha256-8934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef9246`

![slika](https://github.com/ollama/ollama/assets/11651634/f062fe7f-7d6f-4bd8-83b2-d67bee97b5ae)

It seems that unicode letters are not supported in the path, in some part of code. Is there a way to install the app in some other folder until this is fixed?

**Comment by skwolvie** [comment] 2024-02-26 10:51
I got the same error: 

Here is what i did: 
1. I finetuned llama2-7b-hf 
2. I made it into gguf (after a lot of bug fixing)
3. I created the Modelfile and loaded gguf model to ollama. 
4. ollama list shows it is in the list of models
5. ollama run fails

```

C:\Users\31405.ISBDOMAIN1\Desktop>ollama list
NAME                            ID              SIZE    MODIFIED
llama2:latest                   78e26419b446    3.8 GB  3 hours ago
skwolvie_patent_v1:latest       fa698afb0826    7.2 GB  8 minutes ago

C:\Users\31405.ISBDOMAIN1\Desktop>ollama run skwolvie_patent_v1
Error: error loading model C:\Users\31405.ISBDOMAIN1\.ollama\models\blobs\sha256-0a623fb0634059b6ab0857a30f57eae9686729452cc8437dc95ca
```

**Comment by skwolvie** [comment] 2024-02-26 11:55
I see that the error is because the file name while loading and the file name that is actually stored are quite different. It is truncated. 

Notice here error:
```
Error: error loading model C:\Users\31405.ISBDOMAIN1\.ollama\models\blobs\sha256-0a623fb0634059b6ab0857a30f57eae9686729452cc8437dc95ca
```

Notice here file name:
```
C:\Users\31405.ISBDOMAIN1\.ollama\models\blobs\sha256-0a623fb0634059b6ab0857a30f57eae9686729452cc8437dc95ca39368fad73c
```

**Comment by skwolvie** [comment] 2024-02-27 08:56
just verified that the same issue exist in mac os as well. 
when we create a model from a gguf file and then run it, it throws error blob file not found. 

However, if we dont load gguf, and download the basic models no error. 

Pushing the loaded gguf model to hub, and then loading it also produces the same error.

**Comment by hotsmile** [comment] 2024-02-27 11:50
> I see that the error is because the file name while loading and the file name that is actually stored are quite different. It is truncated.
> 
> Notice here error:
> 
> ```
> Error: error loading model C:\Users\31405.ISBDOMAIN1\.ollama\models\blobs\sha256-0a623fb0634059b6ab0857a30f57eae9686729452cc8437dc95ca
> ```
> 
> Notice here file name:
> 
> ```
> C:\Users\31405.ISBDOMAIN1\.ollama\models\blobs\sha256-0a623fb0634059b6ab0857a30f57eae9686729452cc8437dc95ca39368fad73c
> ```

the same to me！ i  use ollama to pull gemma:2b ,but run ,i got the error

**Comment by skwolvie** [comment] 2024-02-28 02:46
@hotsmile what could be the fix?

**Comment by kime541200** [comment] 2024-02-28 10:09
I got the same error, is there any solution?

**Comment by nonacosa** [comment] 2024-02-29 02:25
same error 
<img width="1021" alt="image" src="https://github.com/ollama/ollama/assets/14212375/6aef9154-8bb1-4fc7-96a2-53f1c4314ba3">

**Comment by saamerm** [comment] 2024-02-29 03:13
Seeing the same error as @nonacosa on a CentOS Linux computer running the latest ollama version for dolphin-phi

**Comment by nonacosa** [comment] 2024-02-29 05:38
> Seeing the same error as @nonacosa on a CentOS Linux computer running the latest ollama version for dolphin-phi

After all models ` ollama rm  <model> ` and clear `~/.ollama/models/blobs/` and repeat install, it works now, maby you can try it? 

<img width="938" alt="image" src="https://github.com/ollama/ollama/assets/14212375/5490f396-a297-448a-a4a5-2f684147bf00">

**Comment by eijyuueda** [comment] 2024-03-01 02:36
I also catch the problem(ver. windows preview.)
I converted a model to GGUF format model by myself with using my GPU server and I move the GGUF to my local. (windows)
Aftar that I create Modelfile but I had faced the problem.

```
blobs\sha256-8277d34ba7ab4bd6a64ad57c5d510e439f66cad7bc910ee1441da45001b2a68
blobs\sha256-8277d34ba7ab4bd6a64ad57c5d510e439f66cad7bc910ee1441da45001b2a687
```

Last character is suspiciously missing on the terminal output.
Is there a good interim solution?

**Comment by Parici75** [comment] 2024-03-01 09:40
Same error as @nonacosa  and @saamerm, I tried to remove all models and clear `~/.ollama/models/blobs/`, to no avail.

```bash
➜  ~ ollama pull deepseek-coder:6.7b
pulling manifest 
pulling 59bb50d8116b... 100% ▕████████████████▏ 3.8 GB                         
pulling a3a0e9449cb6... 100% ▕████████████████▏  13 KB                         
pulling 8893e08fa9f9... 100% ▕████████████████▏   59 B                         
pulling 8972a96b8ff1... 100% ▕████████████████▏  297 B                         
pulling 772f510b9558... 100% ▕████████████████▏  483 B                         
verifying sha256 digest 
writing manifest 
removing any unused layers 
success 
➜  ~ ollama run deepseek-coder:6.7b
Error: error loading model /Users/benroland/.ollama/models/blobs/sha256:59bb50d8116b6a1f9bfbb940d6bb946a05554e591e30c8c2429ed6c854867e
```

System info :
```
➜  ~ ollama --version
ollama version is 0.1.27
➜  ~ sw_vers
ProductName:		macOS
ProductVersion:		13.6.1
BuildVersion:		22G313
```

**Comment by NeevJewalkar** [comment] 2024-03-02 06:05
I have been facing this issue since today morning.
Could this be the result of a new update?

**Comment by guilhermecomum** [comment] 2024-03-03 12:19
Could this issue be related to this [change](https://github.com/ollama/ollama/blob/21347e1ed67a4ef36abc11bf314e90eaba9a0dc4/llm/ext_server/ext_server.cpp#L123)?

**Comment by cyriltw** [comment] 2024-03-03 15:19
+1 on this issue.

**Comment by eggsyntax** [comment] 2024-03-03 21:14
I was having the same error, and found that it was sufficient to quit the main ollama app (from the menu bar) and restart it (from spotlight). Then I can `ollama run <some-model>` with no problems.

**Comment by eggsyntax** [comment] 2024-03-04 00:45
I'm a professional programmer, so "[Have you tried turning it off and on again?](https://www.youtube.com/watch?v=nn2FB1P_Mn8)" is burned into my very soul 😁

**Comment by JulienBreux** [comment] 2024-03-05 08:55
Same error here :)

```
~ ❯❯❯ ollama --version
ollama version is 0.1.27

~ ❯❯❯ sw_vers
ProductName:		macOS
ProductVersion:		14.3.1
BuildVersion:		23D60
```

**Comment by cmingxu** [comment] 2024-03-05 09:31
same to me on mac `ollama version is 0.1.27`, even I rm / pull model again

**Comment by nicaudinet** [comment] 2024-03-05 10:19
Same on me (MacOS) with Ollama 0.1.27. Got it to work by:
- `ollama rm mistral`
- `ollama pull mistral`
- Quitting ollama and opening again
- `ollama run mistral`

Not sure if the rm / pull was even necessary

**Comment by guilhermecomum** [comment] 2024-03-05 12:54
If you are using homebrew, don't forget to stop the ollama service.
- `brew services stop ollama`
- `rm -rf ~/.ollama`
- `brew services start ollama`
- `ollama pull <model>`

**Comment by skwolvie** [comment] 2024-03-05 19:22
@here Is this issue resolved?

**Comment by Kota1609** [comment] 2024-03-05 20:25
im using mac, i just uninstalled and installed ollama app again and it worked.

**Comment by skwolvie** [comment] 2024-03-06 06:25
i tired and still getting the same error. Which version did you install?

**Comment by RamiKassouf** [comment] 2024-03-06 09:33
I'm running ollama using cmd and with no GUI, creating a model using a gguf or bin is resulting in the same error above
I've tried removing model and recreating it, stopping ollama serve and rerunning it and to no avail
Please any updates on a fix?

**Comment by JulienBreux** [comment] 2024-03-06 09:55
@RamiKassouf @skwolvie @skwolvie actually, you need to uninstall and install Ollama from your system.

**Comment by zbrkic** [comment] 2024-03-06 10:36
Start/stop/uninstall/install - nothing helped.

**Comment by RamiKassouf** [comment] 2024-03-06 11:43
> @RamiKassouf @skwolvie @skwolvie actually, you need to uninstall and install Ollama from your system.

is that after i create the model? or when is it in the process?

**Comment by RamiKassouf** [comment] 2024-03-07 07:41
> @RamiKassouf @skwolvie @skwolvie actually, you need to uninstall and install Ollama from your system.

I tried It still didn t work

**Comment by JulienBreux** [comment] 2024-03-07 07:50
Sorry friends, it worked for me.

Maybe @BruceMacD have an idea

**Comment by BruceMacD** [comment] 2024-03-07 16:30
Hey everyone, sorry about this. I'm looking to reproduce this now and get it fixed. Thanks to everyone for the details. The error here is vague so it like there are maybe 3 potential problems here.

1. Unsupported unicode characters in the path cause models to not be able to load. I've reproduced this one, and it seems to be Windows specific, I'll be fixing this one.
- workaround: Set `OLLAMA_MODELS` to a path that does not include a unicode character until the fix is in.
2. Unsupported model imported into Ollama. If you import a model which cannot be converted into gguf format, it may result in the `error loading model` message at runtime. I'll see if I can catch the earlier and return a better error.
3. The most common problem seems to be previously downloaded models not working, sometimes with the filename being incorrect. This is the hard one for me to track down at the moment. I'll update again when I find something.
- workaround: try `ollama pull $MODEL_NAME`

**Comment by BruceMacD** [comment] 2024-03-07 19:36
If anyone else hits this error please try stopping ollama and running the ollama server directly with debug on.
powershell:
```
$env:OLLAMA_DEBUG=1; ollama serve
```

command prompt:
```
set "OLLAMA_DEBUG=1" && ollama serve
```

Then if you see any suspicious logs paste them here. Might help me out.

**Comment by BruceMacD** [comment] 2024-03-07 21:50
related for unicode path support: https://github.com/ggerganov/llama.cpp/pull/5927

**Comment by JulienBreux** [comment] 2024-03-08 07:25
> related for unicode path support: https://github.com/ggerganov/llama.cpp/pull/5927

Big thnks Bruce for your followup!

**Comment by FotieMConstant** [comment] 2024-03-08 08:50
> related for unicode path support: [ggerganov/llama.cpp#5927](https://github.com/ggerganov/llama.cpp/pull/5927)

Don't get it, i am on macOS and the PR is related to windows i think...

**Comment by bmaciag** [comment] 2024-03-08 13:52
> same error <img alt="image" width="1021" src="https://private-user-images.githubusercontent.com/14212375/308773885-6aef9154-8bb1-4fc7-96a2-53f1c4314ba3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MDYxODcsIm5iZiI6MTcwOTkwNTg4NywicGF0aCI6Ii8xNDIxMjM3NS8zMDg3NzM4ODUtNmFlZjkxNTQtOGJiMS00ZmM3LTk2YTItNTNmMWM0MzE0YmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDEzNTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlOTNkMzRjNWViNjkyYjBkZGNjMTFhNzJjMDg0MzAwMDRiMmQ2NTdhZTNkMDk5ODZlYTg2YWFmNDI1NGUwZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JJlXJptUs-pDd-tFPwyLx7lC7rmfxaRYTtDOBYhiB7A">

same issue here on windows with llama2

**Comment by karpovas1505** [comment] 2024-03-10 09:34
Hi all
I have the same issue at Windows 10 Pro 64

**Comment by CROmartin** [comment] 2024-03-12 21:30
Hi everybody, I faced the same issue, but in my case model worked fine until now:
"ollama run gemma:latest
Error: error loading model /Users/martinstaresincic/.ollama/models/blobs/sha256:456402914e838a953e0cf80caa6adbe75383d9e63584a964f504a"

I was not too fond of deleting models and redownloading as suggested many times on online forums. A quick fix for me was: I just re-downloaded the Ollama installer, reran it and things started working properly again.

**Comment by xiaods** [comment] 2024-03-13 10:10
![Image_20240313180930](https://github.com/ollama/ollama/assets/37678/11c1669b-8236-4f62-9d82-ef3d4f2459bd)

```bash
C:\Users\kingdee.DESKTOP-7IJNE2P>ollama -v
ollama version is 0.1.28
```

**Closed** 2024-03-13 18:05 UTC
Labels: bug

**Comment by Praisethefab** [comment] 2024-03-25 23:11
With Windows 10 the "Unsupported unicode characters in the path cause models to not be able to load." is still present, or at least changing the OLLAMA_MODELS directory to not include the unicode character "ò" that it included before made it work, I did have the model updated as it was my first time downloading this software and the model that I had just installed was llama2, to not have to wait to redownload all I also migrated the hashes so that I didn't have to redownload them all and they worked perfectly so I am sure it is the "Unsupported unicode" problem
