### ISSUE TITLE
Ollama Docker image 0.4.0-rc3-rocm crashes due to missing shared library

### ISSUE THREAD

**Issue by ic4-y** [ollama/ollama#7279] opened 2024-10-20 17:14 UTC
### What is the issue?

I just tried out the latest 0.4.0-rc3-rocm docker image and the `ollama_llama_server` crashes with

```ollama-rocm | /usr/lib/ollama/runners/rocm/ollama_llama_server: error while loading shared libraries: libelf.so.1: cannot open shared object file: No such file or directory```

I am running this on a Radeon Pro W6800, the latest stable release `0.3.13-rocm` works just fine.

Here is a slightly bigger section of the debug log in case that is helpful.

```
ollama-rocm | time=2024-10-20T17:07:58.034Z level=INFO source=llama-server.go:355 msg="starting llama server" cmd="/usr/lib/ollama/runners/rocm/ollama_llama_server --model /root/.ollama/models/blobs/sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa --ctx-size 8192 --batch-size 512 --embedding --n-gpu-layers 33 --verbose --threads 12 --parallel 4 --port 46723"
ollama-rocm | time=2024-10-20T17:07:58.034Z level=DEBUG source=llama-server.go:372 msg=subprocess environment="[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HSA_OVERRIDE_GFX_VERSION=10.3.0 ROCR_VISIBLE_DEVICES=0 LD_LIBRARY_PATH=/usr/lib/ollama:/usr/lib/ollama/runners/rocm HIP_VISIBLE_DEVICES=0]"
ollama-rocm | time=2024-10-20T17:07:58.037Z level=INFO source=sched.go:450 msg="loaded runners" count=1
ollama-rocm | time=2024-10-20T17:07:58.037Z level=INFO source=llama-server.go:534 msg="waiting for llama runner to start responding"
ollama-rocm | time=2024-10-20T17:07:58.037Z level=INFO source=llama-server.go:568 msg="waiting for server to become available" status="llm server error"
ollama-rocm | /usr/lib/ollama/runners/rocm/ollama_llama_server: error while loading shared libraries: libelf.so.1: cannot open shared object file: No such file or directory
ollama-rocm | time=2024-10-20T17:07:58.288Z level=ERROR source=sched.go:456 msg="error loading llama server" error="llama runner process has terminated: exit status 127"
ollama-rocm | time=2024-10-20T17:07:58.288Z level=DEBUG source=sched.go:459 msg="triggering expiration for failed load" model=/root/.ollama/models/blobs/sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa
ollama-rocm | time=2024-10-20T17:07:58.288Z level=DEBUG source=sched.go:361 msg="runner expired event received" modelPath=/root/.ollama/models/blobs/sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa
ollama-rocm | time=2024-10-20T17:07:58.288Z level=DEBUG source=sched.go:376 msg="got lock to unload" modelPath=/root/.ollama/models/blobs/sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa
ollama-rocm | [GIN] 2024/10/20 - 17:07:58 | 500 |  311.617978ms |       127.0.0.1 | POST     "/api/generate"
```

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

0.4.0-rc3-rocm (Docker image)

**Comment by robbiemu** [comment] 2024-10-20 17:20
check if libelf.so.1 ispresent on your Linux machine (it is usually cated in /usr/lib or /usr/lib64). if it is not present, install libutils package

**Comment by ic4-y** [comment] 2024-10-20 18:01
I am running this in docker. Maybe I am missing something, but why would it matter if my host machine has a linked library or not? Should I not look inside the container rather?

That being said, I am running NixOS on the host. Linked libraries might not be where you'd expect them to be. I am running docker containers here so that I have an independent environment from my host machine.

**Comment by skobkin** [comment] 2024-10-22 16:46
Looks like my #7320 is probably a duplicate of this.

So, just waiting for fixed image then?

**Closed** 2024-10-22 19:54 UTC
Labels: bug, docker
