### ISSUE TITLE
Getting Error: llama runner process has terminated: exit status 127

### ISSUE THREAD

**Issue by Blasserman** [ollama/ollama#6573] opened 2024-08-30 21:15 UTC
### What is the issue?

On two different aarch64 SBC's running Debian. One running Bookworm, one running bullseye. Both get the error when loading the model llama3.1 into memory with Ollama 0.3.8. The previous version ollama worked fine. 

dave@ai:~$ ollama -v
ollama version is 0.3.8
dave@ai:~$ ollama run llama3.1
Error: llama runner process has terminated: exit status 127
dave@ai:~$ 

### OS

Linux

### GPU

Other

### CPU

Other

### Ollama version

0.3.8

**Comment by Blasserman** [comment] 2024-08-30 21:17
They are both aarch64 CPU's. one is Rockchip, one is Raspberry Pi.

**Comment by pdevine** [comment] 2024-08-30 21:51
Dupe of #6541

**Closed by pdevine** 2024-08-30 21:51 UTC
Labels: bug
