### ISSUE TITLE
The "seed" is not working reliable for me.

### ISSUE THREAD

**Issue by oderwat** [ollama/ollama#1749] opened 2023-12-30 23:36 UTC
I am using a seed (int 1) for prompt generation with a mistral model, and it works not reliable. Instead, I get some interesting results with a pattern:

EDIT: It seems like this behavior is independent of the seed choice and the seeds are not working at all?

When freshly start `ollama serve` and send the exact same prompt together with a seed to "/api/generate" (stream: false) I always get three times the same reply. The fourth and all following replies are then different!

When I switch the model and make the same prompt to that, it also gives three of the same and then varying results!

As a workaround, I actually switch to another very small model and create a minimal embedding (is faster than doing an inference prompt) before doing the actual prompt and this gives me reliable results. Even if that actually works and is quite fast in my case, I think there is a problem that needs to be fixed.

I am on the current main [2a2fa3c](https://github.com/jmorganca/ollama/commit/2a2fa3c3298194f4f3790aade78df2f53d170d8e)

**Comment by technovangelist** [comment] 2024-01-02 16:26
Interesting, I tried out this code: 
```
async function test() {
	const body = {
		"model": "mistral", 
		"prompt": "list 3 synonyms for a sink", 
		"stream": false, 
		"options": {
			"seed": 12345, 
			"temperature": 0
		}
	};
	const response = await fetch("http://localhost:11434/api/generate", {
		"method": "POST", 
		"body": JSON.stringify(body), 
	});
	
	const out = await response.json();
	
	console.log(out.response)
}

test();
test();
test();
test();
test();
test();
test();
test();
test();
test();
```

When I leave out the temperature, I get somewhat random responses each time. But use the seed and temp and I get the same results every single time.

**Comment by BruceMacD** [comment] 2024-01-02 16:38
The suggestion above (using temperature) helps a lot, although I do occasionally see some variation here after may requests.

Some other things to note:
- There was a bug in `main` where seed wouldn't be set properly, which is fixed in #1761. If you weren't building from source this will not have been the issue.
- If you're setting `temperate` in the interactive `ollama run` the chat history will effect what is generated also.

**Comment by oderwat** [comment] 2024-01-02 17:09
I recompiled from main with the mentioned PR merged. Using temperature 0 I always get the same output, but for ANY seed, which is not what should be the case, should it?

@technovangelist have you tried other seeds?

**Comment by oderwat** [comment] 2024-01-02 17:16
@technovangelist This is what I get using the current main and you little script (pointing at my server and using 'dolphin2.2-mistral:7b-q4_K_M')

<img width="909" alt="image" src="https://github.com/jmorganca/ollama/assets/719156/13efced0-73eb-4fb5-9c21-aca30bd3d79d">

**Comment by oderwat** [comment] 2024-01-03 18:30
Using the newest main (a00367b2f92) I still can't get the seed to work reliable. But I wonder if that is "just me" or if this is a confirmed problem. From all my experiments it looks like as if there is no real support for a 'seed' or implemented in an unusable way.

**Comment by technovangelist** [comment] 2024-01-04 17:51
Thanks @oderwat for checking. I know @BruceMacD is looking into it. We added a bug label to the issue so we will continue investigating.

**Comment by jmorganca** [comment] 2024-02-20 01:36
@oderwat for consistent output both `seed` must be set to a given number, and `temperature` must be set to 0. Let me know if this doesn't help.

I've added some examples of reproducible outputs to `api.md`:

https://github.com/ollama/ollama/blob/main/docs/api.md#request-reproducible-outputs

**Closed by jmorganca** 2024-02-20 01:36 UTC
Labels: bug

**Comment by d-kleine** [comment] 2024-06-27 06:03
To make the output on the same OS reproducible, you need to set a context length with `num_ctx` to (otherwise the output slightly differs when not setting it)

Also, the having set `seed`, `temperature` to 0 and `num_ctx`, the output is deterministic and reproducible, but inconsistent over different OS. Might be related to llama.cpp: https://github.com/ggerganov/llama.cpp/discussions/2100

**Comment by CnBDM-Su** [comment] 2024-11-01 07:03
Same here. I am using llama3.1:70b.

here is my message :[{
                                "role": "user",
                                "content": 'give me a short joke',
                                "options": {
                                    "seed": 0,
                                    "temperature": 0
                                  }
                            }]

I got different response each time.

**Comment by jtyska** [comment] 2024-11-13 15:10
Hey! I'm still having this problem. When I set temperature to 0 and use different seed values, the generated content is always the same. Any clue on how to fix it? Here is the payload I'm using to generate content via API (/generate)

"model": "qwen2.5:72b",
            "prompt": "Generate something",
            "options":{
                "seed": 99, # here I change to 100, 101, 102, 103 anyvalue and the generated content is always the same
                "temperature":0
            },
            "stream": False 
            
            My ollama version is 0.4.1 got from the docker image on dockerhub.
            
           Could anyone give me a hand on this?

**Comment by d-kleine** [comment] 2024-11-13 15:42
@jtyska ou probably need to pass a fixed context length too as this is not set up in the template: https://ollama.com/library/qwen2:72b/blobs/f02dd72bb242. The reason is that the context length will be random then too, leading the different lengths (and therefore also tokens) generated.

So try this by adding:
```python
...
"num_ctx": 32_768
...
```
to your code and let us know is this fixes the issue for you.

**Comment by oderwat** [comment] 2024-11-13 15:48
It sounds counterintuitive that making more stuff "fixed" will suddenly create different outputs when they were the same with different seeds before.

**Comment by d-kleine** [comment] 2024-11-13 16:21
@oderwat Sorry, you are right – I was juggling too many things at once and got confused. The context length is indeed fixed, and what changes is the input or output length based on the prompt or generation settings.

@jtyska I just tested the settings in Ollama, you should be able to get consistent outputs per seed with the `seed` settings. If you you want variation across different seed, you need to increase the temperature to a value >0 (for instance `0.7`) by keep. So you settings would be:
```python
"model": "qwen2.5:72b",
"prompt": "Generate something",
"options":{
"seed": 99,
"temperature": 0.7 # increased
},
"stream": False
```

Then every generated output is consistent when using the same seed, but varies across different seeds.

**Comment by jtyska** [comment] 2024-11-13 17:06
If you increase the temperature, reproducibility will be impossible. The answer for the same seed, with temperature 0, should be the same, but different seeds, with temperature zero, should produce different responses. Isn't that right? Otherwise, what's the point of having a seed parameter?

**Comment by d-kleine** [comment] 2024-11-13 17:34
Please try out the settings I have provided, and let me know if that worked for you. 

> If you increase the temperature, reproducibility will be impossible. The answer for the same seed, with temperature 0, should be the same, but different seeds, with temperature zero, should produce different responses. Isn't that right? Otherwise, what's the point of having a seed parameter?

Regarding your question, that's not right - the seed initializes a random number generator used during text generation, changing which tokens will be chosen (i.e., for **temperature > 0**). A fixed seed ensures consistency and reproducibility in such cases. However, when **temperature = 0**, the model becomes fully deterministic (=always selecting the most likely tokens), meaning there is no randomness in token selection and changing the seed will not affect the output then.

**Comment by oderwat** [comment] 2024-11-13 17:38
@d-kleine That would mean that with a fixed seed the result of a fixed temperature should be deterministic?

**Comment by d-kleine** [comment] 2024-11-13 17:54
Depends what you mean by "fixed temperature". So for temp = 0, yes; And for temp > 1, only under ideal conditions (there can be different calculations due to underlying hardware differences or model architecture complexities though)

I think easier to distinfuish using **consistency** and **deterministism**:
* fixed seed: ensures **consistency** when randomness is involved 
* temp=0: guarantees **determinism**

So, both settings contribute to reproducibility but from different sides: the seed controls randomness when it's present, and temperature controls whether randomness exists at all.

**Comment by d-kleine** [comment] 2024-11-13 18:30
> Aha? Between different models and hardware? Really?

Yes, I was actually involved in some of those discussions around it, see for example https://github.com/ollama/ollama/pull/5760#issuecomment-2462917232 and https://github.com/ggerganov/llama.cpp/issues/8353#issuecomment-2304407109

> What I think what happens is the following:
> 
> The random generator used is not a (deterministic) pseudo random generator and that means the seed is useless if s more than one number needed.
> 
> Could that be the case?

In this case, no - most modern LLMs (like Qwen) use deterministic PRNG.

**Comment by jtyska** [comment] 2024-11-13 18:36
Thanks a lot @d-kleine I finally got it. I tested with a higher temperature and the same seed, and it indeed produced the same output!

**Comment by filijamz** [comment] 2025-03-01 16:06
I tried some experiments with llama3.2 with no memory (history) and random seed values. I kept asking for a riddle expecting a new riddle with a different seed each time. Instead, it responded with the exact same riddle each time. Am I misunderstanding what seed does?
