### ISSUE TITLE
How to make output consistent

### ISSUE THREAD

**Issue by Fei-Wang** [ollama/ollama#2014] opened 2024-01-16 10:03 UTC
Setting seed and temperature cannot make the output consistent.
<img width="1087" alt="image" src="https://github.com/jmorganca/ollama/assets/11441526/9a00ac1f-c120-4211-9b2e-fcec627f69e1">

**Comment by Fei-Wang** [comment] 2024-01-22 08:04
Hi @mxyng, could you please take a look at the Modelfile config I provided when you get a chance? 
Thanks!

**Comment by mxyng** [comment] 2024-01-22 17:43
@Fei-Wang what kind of model is `q4_0.bin`? The template may be incorrect. It should probably be something like this:

```
[INST] {{ .System }} {{ .Prompt }} [/INST]
```

`<s>` and `</s>` shouldn't be necessary and `{{ .Response }}` is (currently) ignored.

**Comment by Fei-Wang** [comment] 2024-01-23 06:19
Hey @mxyng,

I'm working with `q4_0.bin`, a finetuned llama2 model, and I've hit two snags:

1. I'm using `<s>` and `</s>` as per the guide on Hugging Face (https://huggingface.co/blog/codellama#promptersational-instructions). Did I get something wrong?

2. Changing the ModelFile to `llama2` hasn't fixed inconsistent outputs. See the screenshot below.

Any ideas?

<img width="1323" alt="Screenshot 2024-01-23 at 2 03 40 PM" src="https://github.com/jmorganca/ollama/assets/11441526/e5cd6da1-7481-46de-add0-ac70bc1f8362">

**Comment by pdevine** [comment] 2024-01-27 01:07
Closing this as a dupe of #1749

**Closed by pdevine** 2024-01-27 01:07 UTC
