### ISSUE TITLE
Ollama not use GPU

### ISSUE THREAD

**Issue by Mina4ever** [ollama/ollama#5035] opened 2024-06-13 21:58 UTC
### What is the issue?

I am using Ollama , it use CPU only and not use GPU, although I installed cuda v 12.5 and cudnn v 9.2.0 and I can check that python using gpu in liabrary like pytourch (result of command (>>> print(torch.backends.cudnn.is_available())
**True**, ), I have Nvidia 1050 ti and I am trying to runn llama3 8B model, i found this warning in ollamam server log "level=WARN source=gpu.go:177 msg="CPU does not have AVX or AVX2, disabling GPU support."

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.1.43

**Comment by kangkang721** [comment] 2024-06-13 23:57
解决了么？我也遇到同样的问题

**Comment by xinoer** [comment] 2024-06-14 02:42
I also encountered the same problemI also encountered the same problem, my Ollama version is the Windows installation version, version number 0.1.43

**Comment by melooy** [comment] 2024-06-14 02:57
I also encountered the same problemI also encountered the same problem, my Ollama version is the Windows installation version, version number 0.1.44

**Comment by Shbhom** [comment] 2024-06-14 13:59
Getting the same error, I'm running ollama on docker on arch linux, I've already installed nvidia-container-toolkit, and I'm able to run nvidia-smi command inside the container, and under the processes using GPU in nvidia-smi, there's no process using GPU inside the container, while I'm using ollama to run llama3.

**Comment by pdevine** [comment] 2024-06-14 17:00
Unfortunately you're running this on some pretty old hardware. The RTX 1050 Ti only has 4 GB of VRAM, so llama3 8B would be tight even at 4 bit quantization even if you had AVX on the CPU. That said, this is a dupe of #2187 . In the future we'll make it easy for you to recompile Ollama on your own w/o AVX support but w/ CUDA support.

**Closed by pdevine** 2024-06-14 17:00 UTC
Labels: bug

**Comment by Shbhom** [comment] 2024-06-14 17:12
@pdevine can you tell me why I'm not able to run it on my pc, I got a RTX 4080 Ti.

**Comment by dbl001** [comment] 2024-06-14 18:45
@pdevine Can ollama run llama3 utilizing the GPU? I am running ollama on an iMac 27" with an AMD Radeon Pro 5700 XT.  llama.cpp knows about the AMD GPU.
E.g. 
```
 ./main -m /Users/davidlaxer/llama.cpp/models/7B/ggml-model-q4_0.gguf -n 128 -ngl 1
Log start
main: build = 3051 (5921b8f0)
main: built with Apple clang version 15.0.0 (clang-1500.3.9.4) for x86_64-apple-darwin23.5.0
main: seed  = 1718377585
llama_model_loader: loaded meta data with 16 key-value pairs and 291 tensors from /Users/davidlaxer/llama.cpp/models/7B/ggml-model-q4_0.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = models
llama_model_loader: - kv   2:                       llama.context_length u32              = 2048
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 11008
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 32
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  10:                          general.file_type u32              = 2
llama_model_loader: - kv  11:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  13:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  15:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q4_0:  225 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_vocab: special tokens cache size = 259
llm_load_vocab: token to piece cache size = 0.3368 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 2048
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 32
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: n_embd_k_gqa     = 4096
llm_load_print_meta: n_embd_v_gqa     = 4096
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-06
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 11008
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 2048
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = Q4_0
llm_load_print_meta: model params     = 6.74 B
llm_load_print_meta: model size       = 3.56 GiB (4.54 BPW) 
llm_load_print_meta: general.name     = models
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.30 MiB
ggml_backend_metal_log_allocated_size: allocated buffer, size =   108.60 MiB, (  108.60 / 16368.00)
llm_load_tensors: offloading 1 repeating layers to GPU
llm_load_tensors: offloaded 1/33 layers to GPU
llm_load_tensors:      Metal buffer size =   108.60 MiB
llm_load_tensors:        CPU buffer size =  3539.27 MiB
.................................................................................................
llama_new_context_with_model: n_ctx      = 512
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
ggml_metal_init: allocating
ggml_metal_init: found device: AMD Radeon Pro 5700 XT
ggml_metal_init: picking default device: AMD Radeon Pro 5700 XT
ggml_metal_init: default.metallib not found, loading from source
ggml_metal_init: GGML_METAL_PATH_RESOURCES = nil
ggml_metal_init: loading '/Users/davidlaxer/ollama/llm/llama.cpp/ggml-metal.metal'
ggml_metal_init: GPU name:   AMD Radeon Pro 5700 XT
ggml_metal_init: GPU family: MTLGPUFamilyCommon3 (3003)
ggml_metal_init: GPU family: MTLGPUFamilyMetal3  (5001)
ggml_metal_init: simdgroup reduction support   = true
ggml_metal_init: simdgroup matrix mul. support = false
ggml_metal_init: hasUnifiedMemory              = false
ggml_metal_init: recommendedMaxWorkingSetSize  = 17163.09 MB
ggml_metal_init: skipping kernel_mul_mm_f32_f32                    (not supported)
ggml_metal_init: skipping kernel_mul_mm_f16_f32                    (not supported)
ggml_metal_init: skipping kernel_mul_mm_q4_0
...
```

**Comment by dvdblk** [comment] 2024-06-20 20:57
I'm having a similar issue. Two days ago I have started ollama (0.1.44) with Docker, used it for some text generation with `llama3:8b-instruct-q8_0`, everything went fine and it was generated on two GPUs. 

Today I wanted to use it again, but it did the generation on a CPU instead of GPU.  Same thing happened when I tried to use an embedding model. The solution was to **restart** the docker container...

**Comment by dhiltgen** [comment] 2024-06-20 22:55
@dvdblk if that happens again, you may want to check the host and see if the nvidia_uvm driver unloaded.  We recently had to add [this new logic](https://github.com/ollama/ollama/blob/main/scripts/install.sh#L314-L323) to our install script to make sure things stay loaded on driver 555 or newer.

**Comment by dvdblk** [comment] 2024-06-21 14:27
> @dvdblk if that happens again, you may want to check the host and see if the nvidia_uvm driver unloaded. We recently had to add [this new logic](https://github.com/ollama/ollama/blob/main/scripts/install.sh#L314-L323) to our install script to make sure things stay loaded on driver 555 or newer.

Thanks for the input. I'm on `535.171.04` right now. I vaguely remember an nvidia-driver issue from last year where the driver would stop working (unload?) after some time and it required a system reboot, but I have fixed this long time ago. 

I'm not sure how to reproduce ollama losing access to GPU but the container was up for 40+ hours and until it got restarted the generation was done on CPU. I also have a few other containers running that use very small amount of vram on GPUs and they kept working while ollama started suddenly using CPU. Will try to get some logs the next time.
