### ISSUE TITLE
gemma: unrecognized characters in the response

### ISSUE THREAD

**Issue by skywind3000** [ollama/ollama#2683] opened 2024-02-22 15:43 UTC
![image](https://github.com/ollama/ollama/assets/3035071/bbfbfbcc-a04b-44a8-b7b3-703f1b1acfcf)

What's that ?

model: gemma:7b

**Comment by jaifar530** [comment] 2024-02-22 15:53
it is Arabic language letters, very strang

**Comment by penguinpatroller** [comment] 2024-02-22 20:54
This is probably the same issue as #2650. Still unresolved.

**Comment by mxyng** [comment] 2024-02-23 01:26
Closing as duplicate of #2650

**Closed by mxyng** 2024-02-23 01:26 UTC
