### ISSUE TITLE
`/v1/embeddings` OpenAI compatible API endpoint

### ISSUE THREAD

**Issue by pamelafox** [ollama/ollama#2416] opened 2024-02-08 22:16 UTC
Your blog post mentions you're considering it. We'd love it so that we can point our RAG apps at ollama. Thanks!

**Comment by MuhammadHadiofficial** [comment] 2024-02-09 23:38
@pamelafox Its there now -> https://ollama.com/blog/openai-compatibility

**Comment by pamelafox** [comment] 2024-02-10 00:03
It specifically says that embeddings API is not yet supported on that page (at the bottom).

**Comment by glorat** [comment] 2024-02-12 14:19
One concrete point of incompatibility is the inability to pass in a vector of embedding requests. If one looks at the ollama source code, EmbeddingRequest clearly only takes in a single item rather than an array.

Would appreciate if maintainers would triage to bug / won't fix / feature request so I can adjust expectations accordingly. (Maintainers, you guys do a fantastic job with this project, any response is acceptable).

**Comment by odrobnik** [comment] 2024-04-19 18:23
So, why is the Ollama endpoint at `/api/embeddings` and not at `/v1/embeddings` where it should be to be compatible with OpenAI or for example LM Studio?

**Comment by john-c-kane** [comment] 2024-04-29 10:59
I found this issue because i was trying to use Ollama Embeddings API for the Microsoft Semantic Kernel Memory functionality using the OPENAI provider with Ollama URL but I discovered the application is sending JSON format to API as "model" and "input" but Ollama embeddings api expects "model" and "prompt". So not sure if this is being considered as part of this OPENAI interface compatibility request but wanted to make you aware.

**Comment by odrobnik** [comment] 2024-04-29 12:05
There is no `v1` embeddings endpoint yet, only the standard one at `api`

**Comment by yuriwa** [comment] 2024-05-01 20:47
I've just noticed the pull request [(2476)](https://github.com/ollama/ollama/pull/2476) and wanted to express my appreciation for the work put into it. Thank you for your contribution! Looking forward to its potential merge.

**Comment by jmatsushita** [comment] 2024-05-02 18:43
There seems to be an active PR for this https://github.com/ollama/ollama/pull/2925 by @tazarov  I haven't tested it yet.

**Comment by JpEncausse** [comment] 2024-05-26 13:51
Very curious of availability and capabilities.

My usecase is straight forward: 
- During BUILD I need to create Embeddings of a lot of content locally in order to give a try, reduce cost, and bootstrap a database.
- During RUN I'll calling online APIs when it's needed.

When Ollama will be compatible with `text-embedding-3-large`, `text-embedding-3-small` and `text-embedding-ada-002` it will open the door to run embedding both locally (with a good PC for Free) and Online

**Comment by cristoslc** [comment] 2024-06-06 03:46
I think I see two PRs related to this (https://github.com/ollama/ollama/pull/2925 and https://github.com/ollama/ollama/pull/3642). As others have said, the fact that the `api/embeddings` endpoint doesn't accept an array of inputs AND the difference in the request structure vs. OpenAI's structure (per https://github.com/ollama/ollama/issues/2416#issuecomment-2082426079) are both major blocks to using Ollama in a variety of RAG applications.  Any word on where those PRs are prioritized?

Thank you all for your hard work on the project!

**Comment by aletfa** [comment] 2024-06-26 17:06
+1 here. Please implement the complete compatibility

**Closed** 2024-07-16 20:36 UTC
Labels: feature request, compatibility, embeddings

**Comment by arch7tect** [comment] 2024-07-29 05:54
Here is temporary solution while v1/embeddings in ollama is broken
https://github.com/severian42/GraphRAG-Local-UI/blob/main/embedding_proxy.py

**Comment by royjhan** [comment] 2024-07-29 20:10
@JPMoresmau how are you calling v1/embeddings? I'm unable to reproduce the error, this code is working as expected

```
from openai import OpenAI
 
client = OpenAI(
    base_url='http://localhost:11434/v1/',
    api_key='ollama'
)

response = client.embeddings.create(
  model="all-minilm",
  input=["input1", "input2"],
)

print(response)
```
