### ISSUE TITLE
How to run Windows version Ollama on AMD GPU?

### ISSUE THREAD

**Issue by TM119** [ollama/ollama#2972] opened 2024-03-07 06:27 UTC
I have a W6800, apparently windows version Ollama is running models on CPU rather than GPU. Will AMD GPU be supported?

**Comment by pdevine** [comment] 2024-03-07 07:06
Closing as a dupe of #2598

**Closed by pdevine** 2024-03-07 07:06 UTC

**Comment by ravarcade** [comment] 2024-03-07 17:57
@TM119 You can test build from dhiltgen:
https://github.com/dhiltgen/ollama/releases
I just tested it on my 7800XT. 
Don't forget to install ROCm 5.7.
