### ISSUE TITLE
Please add olmo 7b

### ISSUE THREAD

**Issue by ChangjingZhang** [ollama/ollama#3456] opened 2024-04-02 12:58 UTC
### What model would you like?

OLMO 7b

**Comment by pdevine** [comment] 2024-04-16 23:16
Dupe of #2337

**Closed by pdevine** 2024-04-16 23:16 UTC
Labels: model request

**Comment by userforsource** [comment] 2024-04-20 13:04
https://github.com/ggerganov/llama.cpp/pull/6741
Now

    Hello, as referenced in issue https://github.com/ollama/ollama/issues/2287 the models supported are the ones llama.cpp supports. Check their forum and see if they support it.

This is now support in llama.cpp can you new support into ollama thanks
