### ISSUE TITLE
Model Library per api call

### ISSUE THREAD

**Issue by Leon-Sander** [ollama/ollama#6796] opened 2024-09-13 21:01 UTC
It would be nice to have an api endpoint which could list all possible models as seen on [ollama.com/library](https://ollama.com/library)

**Comment by rick-github** [comment] 2024-09-13 23:30
https://github.com/ollama/ollama/issues/2022

**Comment by pdevine** [comment] 2024-09-17 17:41
Hey @Leon-Sander . It's definitely something that we're looking at. I'll close this as a dupe of #2022

**Closed by pdevine** 2024-09-17 17:41 UTC
Labels: feature request
