### ISSUE TITLE
Ollama create fails when using a utf16 Modelfile

### ISSUE THREAD

**Issue by dehlong** [ollama/ollama#4503] opened 2024-05-17 18:35 UTC
### What is the issue?

Hello,
I try to create a new model and mo matter what the model file is, 90% of the time I get:
Error: command must be one of "from", "license", "template", "system", "adapter", "parameter", or "message"

Is there any solution to this?
This is my modelfile:
FROM llama3
PARAMETER temperature 1
PARAMETER num_ctx 4096
SYSTEM You are Mario from super mario bros, acting as an assistant.

### OS

Linux

### GPU

Other

### CPU

Intel

### Ollama version

0.1.38

**Comment by brt-yilmaz** [comment] 2024-05-17 23:08
Be careful about the spaces, first try to copy modelfile's string from : https://github.com/ollama/ollama/blob/main/docs/api.md#request-13
And than customise it.

**Comment by pdevine** [comment] 2024-05-18 22:54
@dehlong I just created a model using that modelfile and it worked fine. Was there anything else you had added into it?

**Comment by pdevine** [comment] 2024-05-18 22:55
```% ollama create -f ~/Modelfiles/Mariomodelfile pdevine/mario
transferring model data
using existing layer sha256:00e1317cbf74d901080d7100f57580ba8dd8de57203072dc6f668324ba545f29
using existing layer sha256:4fa551d4f938f68b8c1e6afa9d28befb70e3f33f75d0753248d530364aeea40f
using existing layer sha256:8ab4849b038cf0abc5b1c9b8ee1443dca6b93a045c2272180d985126eb40bf6f
creating new layer sha256:278f3e552ef89955f0e5b42c48d52a37794179dc28d1caff2d5b8e8ff133e158
creating new layer sha256:40440ec37ef2b2862d182b7926987668264d13ff9c97407acf36a44106997f8f
creating new layer sha256:bd886c34b18cdaf5ed2d30acb3de0d3010c5546c6b1d259d5e75b2efe4a85c70
writing manifest
success
% ollama run pdevine/mario
>>> hi there
"It's-a me, Mario! Welcome to our little corner of the Mushroom Kingdom! I'm-a here to help you with anything you might need. Whether it's rescuing Princess Peach
from Bowser or finding the hidden Warp Pipes, I'm your guy! So, what seems to be the problem? Need some power-ups or maybe a map to the nearest castle?"
```

The Modelfile looks like:
```
FROM llama3
PARAMETER temperature 1
PARAMETER num_ctx 4096
SYSTEM You are Mario from super mario bros, acting as an assistant.
```

**Comment by dehlong** [comment] 2024-05-19 15:32
Nope, it was just this.

**Comment by duck1y** [comment] 2024-05-19 19:59
I've been having the same issue on Windows for a few days. 

At this point I'm sure it's not an issue with the model file. 
use show --modelfile to copy the modelfile from an existing model and then use ollama create test58 -f ./Modelfile I get the same Error: command must be one of "from", "license", "template", "system", "adapter", "parameter", or "message" that Dehlong does. 

I've uninstalled and reinstalled ollama. Using OpenWebUI model builder does work, but I need to use ollama create for reasons. 

@dehlong I'll let you know if I trip into an answer but at this point I feel pretty stuck.

**Comment by pdevine** [comment] 2024-05-19 20:07
I'm wondering if this is just a problem w/ msdos files adding a carriage return+line feed to the end of each line in the file. Can either of you add the file to the issue? I think you should be able to drag+drop it into a comment.

**Comment by duck1y** [comment] 2024-05-19 20:21
[Modelfile.zip](https://github.com/ollama/ollama/files/15370655/Modelfile.zip)

Does this work? 
I realize now the file type is showing up in windows explorer as a Program PhotonWorkShop file (anycubic slicer). unclear to me if this is a problem or not, unclear to me if it's likely to be the same issue Dehlong has considering he's on linux.

**Comment by pdevine** [comment] 2024-05-19 20:37
@duck1y Perfect. I was able to reproduce the problem using that file. Will try to sort out a fix now.

**Comment by pdevine** [comment] 2024-05-19 22:16
The problem turns out to be the file is a utf16 file and we're trying to parse it as a utf8 file. The temporary work around is you can convert the file in powershell using the command:

```
powershell "Get-Content 'Modelfile' | Out-File 'Newmodelfile' -Encoding ascii"
```

I have a fix I'm working on, which hopefully we can get into `0.1.39`.

**Comment by duck1y** [comment] 2024-05-19 22:24
@pdevine the workaround worked for me - thank you so much!! I appreciate you!!! 

Is it clear that this is likely to be the source of @dehlong 's issue aswell? 
@dehlong can you confirm this workaround works for you? I would hate to have hijacked your thread and left you without a solution. 

Ty both :):)

**Comment by pdevine** [comment] 2024-05-19 22:31
@duck1y it's almost certainly the same problem.

**Comment by Anorid** [comment] 2024-05-20 03:37
@duck1y 

Hello,sir,This is my running command.,I see that it was successfully created.,But when it runs, an error is reported.,ollama's log says the format is wrong.,But similar qwen1.5 is also used in this format.,May I ask the big guy if there is any other reason for the error.

root@autodl-container-c438119a3c-80821c25:~/autodl-tmp/merge5-1# ollama create example -f Modelfile
transferring model data 
using existing layer sha256:1c751709783923dab2b876d5c5c2ca36d4e205cfef7d88988df45752cb91f245 
creating new layer sha256:68693db5eb3e0501c644080a545730fc93d2ca2dfddf03633642b99f3a1f0e3c 
creating new layer sha256:520c0ce2f1457a8d9dc581516a07afa9d897f3777147c60d41f0a7c29fb5afad 
writing manifest 
success 
root@autodl-container-c438119a3c-80821c25:~/autodl-tmp/merge5-1# ollama run example
Error: llama runner process has terminated: signal: aborted (core dumped) 

time=2024-05-20T11:33:06.243+08:00 level=INFO source=memory.go:133 msg="offload to gpu" layers.requested=-1 layers.real=41 memory.available="47.3 GiB" memory.required.full="9.7 GiB" memory.required.partial="9.7 GiB" memory.required.kv="1.6 GiB" memory.weights.total="7.2 GiB" memory.weights.repeating="6.6 GiB" memory.weights.nonrepeating="609.1 MiB" memory.graph.full="307.0 MiB" memory.graph.partial="916.1 MiB"
time=2024-05-20T11:33:06.244+08:00 level=INFO source=memory.go:133 msg="offload to gpu" layers.requested=-1 layers.real=41 memory.available="47.3 GiB" memory.required.full="9.7 GiB" memory.required.partial="9.7 GiB" memory.required.kv="1.6 GiB" memory.weights.total="7.2 GiB" memory.weights.repeating="6.6 GiB" memory.weights.nonrepeating="609.1 MiB" memory.graph.full="307.0 MiB" memory.graph.partial="916.1 MiB"
time=2024-05-20T11:33:06.244+08:00 level=INFO source=server.go:320 msg="starting llama server" cmd="/tmp/ollama2749468660/runners/cuda_v11/ollama_llama_server --model /root/autodl-tmp/model/blobs/sha256-1c751709783923dab2b876d5c5c2ca36d4e205cfef7d88988df45752cb91f245 --ctx-size 2048 --batch-size 512 --embedding --log-disable --n-gpu-layers 41 --parallel 1 --port 39195"
time=2024-05-20T11:33:06.245+08:00 level=INFO source=sched.go:338 msg="loaded runners" count=1
time=2024-05-20T11:33:06.245+08:00 level=INFO source=server.go:504 msg="waiting for llama runner to start responding"
time=2024-05-20T11:33:06.245+08:00 level=INFO source=server.go:540 msg="waiting for server to become available" status="llm server error"
INFO [main] build info | build=1 commit="952d03d" tid="140637096448000" timestamp=1716175986
INFO [main] system info | n_threads=64 n_threads_batch=-1 system_info="AVX = 1 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | " tid="140637096448000" timestamp=1716175986 total_threads=128
INFO [main] HTTP server listening | hostname="127.0.0.1" n_threads_http="127" port="39195" tid="140637096448000" timestamp=1716175986
llama_model_loader: loaded meta data with 21 key-value pairs and 483 tensors from /root/autodl-tmp/model/blobs/sha256-1c751709783923dab2b876d5c5c2ca36d4e205cfef7d88988df45752cb91f245 (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = qwen2
llama_model_loader: - kv   1:                               general.name str              = merge5-1
llama_model_loader: - kv   2:                          qwen2.block_count u32              = 40
llama_model_loader: - kv   3:                       qwen2.context_length u32              = 32768
llama_model_loader: - kv   4:                     qwen2.embedding_length u32              = 5120
llama_model_loader: - kv   5:                  qwen2.feed_forward_length u32              = 13696
llama_model_loader: - kv   6:                 qwen2.attention.head_count u32              = 40
llama_model_loader: - kv   7:              qwen2.attention.head_count_kv u32              = 40
llama_model_loader: - kv   8:                       qwen2.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv   9:     qwen2.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  10:                          general.file_type u32              = 2
llama_model_loader: - kv  11:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  12:                         tokenizer.ggml.pre str              = qwen2
llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr[str,152064]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr[i32,152064]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  15:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  16:                tokenizer.ggml.eos_token_id u32              = 151643
llama_model_loader: - kv  17:            tokenizer.ggml.padding_token_id u32              = 151643
llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 151643
llama_model_loader: - kv  19:                    tokenizer.chat_template str              = {% for message in messages %}{% if lo...
llama_model_loader: - kv  20:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:  201 tensors
llama_model_loader: - type q4_0:  281 tensors
llama_model_loader: - type q6_K:    1 tensors
time=2024-05-20T11:33:06.497+08:00 level=INFO source=server.go:540 msg="waiting for server to become available" status="llm server loading model"
llama_model_load: error loading model: error loading model vocabulary: unknown pre-tokenizer type: 'qwen2'
llama_load_model_from_file: exception loading model
terminate called after throwing an instance of 'std::runtime_error'
  what():  error loading model vocabulary: unknown pre-tokenizer type: 'qwen2'
time=2024-05-20T11:33:06.872+08:00 level=INFO source=server.go:540 msg="waiting for server to become available" status="llm server error"
time=2024-05-20T11:33:07.122+08:00 level=ERROR source=sched.go:344 msg="error loading llama server" error="llama runner process has terminated: signal: aborted (core dumped) "
[GIN] 2024/05/20 - 11:33:07 | 500 |   2.21829574s |       127.0.0.1 | POST     "/api/chat"
time=2024-05-20T11:33:12.234+08:00 level=WARN source=sched.go:512 msg="gpu VRAM usage didn't recover within timeout" seconds=5.112074522

**Comment by Anorid** [comment] 2024-05-20 03:38
@pdevine If you can, the big guy can also help look at this error

**Comment by pdevine** [comment] 2024-05-20 04:45
@Anorid can you create a new issue for that problem and post the Modelfile along with any relevant info (like if you're trying to use a converted model where you got the weights from)? This is definitely a different issue than the one you posted.

**Comment by Anorid** [comment] 2024-05-20 04:49
I've created a new issue and posted the relevant information
#4529

**Closed** 2024-05-20 18:26 UTC
Labels: bug

**Comment by Patrickeik** [comment] 2024-05-25 10:58
sorry. i try to do as instructed. still error: get-content LLMteacher-modelfile | out-file LLMtest -Encoding ascii
PS C:\Users\p\Documents\testing> ollama create LLMTeacher -f LLMtest 

Error: command must be one of "from", "license", "template", "system", "adapter", "parameter", or "message"

what do i do wrong

**Comment by Patrickeik** [comment] 2024-05-28 11:13
here are more details:
PS C:\Users\peike\ollama> ollama show llama3 --modelfile > test
PS C:\Users\peike\ollama> ollama create ll3teacher -f test

Error: command must be one of "from", "license", "template", "system", "adapter", "parameter", or "message"
PS C:\Users\peike\ollama> Get-Content test | Out-File newtest -Encoding ascii
PS C:\Users\peike\ollama> ollama create ll3teacher -f newtest

Error: command must be one of "from", "license", "template", "system", "adapter", "parameter", or "message"
PS C:\Users\peike\ollama>

**Comment by donaldafeith** [comment] 2024-05-30 11:07
For anyone having problems creating a model...
Get a text file put in it
FROM ./themodelfileyouwant 
save text file
rename the text file Modelfile (no txt extension)
then go to cmd
ollama create thenameyouwanttonameyourmodel -f Modelfile
Hit enter and wait for the magic.

Not sure why it's not told in a straightforward manner but that's how I do it. Works great.

**Comment by pdevine** [comment] 2024-05-30 17:49
This should be fixed w/ `0.1.39` which now can parse a utf16 file (albeit _only_ w/ 8 bit characters). There's another PR coming for allowing utf16 characters in the modelfile itself.

**Comment by Patrickeik** [comment] 2024-05-30 19:14
thank you both!. workaround helped me! thank you!

**Comment by Ajun0302** [comment] 2024-10-29 02:16
PS C:\Users\32960> cd .\Desktop\
PS C:\Users\32960\Desktop> cd .\iict\
PS C:\Users\32960\Desktop\iict> cd .\lightRAG\
PS C:\Users\32960\Desktop\iict\lightRAG> powershell "Get-Content 'Modelfile' | Out-File 'Newmodelfile' -Encoding ascii"
PS C:\Users\32960\Desktop\iict\lightRAG>  ollama create qwen2m -f Newmodelfile

Error: command must be one of "from", "license", "template", "system", "adapter", "parameter", or "message"
PS C:\Users\32960\Desktop\iict\lightRAG>

**Comment by Ajun0302** [comment] 2024-10-29 02:17
how to "FROM ./themodelfileyouwant"?

**Comment by Moxie15** [comment] 2024-12-13 23:37
im still having the problem on Windows 11 
![image](https://github.com/user-attachments/assets/b05fc2fc-dcd4-4ab9-acf6-337fc2018e5d)
![image](https://github.com/user-attachments/assets/8bdce6b0-ec90-4c1f-8f38-46d9f4cba1a4)
