### ISSUE TITLE
Ollama异常终止

### ISSUE THREAD

**Issue by GeYingzhen01** [ollama/ollama#2930] opened 2024-03-05 09:08 UTC
English:
After upgrading to version 0.1.27, there has been a noticeable improvement in performance. Although the generation speed is not very fast, the program runs without significant lag. However, Ollama terminates automatically during operation.

中文：
在升级到0.1.27版本之后，性能有了明显的提升。虽然生成速度还不是很快，但程序运行没有明显卡顿。然而，在运行期间，Ollama会自动终止。
![image](https://github.com/ollama/ollama/assets/155865563/4dce4627-71a6-4351-8e69-84b652dc658a)
![image](https://github.com/ollama/ollama/assets/155865563/61555c50-d01c-4861-a539-4867a621dab1)

**Comment by GeYingzhen01** [comment] 2024-03-05 10:07
English:
It should be unresponsive, and a prompt line appears after pressing Ctrl+C:
中文：
应该是无响应，按Ctrl+C后 出现提示行：
![image](https://github.com/ollama/ollama/assets/155865563/6de72457-aff9-4b6b-9f32-274031231169)

**Comment by remy415** [comment] 2024-03-05 21:24
Please provide: 

- Configuration information
  - CPU, RAM, GPU
- Server log
  - ollama service logs

Additionally: are you running it CPU only, or CPU + GPU?

**Comment by GeYingzhen01** [comment] 2024-03-06 08:28
English：
Thank you very much. Today, when I tested the Llama2, gemma:2b, gemma:7b, and Neural Chat models, the system ran smoothly and did not experience the previous program freezing issues. However, occasionally, commands entered would execute but not display on the screen, or a new line would incorrectly display the previous line's information. Since the command line did not promptly clear the previous display content, this caused some confusion in the displayed results.

中文：
非常感谢，今天我测试了Llama2、gemma:2b、gemma:7b以及Neural Chat模型，在整个过程中，系统运行流畅，并没有再出现过去的程序冻结现象。然而，偶尔输入的指令虽然得到执行却不显示在屏幕上，或是新的一行错误地展示了上一行的信息，由于命令行未能及时清空之前的显示内容，这使得显示结果产生了一些混淆。
![image](https://github.com/ollama/ollama/assets/155865563/ab91b024-1fa2-4c40-99dd-3a1f50b752f0)

**Comment by GeYingzhen01** [comment] 2024-03-07 02:33
英文：
When using the Backspace key, the content of the text line cannot be completely deleted, with the last one or two characters remaining visible.

中文：
使用Backspace键时，输入的文本行内容不能完全被删除，最后一两个字符仍然会显示。
![image](https://github.com/ollama/ollama/assets/155865563/6143714c-bd89-438f-ba9d-70c6ce59f6b9)

**Comment by remy415** [comment] 2024-03-07 03:56
I think it may be related to how Windows command line handles different keyboard inputs (UTF parsing). Try running it from Powershell and see if that fixes it

**Comment by GeYingzhen01** [comment] 2024-03-08 01:26
English:
There are issues with clearing Chinese content in Powershell, whereas clearing English content works fine.

中文：
在Powershell中，清除中文内容时存在问题，但清除英文内容则没有问题。

![image](https://github.com/ollama/ollama/assets/155865563/80f979ec-f98a-4b9e-8284-add1002a96f6)




issues 2：
If Ollama is set to "Run this program as an administrator," it has no effect when executing commands (whether in the Command Prompt or PowerShell).

问题2：如果将Ollama设置为“以管理员身份运行此程序”，在执行命令时（无论是在命令提示符还是Powershell中）都不起作用。
![image](https://github.com/ollama/ollama/assets/155865563/7df859ce-6566-4556-b131-ffe1bbf2a194)
![image](https://github.com/ollama/ollama/assets/155865563/1755f7ce-08a1-4fa4-9de0-4aa675d195c3)

**Comment by remy415** [comment] 2024-03-08 13:40
Okay, it seems like it may have difficulty with Chinese characters. I would be interested to see if the issue is present on other OS or just when run on Windows. Just a guess, but maybe it’s related to GIN or a UTF configuration. I am assuming other Chinese character programs work correctly for you in the terminals. 

> Issues 2:

I don’t think ollama needs to run as administrator. You should be able to run it as a standard user.

**Comment by remy415** [comment] 2024-03-08 14:52
@GeYingzhen01 Have you checked the server logs?

From [ollama Windows guide](https://github.com/ollama/ollama/blob/main/docs/windows.md)
```
While we're in preview, OLLAMA_DEBUG is always enabled, which adds a "view logs" menu item to the app, and increses logging for the GUI app and server.

Ollama on Windows stores files in a few different locations. You can view them in the explorer window by hitting <cmd>+R and type in:

explorer %LOCALAPPDATA%\Ollama contains logs, and downloaded updates
app.log contains logs from the GUI application
server.log contains the server logs
upgrade.log contains log output for upgrades
```

**Comment by GeYingzhen01** [comment] 2024-03-09 05:37
English:
In Ubuntu 20.04, there are also issues with clearing Chinese content in the terminal.

中文：
在Ubuntu20.04中，同样终端清除中文内容时存在问题
![image](https://github.com/ollama/ollama/assets/155865563/650cd9c6-bea2-4eff-b259-a1978c15bc01)


windows 10  app.log
[app.log](https://github.com/ollama/ollama/files/14545085/app.log)

windows 10  server.log
[server.log](https://github.com/ollama/ollama/files/14545086/server.log)

ubuntu 20.04  logs:
`-- Logs begin at Fri 2021-03-12 12:25:48 CST, end at Sat 2024-03-09 13:34:08 CST. --
3月 09 10:41:22 gyz-ohos systemd[1]: Started Ollama Service.
3月 09 10:41:22 gyz-ohos ollama[5717]: Couldn't find '/usr/share/ollama/.ollama/id_ed25519'. Generating new private key.
3月 09 10:41:22 gyz-ohos ollama[5717]: Your new public key is:
3月 09 10:41:22 gyz-ohos ollama[5717]: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF2iuJ+ajndeFxYfFTI4obUUxqaIP+HMwUrn/qZBIwB9
3月 09 10:41:22 gyz-ohos ollama[5717]: time=2024-03-09T10:41:22.854+08:00 level=INFO source=images.go:710 msg="total blobs: 0"
3月 09 10:41:22 gyz-ohos ollama[5717]: time=2024-03-09T10:41:22.855+08:00 level=INFO source=images.go:717 msg="total unused blobs removed: 0"
3月 09 10:41:22 gyz-ohos ollama[5717]: time=2024-03-09T10:41:22.855+08:00 level=INFO source=routes.go:1021 msg="Listening on 127.0.0.1:11434 (version 0>
3月 09 10:41:22 gyz-ohos ollama[5717]: time=2024-03-09T10:41:22.855+08:00 level=INFO source=payload_common.go:107 msg="Extracting dynamic libraries..."
3月 09 10:41:29 gyz-ohos ollama[5717]: time=2024-03-09T10:41:29.043+08:00 level=INFO source=payload_common.go:146 msg="Dynamic LLM libraries [rocm_v6 c>
3月 09 10:41:29 gyz-ohos ollama[5717]: time=2024-03-09T10:41:29.043+08:00 level=INFO source=gpu.go:94 msg="Detecting GPU type"
3月 09 10:41:29 gyz-ohos ollama[5717]: time=2024-03-09T10:41:29.043+08:00 level=INFO source=gpu.go:265 msg="Searching for GPU management library libnvi>
3月 09 10:41:29 gyz-ohos ollama[5717]: time=2024-03-09T10:41:29.047+08:00 level=INFO source=gpu.go:311 msg="Discovered GPU libraries: []"
3月 09 10:41:29 gyz-ohos ollama[5717]: time=2024-03-09T10:41:29.047+08:00 level=INFO source=gpu.go:265 msg="Searching for GPU management library libroc>
3月 09 10:41:29 gyz-ohos ollama[5717]: time=2024-03-09T10:41:29.048+08:00 level=INFO source=gpu.go:311 msg="Discovered GPU libraries: []"
3月 09 10:41:29 gyz-ohos ollama[5717]: time=2024-03-09T10:41:29.048+08:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
3月 09 10:41:29 gyz-ohos ollama[5717]: time=2024-03-09T10:41:29.048+08:00 level=INFO source=routes.go:1044 msg="no GPU detected"
3月 09 10:41:55 gyz-ohos ollama[5717]: [GIN] 2024/03/09 - 10:41:55 | 200 |      30.682µs |       127.0.0.1 | HEAD     "/"
3月 09 10:41:55 gyz-ohos ollama[5717]: [GIN] 2024/03/09 - 10:41:55 | 404 |     100.119µs |       127.0.0.1 | POST     "/api/show"
3月 09 10:41:59 gyz-ohos ollama[5717]: time=2024-03-09T10:41:59.803+08:00 level=INFO source=download.go:136 msg="downloading c1864a5eb193 in 17 100 MB >
3月 09 10:46:09 gyz-ohos ollama[5717]: time=2024-03-09T10:46:09.804+08:00 level=INFO source=download.go:250 msg="c1864a5eb193 part 16 stalled; retrying"
3月 09 10:46:16 gyz-ohos ollama[5717]: time=2024-03-09T10:46:16.803+08:00 level=INFO source=download.go:250 msg="c1864a5eb193 part 10 stalled; retrying"
3月 09 10:48:20 gyz-ohos ollama[5717]: time=2024-03-09T10:48:20.894+08:00 level=INFO source=download.go:178 msg="c1864a5eb193 part 1 attempt 0 failed: >
3月 09 10:51:51 gyz-ohos ollama[5717]: time=2024-03-09T10:51:51.542+08:00 level=INFO source=download.go:178 msg="c1864a5eb193 part 4 attempt 0 failed: >
3月 09 10:56:30 gyz-ohos ollama[5717]: time=2024-03-09T10:56:30.514+08:00 level=INFO source=download.go:136 msg="downloading 097a36493f71 in 1 8.4 KB p>
3月 09 10:56:34 gyz-ohos ollama[5717]: time=2024-03-09T10:56:34.759+08:00 level=INFO source=download.go:136 msg="downloading 109037bec39c in 1 136 B pa>
3月 09 10:56:39 gyz-ohos ollama[5717]: time=2024-03-09T10:56:39.533+08:00 level=INFO source=download.go:136 msg="downloading 22a838ceb7fb in 1 84 B par>
3月 09 10:56:42 gyz-ohos ollama[5717]: time=2024-03-09T10:56:42.777+08:00 level=INFO source=download.go:136 msg="downloading 887433b89a90 in 1 483 B pa>
3月 09 10:56:52 gyz-ohos ollama[5717]: [GIN] 2024/03/09 - 10:56:52 | 200 |        14m57s |       127.0.0.1 | POST     "/api/pull"
3月 09 10:56:52 gyz-ohos ollama[5717]: [GIN] 2024/03/09 - 10:56:52 | 200 |      642.76µs |       127.0.0.1 | POST     "/api/show"
3月 09 10:56:52 gyz-ohos ollama[5717]: [GIN] 2024/03/09 - 10:56:52 | 200 |     422.915µs |       127.0.0.1 | POST     "/api/show"
3月 09 10:56:54 gyz-ohos ollama[5717]: time=2024-03-09T10:56:54.490+08:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
3月 09 10:56:54 gyz-ohos ollama[5717]: time=2024-03-09T10:56:54.490+08:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
3月 09 10:56:54 gyz-ohos ollama[5717]: time=2024-03-09T10:56:54.490+08:00 level=INFO source=llm.go:77 msg="GPU not available, falling back to CPU"
3月 09 10:56:54 gyz-ohos ollama[5717]: time=2024-03-09T10:56:54.493+08:00 level=INFO source=dyn_ext_server.go:90 msg="Loading Dynamic llm server: /tmp/>
3月 09 10:56:54 gyz-ohos ollama[5717]: time=2024-03-09T10:56:54.493+08:00 level=INFO source=dyn_ext_server.go:150 msg="Initializing llama server"
3月 09 10:56:54 gyz-ohos ollama[5717]: llama_model_loader: loaded meta data with 21 key-value pairs and 164 tensors from /usr/share/ollama/.ollama/mode>
3月 09 10:56:54 gyz-ohos ollama[5717]: llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
3月 09 10:56:54 gyz-ohos ollama[5717]: llama_model_loader: - kv   0:                       general.architecture str              = gemma
3月 09 10:56:54 gyz-ohos ollama[5717]: llama_model_loader: - kv   1:                               general.name str              = gemma-2b-it
3月 09 10:56:54 gyz-ohos ollama[5717]: llama_model_loader: - kv   2:                       gemma.context_length u32              = 8192
3月 09 10:56:54 gyz-ohos ollama[5717]: llama_model_loader: - kv   3:                          gemma.block_count u32              = 18
3月 09 10:56:54 gyz-ohos ollama[5717]: llama_model_loader: - kv   4:                     gemma.embedding_length u32              = 2048
3月 09 10:56:54 gyz-ohos ollama[5717]: llama_model_loader: - kv   5:                  gemma.feed_forward_length u32              = 16384
3月 09 10:56:54 gyz-ohos ollama[5717]: llama_model_loader: - kv   6:                 gemma.attention.head_count u32              = 8
3月 09 10:56:54 gyz-ohos ollama[5717]: llama_model_loader: - kv   7:              gemma.attention.head_count_kv u32              = 1
3月 09 10:56:54 gyz-ohos ollama[5717]: llama_model_loader: - kv   8:                 gemma.attention.key_length u32              = 256
3月 09 10:56:54 gyz-ohos ollama[5717]: llama_model_loader: - kv   9:               gemma.attention.value_length u32              = 256
3月 09 10:56:54 gyz-ohos ollama[5717]: llama_model_loader: - kv  10:     gemma.attention.layer_norm_rms_epsilon f32              = 0.000001
3月 09 10:56:54 gyz-ohos ollama[5717]: llama_model_loader: - kv  11:                       tokenizer.ggml.model str              = llama
3月 09 10:56:54 gyz-ohos ollama[5717]: llama_model_loader: - kv  12:                tokenizer.ggml.bos_token_id u32              = 2
3月 09 10:56:54 gyz-ohos ollama[5717]: llama_model_loader: - kv  13:                tokenizer.ggml.eos_token_id u32              = 1
3月 09 10:56:54 gyz-ohos ollama[5717]: llama_model_loader: - kv  14:            tokenizer.ggml.padding_token_id u32              = 0
3月 09 10:56:54 gyz-ohos ollama[5717]: llama_model_loader: - kv  15:            tokenizer.ggml.unknown_token_id u32              = 3
3月 09 10:56:54 gyz-ohos ollama[5717]: llama_model_loader: - kv  16:                      tokenizer.ggml.tokens arr[str,256128]  = ["<pad>", "<eos>", ">
3月 09 10:56:55 gyz-ohos ollama[5717]: llama_model_loader: - kv  17:                      tokenizer.ggml.scores arr[f32,256128]  = [0.000000, 0.000000,>
3月 09 10:56:55 gyz-ohos ollama[5717]: llama_model_loader: - kv  18:                  tokenizer.ggml.token_type arr[i32,256128]  = [3, 3, 3, 2, 1, 1, 1>
3月 09 10:56:55 gyz-ohos ollama[5717]: llama_model_loader: - kv  19:               general.quantization_version u32              = 2
3月 09 10:56:55 gyz-ohos ollama[5717]: llama_model_loader: - kv  20:                          general.file_type u32              = 2
3月 09 10:56:55 gyz-ohos ollama[5717]: llama_model_loader: - type  f32:   37 tensors
3月 09 10:56:55 gyz-ohos ollama[5717]: llama_model_loader: - type q4_0:  126 tensors
3月 09 10:56:55 gyz-ohos ollama[5717]: llama_model_loader: - type q8_0:    1 tensors
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_vocab: mismatch in special tokens definition ( 544/256128 vs 388/256128 ).
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: format           = GGUF V3 (latest)
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: arch             = gemma
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: vocab type       = SPM
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: n_vocab          = 256128
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: n_merges         = 0
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: n_ctx_train      = 8192
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: n_embd           = 2048
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: n_head           = 8
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: n_head_kv        = 1
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: n_layer          = 18
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: n_rot            = 256
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: n_embd_head_k    = 256
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: n_embd_head_v    = 256
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: n_gqa            = 8
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: n_embd_k_gqa     = 256
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: n_embd_v_gqa     = 256
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: f_norm_eps       = 0.0e+00
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: f_norm_rms_eps   = 1.0e-06
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: f_clamp_kqv      = 0.0e+00
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: f_max_alibi_bias = 0.0e+00
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: n_ff             = 16384
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: n_expert         = 0
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: n_expert_used    = 0
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: pooling type     = 0
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: rope type        = 2
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: rope scaling     = linear
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: freq_base_train  = 10000.0
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: freq_scale_train = 1
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: n_yarn_orig_ctx  = 8192
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: rope_finetuned   = unknown
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: model type       = 2B
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: model ftype      = Q4_0
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: model params     = 2.51 B
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: model size       = 1.56 GiB (5.34 BPW)
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: general.name     = gemma-2b-it
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: BOS token        = 2 '<bos>'
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: EOS token        = 1 '<eos>'
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: UNK token        = 3 '<unk>'
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: PAD token        = 0 '<pad>'
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_print_meta: LF token         = 227 '<0x0A>'
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_tensors: ggml ctx size =    0.06 MiB
3月 09 10:56:55 gyz-ohos ollama[5717]: llm_load_tensors:        CPU buffer size =  1594.93 MiB
3月 09 10:56:55 gyz-ohos ollama[5717]: .....................................................
3月 09 10:56:55 gyz-ohos ollama[5717]: llama_new_context_with_model: n_ctx      = 2048
3月 09 10:56:55 gyz-ohos ollama[5717]: llama_new_context_with_model: freq_base  = 10000.0
3月 09 10:56:55 gyz-ohos ollama[5717]: llama_new_context_with_model: freq_scale = 1
3月 09 10:56:55 gyz-ohos ollama[5717]: llama_kv_cache_init:        CPU KV buffer size =    36.00 MiB
3月 09 10:56:55 gyz-ohos ollama[5717]: llama_new_context_with_model: KV self size  =   36.00 MiB, K (f16):   18.00 MiB, V (f16):   18.00 MiB
3月 09 10:56:55 gyz-ohos ollama[5717]: llama_new_context_with_model:        CPU input buffer size   =     9.02 MiB
3月 09 10:56:55 gyz-ohos ollama[5717]: llama_new_context_with_model:        CPU compute buffer size =   504.25 MiB
3月 09 10:56:55 gyz-ohos ollama[5717]: llama_new_context_with_model: graph splits (measure): 1
3月 09 10:56:56 gyz-ohos ollama[5717]: loading library /tmp/ollama2883110293/cpu_avx2/libext_server.so
3月 09 10:56:56 gyz-ohos ollama[5717]: {"function":"initialize","level":"INFO","line":433,"msg":"initializing slots","n_slots":1,"tid":"139820697376512>
3月 09 10:56:56 gyz-ohos ollama[5717]: {"function":"initialize","level":"INFO","line":442,"msg":"new slot","n_ctx_slot":2048,"slot_id":0,"tid":"1398206>
3月 09 10:56:56 gyz-ohos ollama[5717]: time=2024-03-09T10:56:56.272+08:00 level=INFO source=dyn_ext_server.go:161 msg="Starting llama main loop"
3月 09 10:56:56 gyz-ohos ollama[5717]: {"function":"update_slots","level":"INFO","line":1565,"msg":"all slots are idle and system prompt is empty, clea>
3月 09 10:56:56 gyz-ohos ollama[5717]: [GIN] 2024/03/09 - 10:56:56 | 200 |   3.44796187s |       127.0.0.1 | POST     "/api/chat"
`

**Comment by jmorganca** [comment] 2024-06-04 06:59
Hi this should be fixed in the latest version of Ollama (incl the wide character from the previous comment :). Please let me know if you're still seeing issues

**Closed by jmorganca** 2024-06-04 06:59 UTC

**Comment by GeYingzhen01** [comment] 2024-06-04 07:17
中文：新版本没有再出现类似问题，一切正确。非常感谢!
English:The new version has not encountered similar issues; everything is correct. Thank you very much.
![image](https://github.com/ollama/ollama/assets/155865563/449d4e0d-1928-4c6a-a931-45775c826327)
