### ISSUE TITLE
empty response

### ISSUE THREAD

**Issue by themw123** [ollama/ollama#4724] opened 2024-05-30 15:37 UTC
### What is the issue?

I am getting an empty response string with llama3:8b.
Different models like mistral-instruct are working fine.

Setup:
- windows 11
- newest ollama version
- llama3:8b(latest)

When context gets to high (approximately after exchanging 20 question/answer pairs) by appending the history with every request, i get an empty response from time to time like in 30% of responses.

Here is my code:

```
self.messages = [{"role": "system", "content": system_role}]
self.messages.append({"role": "user", "content": my_input_text})

url = "http://localhost:11434/api/chat"
data = {
    "model": "llama3:8b",
    "messages": self.messages,
    "stream": True
}
response = requests.post(url, json=data)   

for chunk in response.iter_lines():
    if chunk:
        chunk = chunk.decode('utf-8')
        chunk = json.loads(chunk)
        content = chunk['message']['content']
        print(content, end="", flush=True)
        yield content
```

### OS

Windows

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.1.39

**Comment by dominikvalk** [comment] 2024-06-05 18:12
same for me.

**Comment by 22Black22** [comment] 2024-06-05 19:20
same for me. llama3 with several messages and instant empty response

**Comment by Qualzz** [comment] 2024-06-30 23:10
Same for me with gemma2, llama3. 

What is weird is that using open web ui, long contexts works fine, but using the ollama.js chat function, > 512 token and the answer are empty with "`model does not support sliding window, limiting generation`" visible in the ollama logs

**Comment by SheMelody** [comment] 2024-07-03 14:35
This seems to be an issue specific to Windows. I'm having the same exact problem. When using ollama on Linux it's perfectly fine, I literally had zero issues in there, same versions.

**Comment by pdevine** [comment] 2024-09-12 23:19
I'm having a hard time reproducing this in Windows (and haven't seen it in either Linux or MacOS). I've been trying with Windows 11 and a 7900 XTX, but no luck.

Given the issue was opened in May, let's go ahead and close it, but if someone can repro I can reopen.

**Closed by pdevine** 2024-09-12 23:19 UTC
Labels: bug

**Comment by v3ss0n** [comment] 2024-09-25 16:58
Is this bug solved? i am still encountering. Why this is closed as completed? which PR fixes it?

**Comment by codejq** [comment] 2025-01-25 17:25
For me, the issue was, that I set the temperature to 0.5 and I had to change it ti to 0.1 and I had to omit the format: JSON
