### ISSUE TITLE
Ollama api port confusion

### ISSUE THREAD

**Issue by 17Reset** [ollama/ollama#3669] opened 2024-04-16 09:03 UTC
### What is the issue?

After I start the two ollama services on the specified ports (8080: llm_api, 8081:emb_api), I add the local gguf model to each of them, and then use `curl http://192.168.18.165:8080/api/tags` to view the model inside llm_api, which will print the emb_api with the models. This is obviously incorrect.

### Steps to reproduce

```
OLLAMA_HOST=192.168.18.165:8080 ollama serve
curl http://192.168.18.165:8080/api/create -d '{
  "name": "smaug_34b_q8",
  "modelfile": "FROM /mnt/Athena/Model/Abacus/llm_quantized/smaug_34b_q8.gguf"
}'
```

```
OLLAMA_HOST=192.168.18.165:8081 ollama serve
curl http://192.168.18.165:8081/api/create -d '{
  "name": "bge-large-en",
  "modelfile": "FROM /mnt/Athena/Model/BAAI/repo/bge-large-en-v1.5-gguf/bge-large-en-v1.5-f16.gguf"
}'
```

### OS

Linux

### Ollama version

ollama version is 0.1.31

### GPU

Nvidia

### CPU

Intel

**Comment by thinkverse** [comment] 2024-04-16 11:19
I don't think this would be considered incorrect. Ollama saves models to a shared location. For Linux that is `/usr/share/ollama/.ollama/models`. There is an `OLLAMA_MODELS` environment variable you can set that I just saw in a comment.

https://github.com/ollama/ollama/blob/f335722275d8184836d1b777f356fa7b0a012ede/server/modelpath.go#L102-L107

@jmorganca could this be used to set the models directory for each service?

**Comment by thinkverse** [comment] 2024-04-16 11:46
Tested setting the `OLLAMA_MODELS` environment variable and with that each service has its own model directory.

When the services were first created each `/api/tags` had no models.

<img width="1120" alt="Screenshot 2024-04-16 at 13 40 09" src="https://github.com/ollama/ollama/assets/2221746/96a15b96-f1ce-4247-9226-3f8050e8c3b0">

Afterward, I created a model from Ollama's default shared directory into only one service.

<img width="1206" alt="Screenshot 2024-04-16 at 13 42 38" src="https://github.com/ollama/ollama/assets/2221746/036cf028-018d-47e8-81ec-aca0ca916d83">

And when I later checked `/api/tags` only one service has a model in it.

<img width="1158" alt="Screenshot 2024-04-16 at 13 44 17" src="https://github.com/ollama/ollama/assets/2221746/ac4faae4-a9bc-45cf-8a91-237d8c6004b6">

If this is your desired result then set the `OLLAMA_MODELS` environment variable when creating your service so each service has its own models directory.

```bash
OLLAMA_HOST=127.0.0.1:8081 OLLAMA_MODELS=~/Ollama/emb_models ollama serve
```

**Comment by dims** [comment] 2024-04-16 12:02
Duplicate of https://github.com/ollama/ollama/issues/3666

**Comment by pdevine** [comment] 2024-04-16 23:13
This is expected behaviour. You can use the `OLLAMA_MODELS` env variable to change the location for each instance.

**Closed by pdevine** 2024-04-16 23:13 UTC
Labels: bug, needs-triage

**Comment by 17Reset** [comment] 2024-04-17 03:04
Thanks, I was the one who didn't read the documentation carefully.
