### ISSUE TITLE
Supports the computing power of NPUs and GPUs provided by Intel Ultra processors

### ISSUE THREAD

**Issue by Perry961002** [ollama/ollama#4150] opened 2024-05-04 11:11 UTC
I'm using an Intel Ultra processor and its GPU and NPU are never used when running the llama2 model

**Comment by Mr-Wang-YourNeighbor** [comment] 2024-05-14 15:29
I have the same question about AMD NPU

**Comment by Mr-Wang-YourNeighbor** [comment] 2024-05-14 15:31
In the future, having an NPU in the CPU will definitely become commonplace. I hope the author can focus more on this aspect.

**Comment by pdevine** [comment] 2024-05-15 01:01
Going to close this as a dupe of #3004

**Closed by pdevine** 2024-05-15 01:01 UTC
Labels: feature request

**Comment by Mr-Wang-YourNeighbor** [comment] 2024-05-15 01:28
all right
