### ISSUE TITLE
Command R model works very slow on MAC 

### ISSUE THREAD

**Issue by Zig1375** [ollama/ollama#3404] opened 2024-03-29 10:03 UTC
### What is the issue?

The Command R model runs very slowly on a Mac (with an M2 Pro CPU and 32GB of RAM). It utilizes only 80-90% of the CPU, out of a possible 1200% (which results in processing about 1 token every 20-30 seconds).

However, on a Windows 11 machine (equipped with an Nvidia 4070 GPU), it runs very quickly (processing about 5-10 tokens per second).

Previously, with other models, the situation was the opposite. The Mac ran much faster, even surpassing the performance of the Windows machine.

### What did you expect to see?

Mac works faster, at least a few tokens per second.

### Steps to reproduce

Install Command R model on mac m2 pro.

### OS

macOS

### Architecture

arm64

### Ollama version

0.1.30

### GPU

Apple

### CPU

Apple

**Comment by ylca0** [comment] 2024-04-03 10:52
This appears to be due to insufficient memory: #2324

**Comment by Zig1375** [comment] 2024-04-03 11:05
On my mac there are about 10GB RAM free!!!
Why it doesn't use all the memory?

**Comment by ylca0** [comment] 2024-04-03 11:10
I had a similar situation: there was still a lot of unused memory. 
I'm guessing it has something to do with mode selection strategy? I wonder if there's a solution.

**Comment by igorschlum** [comment] 2024-04-06 00:00
How much memory do you have in Total on your computer. I have 32GB on my Mac. I can test a script and let you know if it is slow also on my computer.

**Comment by ylca0** [comment] 2024-04-06 06:18
@igorschlum I have 36GB memory. ollama uses pure cpu calculations when I run the 70b 4bit model, and the speed is around 20-30 seconds per token. I tried to run it using llama.cpp, but the memory usage was too high and the computer crashed.

**Comment by sourcedexter** [comment] 2024-04-16 09:16
I have the same issue on Mac M1, plenty of memory is free and yet the gneration is very very slow. i have tested other models like Llama2, codegemma, and those are pretty fast.

**Comment by SmileSydney** [comment] 2024-06-01 07:09
Having the same issue M2 with 64GB. Activity Monitor shows 9GB used.

**Comment by dhiltgen** [comment] 2024-06-01 22:25
Can you try again on the latest release?  On a 32G M2 I'm seeing ~7 TPS and
```
% ollama ps
NAME            	ID          	SIZE 	PROCESSOR     	UNTIL
command-r:latest	b8cdfff0263c	24 GB	6%/94% CPU/GPU	4 minutes from now
```

**Comment by Zig1375** [comment] 2024-06-02 11:51
I'll be able to test it tomorrow

**Comment by Zig1375** [comment] 2024-06-02 20:16
Wow! It works very very fast now! Thank you!

**Comment by igorschlum** [comment] 2024-06-02 20:35
@Zig1375 good news, if the issue is solve, could you please close it?

**Closed** 2024-06-02 21:22 UTC
Labels: bug
